### ISSUE TITLE
Broken links in spec

### ISSUE THREAD

**Issue by pafcu** [matrix-org/matrix-doc#1010]
https://matrix.org/docs/spec/client_server/r0.2.0.html contains links to https://matrix.org/docs/spec/r0.2.0/client_server.html which does not exist.

**Comment by richvdh** [comment]
Thanks for the report. The only broken link I could find was in 'search' (https://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-search) - did you see any others?

I have fixed this with a redirect, anyway.
