### ISSUE TITLE
In AS API, PUT /transactions/* endpoint, document how to distinguish state event from timeline event

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#1014]
as indicated in https://github.com/matrix-org/matrix-react-sdk/pull/1453 and https://github.com/vector-im/riot-web/issues/5176, a user can send an event that has a type that matches a state event (e.g. `m.room.topic`) as a timeline event.  Obviously, this won't change the room's state, but since `PUT /transactions/*` doesn't indicate whether the event was sent as a state event or a timeline event, it could result in a confused AS if this happens, as the AS may think that the state has changed when it actually hasn't.

**Comment by richvdh** [comment]
It should be possible to distinguish a state event by the presence of a `state_key` field?

**Comment by uhoreg** [comment]
> It should be possible to distinguish a state event by the presence of a `state_key` field?

Yeah, I guess that works.  Maybe that could be documented somewhere.

**Comment by richvdh** [comment]
Yeah. It's in https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#state-event-fields ("The presence of this key makes this event a State Event"), but I very much agree it's impossible to find there.
