### ISSUE TITLE
Add https://github.com/Nordgedanken/Morpheus

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-doc#1019]
Morpheus is a alpha qt client written in golang which main goal is to have a native windows focused client.

I am currently writing on it a chat can be found here: #Morpheus:matrix.ffslfl.net 
Currently a bit is to do (like actualy room switching) but that should be done in the next week I think. 

If you have any questions or if I missed anything to write in here please ask or let me know.
I will add a comment as soon as the above missing crucial feature is added and would love if i can get it listed at matrix.org :)

**Comment by richvdh** [comment]
@MTRNord could you make a PR to add it as per https://github.com/matrix-org/matrix-doc/blob/master/supporting-docs/projects/README.md?

**Comment by MTRNord** [comment]
@richvdh I will :+1: didn't saw that README :)
