### ISSUE TITLE
move MXID grammar out of the intro

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1031]
it's impossible to find there. we should also put the intro on the index page of the spec or something, as it's very hard to spot

**Comment by richvdh** [comment]
It *is* on the index page of the spec: 
![image](https://user-images.githubusercontent.com/1389908/31862545-93e54294-b737-11e7-8afa-183ccadcffb8.png)

Agreed that the identifier grammars belong in the appendices rather than the intro, though.

**Comment by ara4n** [comment]
my point was to consider inlining it into the index page, as the crappy link you've highlighted seems incredibly hard for people to spot, especially when it contains key information.  I repeatedly miss it; i think because my brain assumes that it's a random 'intro to matrix' tutorial that's being linked, rather than the common missing material for the per-API specs below.

**Comment by richvdh** [comment]
fair enough, but that's not what you said ;)

**Comment by ara4n** [comment]
sorry, i thought that the implication to inline was clear given the link's already present. my bad for being too terse.
