### ISSUE TITLE
Doc @room notifications

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-doc#1033]
Documentation: https://docs.google.com/document/d/1qRdlg94cr9YXxPCwhW4HgI2oDrqQOUKX5HptZFBGf6o/edit#

ie. the `sender_notification_permission` pushrule condition.

**Comment by turt2live** [comment]
Can the doc made public for viewing please?

**Comment by richvdh** [comment]
doc perms fixed, I hope

**Comment by KitsuneRal** [comment]
Still can't access the doc: "not found our you do not have access to it".

**Comment by richvdh** [comment]
see also #1101 which is about the power_levels for this I think
