### ISSUE TITLE
none of the Content Repository endpoints in C-S say whether they require auth or are rate limited

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#1046]

**Comment by uhoreg** [comment]
looks like a few other endpoints are missing this information too, so this should probably be fixed as part of a larger cleanup task

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-doc/pull/1064 documents the rate limiting and auth requirements, but doesn't handle the rest of the endpoints. This ticket could either be closed or be converted to a checklist of known endpoints which need clarification.

**Comment by turt2live** [comment]
I've opened https://github.com/matrix-org/matrix-doc/issues/1370 to cover the general case of very few things declaring rate limiting.

The media repo specifically does declare rate limiting and auth now though, so I'm going to go ahead and close this.
