### ISSUE TITLE
Formally spec Content Security Policy for media repo

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1066]
This shouldn't be an implementation-specific thing, given it needs to protect all clients

**Comment by turt2live** [comment]
What is the policy?

**Comment by turt2live** [comment]
The policy used by synapse is `Content-Security-Policy: default-src 'none'; script-src 'none'; plugin-types application/pdf; style-src 'unsafe-inline'; object-src 'self';` fwiw
