### ISSUE TITLE
Prevent sending push notifications to mobile devices if activity on desktop client device

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-doc#1119]
At now Riot mobile apps play sound notifications always on new messages, so if I actively use desktop Matrix client - my device rings very often, so I must turn notifications off, and not forgot to give back it on when I go away from desktop computer, and do this multiple times per day.

For solve this problem - will be good to detect user activity on desktop device client, and suppress (or delay) sending push notifications to mobile devices if activity on desktop device is detected some time ago.

**Comment by richvdh** [comment]
https://github.com/vector-im/riot-web/issues/469
