### ISSUE TITLE
Federation /version endpoint should not be under /v1/

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-doc#1121]
The federation version endpoint added by #1072 should not be

`/_matrix/federation/v1/version`

and instead should be

`/_matrix/federation/version` or `/_matrix/federation/versions`

similar to `Client 2.1  /_matrix/client/versions` which is outside any version's tree allowing for queries in the blind to find out what is available.

**Comment by maxidor** [comment]
@jevolk that endpoint is about the **server implementation** version, not the protocol version, which is a reasonable place to be, as the structure describing it might change over the spec versions.

**Comment by jevolk** [comment]
How then does the remote party know if the server supports `/v1/` `/v2/` or `/vx/`? If the endpoints change enough to warrant another query for version information shouldn't that increment their `/vx/` prefix instead? Will a `/v2/version` have different name branding than `/v1/version`? If not, why have all these versions inside each version?

There should be a single root-level query to find out what the server is and what it supports.

**Comment by maxidor** [comment]
it currently doesn't, since there is no protocol related `/version` endpoint.

**Comment by maxidor** [comment]
> How then does the remote party know if the server supports /v1/ /v2/ or /vx/?

They don't, there is no equivalent of `/version` for the federation protocol.

> If the endpoints change enough to warrant another query for version information shouldn't that increment their /vx/ prefix instead?

It would, but right now there never was a release of the federation spec, and therefore there there can't be a v2 yet.

> Will a /v2/version have different name branding than /v1/version? If not, why have all these versions inside each version?

Who knows what will happen in v2, it's not out yet.

> There should be a single root-level query to find out what the server is and what it supports.

What the server is: I disagree.  
What it supports: I agree. Feel free to propose a draft.

**Comment by jevolk** [comment]
>> How then does the remote party know if the server supports /v1/ /v2/ or /vx/?

> They don't, there is no equivalent of /version for the federation protocol.

Exactly, that's why to be both consistent with the client-server specification *and* functionally useful at the same time it would make more sense to move this up a level.

>> If the endpoints change enough to warrant another query for version information shouldn't that increment their /vx/ prefix instead?

> It would, but right now there never was a release of the federation spec, and therefore there there can't be a v2 yet.

There's no reason why an endpoint can't have individual versioning. Granular versioning is a good thing. Lessons were learned and conclusions were drawn from experience to this effect with the client-server specification in this regard, if I recall, by admission of its maintainers.

>> There should be a single root-level query to find out what the server is and what it supports.

> What the server is: I disagree.
> What it supports: I agree. Feel free to propose a draft.

Consider finally that we already know much of what this endpoint provides by way of the HTTP `Server: ` header. Granted, that doesn't have to say `Synapse/0.26` it can say `nginx` so this endpoint as it stands isn't entirely useless, but usually useless.

**Comment by richvdh** [comment]
yup this is about finding out the server name and version, and the only reason it's of value is because of reverse proxies. It's in the right place imho.

**Comment by jevolk** [comment]
Closing this doesn't solve the problem of a lack of federation /versions endpoint. Do you want a new issue opened or this one repurposed?

**Comment by maxidor** [comment]
@jevolk the first step is to draft a proposal, ideally as a Google Doc. You should not re-open this issue.

**Comment by richvdh** [comment]
you can open a separate issue if you want.
