### ISSUE TITLE
userId in /_matrix/client/r0/presence/{userId}/status is a redundant parameter

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-doc#1125]
The presence status endpoint in 11.6.2.1 marked as `Requires auth: Yes`

PUT `/_matrix/client/r0/presence/{userId}/status`

does not require a userId path parameter because the specification says:

> You cannot set the presence state of another user.

This means that client implementations must urlencode a `userId` and server implementations must urldecode a `userId` only to compare the `userId` to that of the `access_token` which is already known. This is redundant.

While I won't advocate here specifically for moving /status up a level into /presence/, this is still a useless operation and we can do better with some type of restructuring.

**Comment by maxidor** [comment]
@jevolk [you can](https://github.com/matrix-org/matrix-doc/blob/master/specification/application_service_api.rst#identity-assertion), if you have an AS token.

**Comment by jevolk** [comment]
> @jevolk you can, if you have an AS token.

That's spukhafte fernwirkung. That should probably be more clearly marked everywhere in the spec where access_tokens and parameters like this are discussed, but that's a separate issue.
