### ISSUE TITLE
auth_events is redundant with at best a neutral use case, at worst, nefarious.

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-doc#1128]
Federation unstable.4.1 "PDU Fields" lists:

Key
> auth_events

Type
> List of (String, {String: String}) pairs

Description
> Required. Event IDs and hashes for the "auth events" of this event.

The section goes on to say:
> The auth_events field of a PDU identifies the set of events which give the sender permission to send the event. The auth_events for the m.room.create event in a room is empty; for other events, it should be the following subset of the room state:
>
>The m.room.create event.
The current m.room.power_levels event, if any.
The current m.room.join_rules event, if any.
The sender's current m.room.member event, if any.

The information provided by this object is redundant. Whether or not the sender has permission to send the event depends on the state of the room. The state of the room, relative to an event, depends on where it is attached to the graph. Attachment is made through the `prev_events` references. If the state at the point of attachment does not *permit* the attachment, the supplied `auth_events` **can only be invalid**. If the state of the room at the point of attachment is not *known*, the supplied `auth_events` **can only be untrusted** for wont of concurrence by resolving the state of the room.

Thus the supplement of `auth_events`, involving a list of event ID's, and their hashes objects, in every event, adding nearly 300 bytes *to every single event*, state and non-state, is redundant at best and misleading at worst.

**Comment by richvdh** [comment]
auth_events are key to the v2 state resolution algorithm.
