### ISSUE TITLE
Specify /whoami endpoint supports AppServices

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1135]
It's easy to forget that application services must also be supported by the /whoami GET API endpoint. A note should be added to the spec to remind the user that this is the case.

**Comment by turt2live** [comment]
ftr this means that `?user_id=@_freenode_whatever:matrix.org` gives `{"user_id":"@_freenode_whatever:matrix.org"}` - assuming the proper access checks pass, of course.

**Comment by anoadragon453** [comment]
Oh yeah, AS' pass the user_id as a parameter in their request. So we just need to give that back. Super easy!

**Comment by jevolk** [comment]
These notices should probably be put on every endpoint where it applies. Already made a similar mistake in #1125.

**Comment by richvdh** [comment]
clarified in #1152 thanks to @turt2live
