### ISSUE TITLE
Per-user room display names

### ISSUE THREAD

**Issue by Ekleog** [matrix-org/matrix-doc#1138]
I was just thinking about a use case that arises with the growth of the matrix network: room display name collisions. What could happen is that two admins may put the same display name on two rooms, and a user who is present on both rooms will find it hard to disambiguate the two rooms in the list.

So I was thinking it may be a good idea to allow the user to override the room display name. This would need to be stored somewhere in the room state, I guess, so that all clients of the same user can agree on the name.

This would also help when a user wants to have a custom naming scheme in order to more easily sort their rooms. (this last use case being the one I tried to handle that triggered the question of “what if two rooms have the same display name?”)

**Comment by turt2live** [comment]
This sounds a lot like https://github.com/matrix-org/matrix-doc/issues/690

**Comment by Ekleog** [comment]
Indeed, I searched for “room display name” and it didn't turn up, but with “rooms displayname” it does. Sorry and thanks! :)
