### ISSUE TITLE
"edu_type" should be "type"

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-doc#1143]
For consistency. They're also already in the `edus` array.

**Comment by maxidor** [comment]
Where exactly do you see it?

**Comment by jevolk** [comment]
> Where exactly do you see it?

@maxidor It's in [Section 5](https://matrix.org/docs/spec/server_server/unstable.html#edus) and the [Synapse implementation](https://github.com/matrix-org/synapse/blob/master/synapse/federation/units.py#L39). This is not a documentation error. There is just no reason to call it `edu_type` rather than just `type`. Tor the latter puts the object on its way to being a proper event while the former precludes that. Consider `content` is not called `edu_content`, etc...

**Comment by richvdh** [comment]
It is annoying, but I don't think it's a pressing thing to change.
