### ISSUE TITLE
Mention that /sync and /events is special for AS user

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-doc#1144]
Historically, an AS user could use /sync and /events to get all updates for all rooms that they are "interested in". This functionality has been deprecated for a long time due to performance issues, and in fact its has been broken in synapse for a while. The plan is for this to be removed from future versions of synapse.

We should mention that /sync and /events won't work for AS users (but will for AS virtual users).

Alternatively, we could look to make /sync to work as usual for AS users, meaning no special documentation would be needed in the spec (apart from mentioning the change).

**Comment by richvdh** [comment]
Let's assume we're doing option 1 for now.
