### ISSUE TITLE
Periodically checkpoint the state

### ISSUE THREAD

**Issue by Ekleog** [matrix-org/matrix-doc#1168]
If I understand federation correctly, currently, the slow part is state events. Because when a server joins a new room, it must fetch all previous state events, in order to build up its own state.

I was wondering whether it would be a good idea to periodically have all servers that participate in a room sign together a checkpoint of the state, so that late-joining servers could just fetch the last checkpoint and all state events thereafter.

Obviously, this will have security implications as well (what if only a part of the servers sign an invalid checkpoint?), and I didn't think this through as the idea just arose in a discussion with a friend, but I thought this may be a nice-to-have that could ease off a lot federated traffic.

**Comment by richvdh** [comment]
they do just get a snapshot of the state, I'm afraid. See https://matrix.org/docs/spec/server_server/unstable.html#joining-rooms:

> The resident homeserver then accepts this event into the room's event graph, and responds to the joining server with the full set of state for the newly- joined room.

The slow part is (I think) (mostly) checking the signatures on the state events.

[aside: I'd encourage discussion of ideas like this in the matrix rooms, rather than here]

**Comment by Ekleog** [comment]
I think my “snapshot of the state” expression was unclear. According to your link, what is passed is “[a] list of events giving all of the events in the auth chains for the join event and the events in state” and “[a] complete list of the prevailing state events at the instant just before accepting the new m.room.member event”.

This is a list of all the state events, meaning that the receiving server has to download and check the signatures on all the state events. I'm not sure what the download time is versus the checking time, but do know that joining big rooms for the first time is much slower than I think it should be.

What I was thinking was to have all keyservers sign a “consolidated snapshot of the state”, that contains a pre-computed state for the state that takes into account all previous state events, signed with all the participating HSs keys. Which means only one almost-constant-size download and one signature per participating HS to check, instead of one event and one signature per state event.

From a complexity perspective, if N is the number of HS, M is the number of members in the room at the time of join, and E is the number of state events, the current solution is O(E) download, O(E) signature checks; and what I'm putting forward is O(P) download, O(N) signature checks. And necessarily N ≤ P ≤ E, and I'd guess N ≤ P ≪ E for big long-lived rooms (the ones currently causing issues).

Does that make more sense now? If so, would it be possible to reopen the issue in order to discuss the security implications such a consolidated state event would have ?

**Comment by Ekleog** [comment]
Also, as I missed your aside before answering: unfortunately all rooms for development of matrix that I know of are too active to allow for long-delay large-content discussion like one that would be I think needed for spec changes… that said, maybe there is a room I don't know of?

**Comment by turt2live** [comment]
[#matrix-architecture:matrix.org](https://matrix.to/#/#matrix-architecture:matrix.org) is currently the best room for spec discussions, like this.

**Comment by richvdh** [comment]
let's take it to matrix-architecture as @turt2live suggests. I don't understand how what you're proposing would help, and I suspect that there are some misconceptions which can be cleared up more easily in a synchronous conversation

**Comment by Ekleog** [comment]
So for the discussion, it all started at https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$152218630064lehXP:sw1v.org (with some off-topic discussion about my issues joining #matrix-architecture) then https://matrix.to/#/!fILrmqIZQfJcrUiBRk:matrix.org/$152218842954MeyQl:gaspard.ninja .

What I remember of this is that it's possibly not signature checking that takes the most time for a join, but maybe key fetch, hence such a change would likely be of little use.
