### ISSUE TITLE
Clarify that only the from parameter is required on /keys/changes

### ISSUE THREAD

**Issue by mujx** [matrix-org/matrix-doc#1170]
According to the current [spec](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#get-matrix-client-r0-keys-changes) both `from`  and  `to` query parameters are required for a valid request but testing against synapse v0.26 shows that only `from` is required.

Maybe clarify that an empty `to` implies the latest state? I can submit a PR if that indeed is not a synapse bug.

**Comment by richvdh** [comment]
It is neither a spec bug nor a synapse bug. Synapse will cope if you do not provide a `to` but other implementations may not.

There's an argument for enforcing it correctly in Synapse to stop people writing buggy clients, I suppose.

**Comment by mujx** [comment]
This sounds like a synapse bug then; it shouldn't try to cope if the spec says `REQUIRED` but the parameter is missing. It should throw an error.
