### ISSUE TITLE
Cleaning an Home Server

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/matrix-doc#1179]
Sorry if I missed information somewhere, but I cannot find how to “clean” an home server.

Basically, I would want to remove:
– communities with no-one inside (basically were created as tests);
– local rooms or copy of federated rooms for which no local user are inside anymore.

Currently I think there is a growing number of “dead rooms” on my HS, and I’d like to get ride of them.

Thanks for your help!

**Comment by richvdh** [comment]
not really a spec issue, I'm afraid.

**Comment by Half-Shot** [comment]
Sorry @ArchangeGabriel, could you ask in matrix-org/synapse?
