### ISSUE TITLE
Spec proposals page

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1181]
Create a new page for tracking progress of spec proposals.

Thinking https://docs.google.com/document/d/1wLln7da12l0H5YgAh5xM2TVE7VsTjXzhEwVh3sRBMCk/edit

**Comment by turt2live** [comment]
Is this something that should be opened on the matrix.org repo rather than the spec?

**Comment by ara4n** [comment]
dup #1233
