### ISSUE TITLE
Clarify the difference between /state/:event and /state/:event/:stateKey

### ISSUE THREAD

**Issue by njouanin** [matrix-org/matrix-doc#1182]
In client-server spec '6.3.1   GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}', roomId, eventType and stateKey are required. 
The get example miss the eventType parameter : 
`GET /_matrix/client/r0/rooms/%21636q39766251%3Aexample.com/state/m.room.name/ HTTP/1.1`

**Comment by richvdh** [comment]
it's not a very good example, but it is correct: `eventType` is `m.room.name` and `stateKey` is empty.

**Comment by njouanin** [comment]
‘stateKey‘ is marked as required in the documentation. How can it empty in the example ?

**Comment by maxidor** [comment]
@njouanin the key only needs to be there, the content can be anything (except null). Empty value is content as well.

**Comment by njouanin** [comment]
what's the difference with 6.3.2 endpoint then ?

**Comment by richvdh** [comment]
now *that* is a good question. An extra `/`, maybe?

**Comment by njouanin** [comment]
I mean functionally... 
Anyway, a required argument which can be empty is troublesome and it should be clarified in the doc. 
As I understand stateKey is not required (can be blank) and in this case it is equivalent to calling 6.3.2. Am I wrong ?

**Comment by turt2live** [comment]
I've renamed this so I can understand the issue more at a glance. I'd like to just axe the redundant endpoint and fix the discrepancy with documentation, however swagger requires that all path parameters be listed as "required". I suspect for this particular case we can get away with that though and say "required, can be an empty string" and be fine.
