### ISSUE TITLE
Document key-share requests

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1183]
Documentation: https://docs.google.com/document/d/1m4gQkcnJkxNuBmb5NoFCIadIY-DyqqNAS3lloE73BlQ
PRs: #1465

We should document the events used by riot to do keyshare requests

**Comment by benparsons** [comment]
(richvdh, using your prop as testdata)

**Comment by richvdh** [comment]
it's in use, so I guess this is pr-missing

**Comment by richvdh** [comment]
related to #501
