### ISSUE TITLE
RoomEvent type not described in 6.3.6 of client spec

### ISSUE THREAD

**Issue by njouanin** [matrix-org/matrix-doc#1184]
The `GET /_matrix/client/r0/rooms/{roomId}/messages` response format contains a `chunk` attribute of type `[RoomEvent]`. The `RoomEvent` type is not describe in this paragraph. It is only described in `GET /_matrix/client/r0/initialSync` spec which is marked as deprecated.
Can you describe the `RoomEvent` type ?

**Comment by richvdh** [comment]
this appears to be referring to https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-rooms-roomid-messages, ftr

**Comment by KitsuneRal** [comment]
For the further record, it's `message_pagination.yaml`, and the contents of `chunk` look very much like `event_batch.yaml`. @richvdh, should I add the respective `"$ref":`, since I just submitted the PR for spec cleanup anyway?

**Comment by KitsuneRal** [comment]
It actually might rather be an array of `"definitions/event-schemas/schema/core-event-schema/room_event.yaml"`...

**Comment by turt2live** [comment]
That PR is https://github.com/matrix-org/matrix-doc/pull/1186 ftr
