### ISSUE TITLE
Clarify/prioritize http status code vs errorcode

### ISSUE THREAD

**Issue by maxidor** [matrix-org/matrix-doc#1188]
As seen by https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/%241525345332979375uwIJj:matrix.org some client rely on the error code string in the body instead of the returned status code. while some others rely on HTTP status code only.

HTTP status code and errorcode seem to be redundant piece of information at this point, so it would be good to take appropriate action depending on the intended purpose:
- If status code always match a specific errorcode, then why have both? and if we must keep both, decide which one has priority and which one should be used by clients.
- If they don't exactly match, or if the HTTP status code is a generic indication, then clarify the generic meaning of status codes in the spec (appendixes maybe)?

**Comment by richvdh** [comment]
I couldn't agree more. I think in general we need both, because we want more expressiveness than is plausible from an HTTP status code alone; however this absolutely needs tidying up.

https://github.com/matrix-org/matrix-doc/issues/603 is related.

**Comment by njouanin** [comment]
The HTTP status code could also be added to the json error object, something like :
``
{
  "errcode": "<error code>",
  "error": "<error message>",
 "http_status": 401
}
``

**Comment by turt2live** [comment]
I've labelled this as a clarification, although the OP is half suggestion half clarification.
