### ISSUE TITLE
Ignoring Users

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1197]
Documentation: https://docs.google.com/document/d/1Jex7lDAwmv0KcgyL9oeGfUCsjw0CWSqedPKZ1ViSVis/edit
Author: @erikjohnston 
Date: 03/05/2016
PRs: #1142

**Comment by turt2live** [comment]
This has been completed: https://github.com/matrix-org/matrix-doc/pull/1142
