### ISSUE TITLE
Device Management API

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1201]
Documentation: https://docs.google.com/document/d/1H8Z5b9kGKuvFkfDR1uQHaKdYxBD03ZDjMGH1IXQ0Wbw/edit#heading=h.8rtccxo23ng
Author: @richvdh
Date: 14/07/2016

**Comment by uhoreg** [comment]
Seems like this has already been documented for a while: https://matrix.org/docs/spec/client_server/r0.3.0.html#device-management
