### ISSUE TITLE
3rd Party Entity lookup API

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1203]
Documentation: https://docs.google.com/document/d/13NGa46a_WWno-XYfe8mQrglQdtOYMFVZtxkPKXDC3ac/edit#heading=h.m0btedxhv6ao
Author: @leonerd 
Date: 21/07/2016
PRs: #1353

**Comment by KitsuneRal** [comment]
Ftr: #1414 is amending #1353 (under review now).

**Comment by turt2live** [comment]
this got merged
