### ISSUE TITLE
Proposal for multi-device deletion API

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1205]
Documentation: https://docs.google.com/document/d/1LaA9Q96ytumLmE-eAscONMMX5rE26ri4G7uj-rmltbs/edit
Author: @richvdh
Date: 12/10/2016
PRs: 1239

**Comment by t3chguy** [comment]
`spec-pr-missing` seems incorrect as this has already been merged it seems: https://github.com/matrix-org/matrix-doc/pull/1239

**Comment by turt2live** [comment]
I asked elsewhere, but surely merged means these can be closed?

**Comment by t3chguy** [comment]
Going off the state diagram it seems that way
![image](https://user-images.githubusercontent.com/2403652/41851165-f441dd2e-787e-11e8-931b-d4e181c4f2df.png)

**Comment by Half-Shot** [comment]
Closing. Please reopen if this is not the process.

**Comment by turt2live** [comment]
(can someone select all & close the others?)

**Comment by benparsons** [comment]
@turt2live is done
