### ISSUE TITLE
Publishing Room Lists for 3rd party networks

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1207]
Documentation: https://docs.google.com/document/d/12mVuOT7Qoa49L_PQAPjavoK9c2nalYEFOHxJOmH5j-w/edit
Author: @erikjohnston
Date: 21/10/2016

**Comment by Half-Shot** [comment]
Worth pointing out that this already exists, albeit totally unspecced and broken. I'm going to be writing up some issues on these endpoints...

**Comment by turt2live** [comment]
Doesn't this exist in the form of https://matrix.org/docs/spec/application_service/r0.1.0.html#application-service-room-directories ?

**Comment by Half-Shot** [comment]
Yes, it has since been specced :laughing:

**Comment by turt2live** [comment]
I'm just going to quietly mark this as merged...
