### ISSUE TITLE
Thoughts on Room State

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1210]
Documentation:
Author: @NegativeMjark 
Date: 28/11/2016

**Comment by richvdh** [comment]
@benparsons : can we close this?

**Comment by ara4n** [comment]
it was opened to track the doc on google drive, in case we want to use it as a basis for state improvements in future. if it isn’t useful for that @richvdh then feel free to close it.

**Comment by benparsons** [comment]
@richvdh yes, I'll update the generator to include all issues which are correctly labelled.
