### ISSUE TITLE
Device List Update Stream

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1212]
Documentation: https://docs.google.com/document/d/1fNBZUeMlp0fn0en5bCji5fn6mSvj48UylWfGKrk8ZIw/edit#heading=h.j3k62x61k895
Author: @richvdh 
Date: 18/01/2017
PRs: #1284, #1648

**Comment by turt2live** [comment]
more reference material: https://github.com/matrix-org/synapse/pull/1857 https://github.com/matrix-org/synapse/issues/2210

**Comment by uhoreg** [comment]
Client-Server side should be fixed by https://github.com/matrix-org/matrix-doc/pull/1284

**Comment by uhoreg** [comment]
Server-Server side seems to be the "Update 10 July 2018" section of the above document.
