### ISSUE TITLE
Related Groups (i.e. flair)

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1214]
Documentation: https://docs.google.com/document/d/1wCLXwUT3r4gVFuQpwWMHxl-nEf_Kx2pv34vZQQVb_Bc/edit#heading=h.82i09uxamcfq
Author: @lukebarnard1 
Date: 03/10/2017

**Comment by turt2live** [comment]
I'm declaring this as obsolete now that [MSC1772](https://github.com/matrix-org/matrix-doc/issues/1772) (Spaces, or Communities v2, or Groups v2) is in FCP. We anticipate that Spaces will take over the spec, and that Groups will never make it into an official spec document.
