### ISSUE TITLE
Groups as Rooms

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1215]
Documentation: https://docs.google.com/document/d/1ZnAuA_zti-K2-RnheXII1F1-oyVziT4tJffdw1-SHrE/edit#
Author: @ara4n 
Date: 17/10/2017

**Comment by Half-Shot** [comment]
This probably needs tidying up so it looks more like a proposal document and less like a set of notes.

**Comment by ara4n** [comment]
has been replaced by a more formal proposal at #1772
