### ISSUE TITLE
@room notification proposal

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1216]
Documentation: https://docs.google.com/document/d/1qRdlg94cr9YXxPCwhW4HgI2oDrqQOUKX5HptZFBGf6o/edit
Author: @dbkr 
Date: 23/10/2017
PRs: #1176

**Comment by richvdh** [comment]
oh wait, #1176 isn't really the same as this

**Comment by richvdh** [comment]
dup #1033
