### ISSUE TITLE
Improving Presence

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1221]
Documentation: https://docs.google.com/document/d/1sKaM9J5oorEeReYwOBmcgED6XnX2PdCYcx0Pp0gFnqM/edit#heading=h.geptormxf2k8
Author: @ara4n 
Date: 26/12/2017

**Comment by eras** [comment]
I was discussing (monologue really) about this topic on the Matrix HQ room today and the following ideas came to my mind:

- Presence should be opt-in, not opt-out. Not everyone wishes to tell everyone this information.
- Presence should be opt-in per room; those that might choose to tell presence might choose to be picky about it (ie. I would probably only tell my friends, not all the 1000 people on Matrix HQ). This data could be stored in a user account setting so it wouldn't affect the presence protocol per sē, only its semantics.
- There was also an idea about disabling presence on big rooms, but I guess the previous would work out automatically; but if not, there could also be a per-room opt-out or opt-in for receiving presence data
- The main benefit - besides privacy - would be greatly reduced load on the server?

**Comment by richvdh** [comment]
Seems to be a dup of #1100
