### ISSUE TITLE
Replies - next steps

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1224]
Documentation: https://docs.google.com/document/d/1FZsvodn2C0iKJDtn-8y8IPwOa96ixoJejK3gMLVOXHM/edit
Author: @t3chguy
Date: 03/02/2018

@t3chguy to update status (use label)

**Comment by ara4n** [comment]
obsoleted by https://github.com/matrix-org/matrix-doc/issues/1234
