### ISSUE TITLE
State Reset mitigation proposal

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1226]
Documentation: https://docs.google.com/document/d/1L2cr8djdpOFXJgqGTf3gUrk-YGBYf--rP8Nw6mYYAu8/edit#heading=h.vazyvubo3b4z
Author: @richvdh 
Date: 20/02/2018

**Comment by richvdh** [comment]
I think we're mothballing this in favour of some upcoming work on the state res algorithm.
