### ISSUE TITLE
Handling Consent for Privacy Policy

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1231]
Documentation: https://docs.google.com/document/d/1-Q_Z9dD3VTfsNYtK_WTzyTQR4HQWsntt-_DwgoW02ZU/edit#heading=h.cvd8uae3gmto
Author: @neilisfragile 
Date: 02/05/2018

**Comment by richvdh** [comment]
This MSC isn't very clear about what exactly was agreed; it never really made it into a finished document.

[consent tracking](https://github.com/matrix-org/synapse/blob/e206b2c9ace8a202bf47ec419581e19f0baa39fb/docs/consent_tracking.md) was implemented in synapse in a way that mostly didn't affect clients (apart from #1252) so didn't need a full MSC process. Accordingly, I'm going to declare this obsolete.

[MSC1692](https://github.com/matrix-org/matrix-doc/pull/1692) is an extension which extends support into the User-Interactive Auth and login APIs.
