### ISSUE TITLE
Media limits API

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1232]
Documentation: https://docs.google.com/document/d/1fI4ZqQcyAyBEPMtS1MCZWpN84kEPdm9SDw6SVZsJvYY/edit
Author: @Half-Shot
Date: 04/05/2018
PRs: #1189

**Comment by Half-Shot** [comment]
(This has been ready for a while now, can it get reviewed?)

**Comment by benparsons** [comment]
@Half-Shot who do you think should be reviewing it - can you include them in the thread?

**Comment by Half-Shot** [comment]
Anyone from the Riot side would be fine, I'll pick @lukebarnard1 :grin:

**Comment by benparsons** [comment]
Luke, will you be able to help with this?

**Comment by ara4n** [comment]
RIGHT - we've picked this up as part of a clear the MSC backlog mission; sorry for the delay.

Having spoken it through, there are some conclusions on the 'Shortcomings' section, and with these now incorporated, it lgtm.  @dbkr, @turt2live (and anyone else) can you give an upvote for an lgtm?
