### ISSUE TITLE
Voice messages

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1238]
Documentation: TBD
Author: @aviraldg
Date: 13/04/2016
PRs: #310

**Comment by remram44** [comment]
I'd be wary of referring to this as "push-to-talk", which usually refers to real-time streaming audio (activated by a button) rather than recorded audio messages played asynchronously.

**Comment by turt2live** [comment]
(renamed this and the PR to be "voice messages" to avoid confusion with what we've been calling PTT)

**Comment by Half-Shot** [comment]
@turt2live #310 was closed, should we close this? (And I think the author has vanished anyway?)

**Comment by turt2live** [comment]
I guess this is obsoleted by https://github.com/matrix-org/matrix-doc/pull/2516

It was previously abandoned, which we don't close issues for - it just never got the right labels.
