### ISSUE TITLE
Provide spec proposal templates

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1241]
@mujx pointed out that having a consistent starting point for spec proposals would be useful.  @benparsons perhaps you can find some commonality out of the ones we have atm (erik's Groups one might be a good bet?) to provide a potential starting point?

**Comment by benparsons** [comment]
I have noted:

* Problem/Background
* Proposal
* Tradeoffs
* Issues
* Conclusion

These could all be optional.

**Comment by turt2live** [comment]
The template mentioned above seems to be linked in the proposals introduction. Is there something else people had in mind before closing this?

**Comment by benparsons** [comment]
I think that was it - can close.
