### ISSUE TITLE
/rooms/{roomId}/members is not specified as requiring authentication

### ISSUE THREAD

**Issue by florianjacob** [matrix-org/matrix-doc#1245]
This currently makes the endpoint incompatible between synapse and ruma-client.

synapse enforces authentication [here](https://github.com/matrix-org/synapse/blob/2c3e995f38a411647ca08ae2959add577041ca97/synapse/rest/client/v1/room.py#L380) and will return a status code `403` for every request without an access token.

ruma-client-api conforms to what the spec says here and [only sends an access token if the endpoint is marked as requiring authentication](https://github.com/ruma/ruma-client-api/blob/master/src/r0/sync.rs#L116), getting a `403` from synapse every time.

This seems to be a simple omission, as the behaviour depends on which user calls the endpoint, and therefore requires authentication:

> A list of members of the room. If you are joined to the room then this will be the current members of the room. If you have left the room then this will be the members of the room when you left.

Additionally, the status code 403 "You aren't a member of the room and weren't previously a member of the room." *is* actually specified.

Also, the very similar `/rooms/{room_id}/joined_members` requires authentication as well.

Possible solution if this is just an omission: #1244

**Comment by richvdh** [comment]
fixed by #1244
