### ISSUE TITLE
 static private rooms that always stay private

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-doc#1246]
At the moment, a private room (one that is invite-only) can always be made public later.

To increase the confidentiality, there should be a way to mark a room's state as static, ie. private with no way to change to public.

I thought this is most important especially in rooms between only 2 users where they speak about confidential things.

Additinaly, if this is implemented, maybe there should then be a new extra option like "invite-only-if-all-room-members-agree"

**Comment by richvdh** [comment]
I think this is covered by #1255
