### ISSUE TITLE
Document body param `third_party_instance_id` on POST /publicRooms

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1248]
We use it to fetch a single ASes room list, but it's not documented anywhere.

**Comment by Half-Shot** [comment]
be good if this could be tagged?

**Comment by Half-Shot** [comment]
:)

**Comment by richvdh** [comment]
apparently it doesn't actually do anything in synapse, in that it's impossible to tag rooms in a way that this would give any result:

> It's basically used to filter against the `appservice_room_list` table and I couldn't find any code that populates that table

If we ever fix it, I would love it if it could be renamed `thirdparty_*` for consistence with ALL THE OTHER thirdparty stuff.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-doc/issues/869
