### ISSUE TITLE
Correct the json object definition of an olm encrypted event

### ISSUE THREAD

**Issue by mujx** [matrix-org/matrix-doc#1251]
The e2ee guide currently states that the content of an event encrypted with olm should have the following structure (https://matrix.org/docs/guides/e2e_implementation.html#encrypting-an-event-with-olm)
```
{
  "algorithm": "m.olm.v1.curve25519-aes-sha2",
  "sender_key": "<our curve25519 identity key>",
  "ciphertext": "<encrypted payload>"
}
```
which is inconsistent with the previous paragraphs.

The ciphertext should be an object mapping from the Curve25519 identity key for the recipient device,
as it is already explained in https://matrix.org/docs/guides/e2e_implementation.html#m-olm-v1-curve25519-aes-sha2.
```
{
  "content": {
    "algorithm": "m.olm.v1.curve25519-aes-sha2",
    "ciphertext": {
      "ljb1QTjaFixBF9Z0v+vkqDFUeez8Y9AqV9QQ4HPc6G8": {
        "body": "Awog2xyRyO+VNbg2BfF7SFgzqWmQG ... K3Ps",
        "type": 0
      }
    },
    "sender_key": "a3tA5yqMRFHnqJ92AgStNgmJIQSgdcGzPPyb2Ec/snM"
  },
  "sender": "@bob:localhost",
  "type": "m.room.encrypted"
}
```

**Comment by richvdh** [comment]
the e2ee guide is in https://github.com/matrix-org/matrix.org. Would you mind raising this there instead?
