### ISSUE TITLE
spec M_CANNOT_LEAVE_SERVER_NOTICE_ROOM error

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1254]
cf https://github.com/matrix-org/synapse/commit/08bfc48abf8c138b540ede6c816338c044130dec

**Comment by richvdh** [comment]
the error code is now misleadingly named, because it is only used to stop you rejecting invites to the server notice room :(

**Comment by Half-Shot** [comment]
Surely this could just be M_FORCE_JOINED rather than specific to the SNR?

**Comment by turt2live** [comment]
just dropping by to say someone (me) went as far as documenting that the errors needed speccing, but didn't do so:
![image](https://user-images.githubusercontent.com/1190097/58387721-ca91f900-7fd0-11e9-82ca-fd3208b3c03c.png)

:|
