### ISSUE TITLE
Olm is not explained in the spec

### ISSUE THREAD

**Issue by jimmycuadra** [matrix-org/matrix-doc#1258]
In r0.3.0 of the client-server spec, section 11.10.1.3 (Device keys) ends with the sentence:

> For Olm version 1, each device requires a single Curve25519 identity key, and a number of signed Curve25519 one-time keys.

This is the first time in the spec that Olm is mentioned, and it is never explained.

**Comment by richvdh** [comment]
links are always helpful. In this case we are referring to https://matrix.org/docs/spec/client_server/r0.3.0.html#device-keys.

**Comment by richvdh** [comment]
this is basically #501. Note that https://matrix.org/speculator/spec/drafts%2Fe2e/client_server/unstable.html#messaging-algorithms has some draft info about olm.

**Comment by richvdh** [comment]
closing as a dup as #501. feel free to reopen if you disagree
