### ISSUE TITLE
something is pushing out the spec to be thousands of pixels wide

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1268]
https://matrix.org/docs/spec/client_server/r0.3.0.html

**Comment by turt2live** [comment]
There's quite a few long tables. If I'm not mistaken, they used to wrap.

**Comment by turt2live** [comment]
Found the problem. In `site_overrides.css` there's this:
```
div#tables-of-tracked-proposals td:nth-of-type(2), td:nth-of-type(3) {
    white-space: nowrap;
}
```

The second condition, `td:nth-of-type(3)` isn't scoped by the proposals table. Conveniently, the third column in the spec tables is the description, leading to insane column lengths.

As far as I can tell, the `site_overrides.css` is ignored in matrix-org/matrix.org, so paging @benparsons to fix :)

**Comment by benparsons** [comment]
@turt2live well spotted. Fixed and deployed, but will take a short time to decache.
