### ISSUE TITLE
Proposal Add /_matrix/media/v1/resolve_url to Client-Server API: download and preview urls in the clients despite CORS

### ISSUE THREAD

**Issue by oivoodoo** [matrix-org/matrix-doc#1270]
Hi everyone!

Related issue is https://github.com/vector-im/riot-web/issues/3015

Documentation: https://docs.google.com/document/d/1bbX1yxNETmMa-AxBGjIpb4lNoTuc3vjGXmbZWrNBlzM/edit?usp=sharing

Thank you!

**Comment by turt2live** [comment]
Related: https://github.com/matrix-org/matrix-doc/issues/608

**Comment by uhoreg** [comment]
(clarified title a bit -- in particular, this is not Synapse-specific, but would apply to any Matrix Homeserver.)

**Comment by oivoodoo** [comment]
@uhoreg thank you, now it looks better. what do you think about the new endpoint? this concept has already implemented in my branches and ready to give a try in case if spec looks good for everyone.

**Comment by oivoodoo** [comment]
Hi @richvdh. Could you review the spec file as well? thank you!

**Comment by uhoreg** [comment]
I've re-written the Google doc as a markdown doc at #2370

**Comment by turt2live** [comment]
Flagging this one as obsolete to continue over at that issue then,
