### ISSUE TITLE
Document Thirdparty AS Endpoints

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1271]
Which you can find in: https://github.com/matrix-org/matrix-appservice-bridge/blob/8a0a704e7de75155843f1548d25c72b4f48aae11/lib/bridge.js#L315

Oh and there should also be a whole bunch of equivalent ``/thirdparty`` endpoints for the HS, which will be found in the bowels of synapse.

These should all be documented in the AS spec.

**Comment by turt2live** [comment]
I believe this is completed: https://matrix.org/docs/spec/application_service/unstable.html#get-matrix-app-unstable-thirdparty-protocol-protocol
