### ISSUE TITLE
Document Appservice Directories

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1272]
Until today I didn't know this was a thing, but apparently Appservices can have their own curated directories in the form of https://github.com/matrix-org/synapse/blob/f009df23ec711e943d958bb0a0e3185d42d7cc79/synapse/rest/client/v1/directory.py#L220

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-doc/issues/869
