### ISSUE TITLE
Include proposals.py generator in CI

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1277]
Only need to leave a line in https://github.com/matrix-org/matrix-doc/blob/master/scripts/generate-matrix-org-assets, but I'd like to understand how the dependencies play with existing Jenkins setup.

**Comment by michaelkaye** [comment]
So I think all we need to do is insert a call to the proposals script before gendocs runs, and remove ../specifications/proposals.rst from version control (and exclude in .gitignore) so we get a clean git repo.

As you say, dependency wise, i think we need `m2r` and `requests` to be installed before we run that python script. 

The pip packages that provide these should be added (at appropriate versions) to https://github.com/matrix-org/matrix-doc/blob/master/scripts/requirements.txt

This will then be used by https://github.com/matrix-org/matrix-doc/blob/master/scripts/test-and-build.sh#L9 to install the dependencies before running jenkins.

If you make a PR for that then it should work, and a test build be performed and I think the travis build will complain if there's a problem before we merge to master and jenkins actually does the build and deploy.

**Comment by michaelkaye** [comment]
(LMK if you run into problems having done that)

**Comment by benparsons** [comment]
@michaelkaye awesome explanation, thanks!

**Comment by benparsons** [comment]
@michaelkaye why would we want to remove ../specifications/proposals.rst ? The script will overwrite this file with new content, but it would be valuable to have as a fallback. Is there a benefit to removing it?

**Comment by benparsons** [comment]
I have a PR out for this which does not include removing the base version of proposals.rst: #1282

**Comment by michaelkaye** [comment]
> @michaelkaye why would we want to remove ../specifications/proposals.rst ? The script will overwrite this file with new content, but it would be valuable to have as a fallback. Is there a benefit to removing it?

If the build process is generating it on build, then having an identically named file that is out of date, always replaced and never deployed seems confusing to me. If the build process fails then we will get a missing file and should fix the build process. If it fails and there's a file there anyway then we won't get a missing file - it'll just be out of date.

We'll always have it as a fallback in the git history - we just don't need it in the currently in use branch.

**Comment by benparsons** [comment]
@michaelkaye ok, understood. I'll update the PR to remove the base file.

**Comment by turt2live** [comment]
@benparsons if I'm not mistaken this issue is completed. Is there something I'm missing or can this be closed?

**Comment by benparsons** [comment]
You are not mistaken.
