### ISSUE TITLE
Allow appservices to log in their users

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1285]
Currently registering a new appservice user gets you an access token for that user, however that's the last time you'll see that token. If the appservice uses that token and it gets lost, the only way to recover it is to do some database queries. The appservice cannot re-register the user (as the user ID is already taken) and it cannot login (currently).

An extension to the login would potentially be to allow appservices to log in with a request very similar to that of registering:

**Registration (current)**:
```
POST /_matrix/client/r0/register?access_token=your_as_token
{
  "username": "_namespaced_user",
  "type": "m.login.application_service"
}
```

**Proposed login request**:
```
POST /_matrix/client/r0/login?access_token=your_as_token
{
  "username": "_namespaced_user",
  "type": "m.login.application_service"
}
```

**Comment by Half-Shot** [comment]
I'm slightly confused? Why do you need an access token for an AS user?

**Comment by turt2live** [comment]
The use case I have is for go-neb management in Dimension. Other use cases could be managed accounts (through an appservice) or similar dynamic bots to go-neb. It'd also help with a Vault integration for matrix.

**Comment by maxidor** [comment]
@turt2live as far as I can tell, nothing in the spec stops you to register an AS user with a password or to login with it?

**Comment by Half-Shot** [comment]
>The use case I have is for go-neb management in Dimension. Other use cases could be managed accounts (through an appservice) or similar dynamic bots to go-neb. It'd also help with a Vault integration for matrix.

Seems fair, so the proposal is to have a token that can only act upon that account rather than using the global AS token. Cool :)

**Comment by turt2live** [comment]
@maxidor The whole point of bypassing the registration process is to not have to manage passwords. See also: https://matrix.org/docs/spec/application_service/unstable.html#server-admin-style-permissions

**Comment by turt2live** [comment]
@Half-Shot yup - simple bots (or magic ones like go-neb) don't have a way to set the `user_id` in requests, which is ideal imho. Being able to say "this is your token" and completely hide the fact that it's an AS user is the goal.

**Comment by maxidor** [comment]
I'm most likely missing something here. Your example in OP uses the AS token, so why do you need to *login* to get an access token if you already have the AS one?

**Comment by turt2live** [comment]
Because the account which you're logging in for may be an application or user which is not able to send the `user_id` as part of all of their requests. It would also prevent the application/user from using a token which has super-user access over the namespace.

The full request process would be:
* `>> POST /_matrix/client/r0/login?access_token=appservice_access_token`
* `<< {"access_token": "not_the_appservice_access_token"}`
* (client/other app) `>> GET /_matrix/client/r0/account/whoami?access_token=not_the_appservice_access_token`

**Comment by maxidor** [comment]
login uses interactive auth, so it's up to the implementation to offer it. I don't see anything in the spec that forbids it?

**Comment by turt2live** [comment]
... that's why I'd like to make it a spec

**Comment by melochale** [comment]
we can have this feature? we really need it, our case we use matrix as a micro-service, so we mange the user account/password internally, but sometimes the password my get lost on vault management(ttl), so now we cannot login, need to have a way to reset the password or login to get token to reset it.

**Comment by Half-Shot** [comment]
Nobody has linked it yet, but https://github.com/matrix-org/matrix-doc/pull/2778 is the MSC that solves this. @melochale Synapse already implements that MSC as an unstable feature that you can use, and the MSC will hopefully be nearing a merge as it's approaching FCP.

**Comment by uhoreg** [comment]
MSC2778 is now merged into the spec.
