### ISSUE TITLE
Leave rooms with a reason?

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1295]
Just wondered why there is no reason field for leaving a room, but there is for a kick. It would have some use for bots who wish to declare why they are leaving e.g.  "Been invited to a Encrypted room, but leaving because we don't support that".

Given both kicking and leaving result in the same member state (you can even kick yourself with a reason in Riot), it seems a little odd that we don't have an option for that via /leave.

**Comment by jcgruenhage** [comment]
Also, the event that's created when kicking someone doesn't conform to the spec, because https://matrix.org/docs/spec/client_server/r0.3.0.html#m-room-member doesn't contain reason.

**Comment by anoadragon453** [comment]
> Also, the event that's created when kicking someone doesn't conform to the spec, because https://matrix.org/docs/spec/client_server/r0.3.0.html#m-room-member doesn't contain reason.



Heads up that this is now supported in the latest version of the spec: https://github.com/matrix-org/matrix-doc/blob/6274a66ae5fa140c0f08992a4244e5b066194150/api/client-server/kicking.yaml#L64-L68
