### ISSUE TITLE
AppServices: Document client-server requests omitting user_id param

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1296]
The majority of application services and Synapse itself all allow for the behavior of omitting the `user_id` parameter when calling the Client-Server API with an `access_token`. This assumes that the application service is acting as its main user, or what it specifies as the `sender_localpart` user in its registration config.

This behavior is currently not documented anywhere in the spec, and would be useful for homeservers implementing the AS API to know when they get these types of requests from application services :)

**Comment by non-Jedi** [comment]
For what it's worth, this was the most confusing part when I was trying to implement an application service. The "main AS user" wasn't even mentioned at that time in the AS doc.
