### ISSUE TITLE
spec @mxid state_key restriction on state events

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1305]
only `@user:domain` is allowed to send state events with a state_key of `@user:domain`. https://matrix.org/docs/spec/server_server/unstable.html#rules appears not to mention this.

**Comment by uhoreg** [comment]
Which event type(s) does this apply to?

**Comment by t3chguy** [comment]
is that the case though? When I kick someone I send a state event with `state_key` of the MXID that I kicked?

**Comment by turt2live** [comment]
Having brought this up alongside the conflicting issue #571, some enlightenment has occurred: 

* The state key restriction applies to non-membership events (as membership events are handled differently)
* This is a thing: https://github.com/matrix-org/synapse/blob/cd32c19a604549b4518d748c07149d140bc9e063/synapse/event_auth.py#L407-L414
* This restriction is in place for some potential future improvements to membership, and possibly user-defined state data in a room that others cannot touch, although this is still in the idea phase.

**Comment by richvdh** [comment]
don't think this got fixed yet; it will be done by #1591

**Comment by uhoreg** [comment]
Fixed by #1591
