### ISSUE TITLE
Proposal for a media information API

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1310]
Documentation: https://docs.google.com/document/d/1yNnOIFuYYu33YVVhOMPZoNQ8YBGcSfSiO1bTe1NwPHI/edit?usp=sharing
Resolves: #703

**Comment by anoadragon453** [comment]
I was working on a server-side feature that this would've made much easier. Mind if I markdownify this and turn it into an MSC?

**Comment by turt2live** [comment]
Oh please do. Note that it's partially implemented by matrix-media-repo already as an unstable endpoint.

**Comment by anoadragon453** [comment]
https://github.com/matrix-org/matrix-doc/pull/2380
