### ISSUE TITLE
State that application services can register users without needing a login type

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1312]
Currently the AS spec says that a registration type of `m.login.application_service` is required when registering a fake user as an application service. Turns out that no AS does this, and Synapse just assumes that supplying an AS token in the request = registering a fake user.

We should change things so bot authors don't get confused when their fake user registration doesn't work.

**Comment by turt2live** [comment]
I'm more in favor of fixing all the bridges to be honest.

**Comment by Half-Shot** [comment]
I'm also in favor of fixing it to use the type, but we should spec what actually exists before changing it.

**Comment by turt2live** [comment]
This is one of those cases I disagree on soecing it at all.

It is a very clear synapse bug to not validate and it's the bridge's fault for relying on that. If anything, synapse should be patched with a warning in the changelog.

**Comment by Half-Shot** [comment]
I'd actually prefer to spec/keep the "better" way and allow synapse to support both, which I can't believe would be hard to achieve.

**Comment by anoadragon453** [comment]
And Dendrite will just flat out block incorrect behavior (with a helpful error message ofc :)

**Comment by turt2live** [comment]
Synapse supporting both is fine, although I still strongly disagree with this being in the spec.

**Comment by anoadragon453** [comment]
@turt2live I believe the consensus is to not change the spec, keep the current behavior in Synapse (and warn in the logs), and have Dendrite deny the more lax request, but [provide a helpful warning](https://github.com/matrix-org/dendrite/issues/512) when you try to do it the non-spec way.

**Comment by turt2live** [comment]
Sounds good to me :)

Is it safe to have this issue closed? (even though having 475 open issues pleases my OCD)

**Comment by anoadragon453** [comment]
Yes I think so.
