### ISSUE TITLE
Proposal to have the appservice registration `type` be optional

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1316]
Documentation: https://docs.google.com/document/d/1ng01UlGynBfktSepGHtsCArsE5ZM6mOZzZn-ULtTZEM/edit?usp=sharing
Related/resolves: https://github.com/matrix-org/matrix-doc/issues/1312

**Comment by Half-Shot** [comment]
We've since made synapse and dendrite (and all the matrix-org, maunium and other bridges) support `type`, so I think there is very little point in driving the other way now. Can we close this one @turt2live ?
