### ISSUE TITLE
Proposal for Open Governance of Matrix.org

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1318]
Documentation: https://docs.google.com/document/d/1vASIt2v0UwKnUKHNEjA_P3SFCM0kcIUl1LQyM--ax04/edit#

**Comment by ara4n** [comment]
mental note to spell out guidelines for when features should land in the spec v. via integration/widget etc.

**Comment by turt2live** [comment]
Keywords: foundation

**Comment by ara4n** [comment]
This has been converted to markdown at #1779, and significantly rewritten to incorporate the review feedback for #1318 and the sessions with the Foundation lawyers in Nov 2018 to define the relationship between the legal Foundation entity and the Spec Core Team.
