### ISSUE TITLE
AS traffic rate-limiting

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1323]
Documentation: https://docs.google.com/document/d/14ygfhAMUrAa04YMHHl2P8_mxV3H2ntNq_-crmZizED0/edit?usp=sharing
Date: 2018-06-20
Author: @anoadragon453

**Comment by turt2live** [comment]
Can the protocol stuff be moved to it's own proposal? I feel it needs a lot more information, and it would be a shame to block simpler functionality on something more complicated :(

**Comment by anoadragon453** [comment]
@turt2live done https://github.com/matrix-org/matrix-doc/issues/1324

**Comment by Half-Shot** [comment]
This appears to be documented in #1262, can it be closed?
