### ISSUE TITLE
/createRoom has no descriptions for what a state event is

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1327]
![image](https://user-images.githubusercontent.com/1190097/41697566-97a7bcce-74d6-11e8-869e-5de570c0f572.png)

**Comment by Half-Shot** [comment]
That's sad :(

**Comment by turt2live** [comment]
It's not the same type given you're not able to give an event id, etc.

**Comment by Half-Shot** [comment]
Pardon, double checked to make sure and yeah it's just the 3 keys.
Synapse uses them essentially the same way as: https://matrix.org/docs/spec/client_server/r0.3.0.html#put-matrix-client-r0-rooms-roomid-state-eventtype-statekey obviously without roomid and content being in a different place.
