### ISSUE TITLE
Define what clobber means

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1328]
Some people are unclear. It should be defined or replaced with a better word throughout the spec

**Comment by Half-Shot** [comment]
We could probably replace the word with replace.

**Comment by joepie91** [comment]
Just ran into this in [this part](https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-createroom) of the spec.

There, the text:

> The server will clobber the following keys: creator, room_version.

... could be changed into:

> The server will override the following keys: creator, room_version.

(Assuming that my understanding of the phrase is correct, and it means to say that the client-specified value will be ignored, and a server-determined value will always be used for those keys.)

I'm not sure whether this 'override' terminology will work elsewhere in the spec, or whether it needs to be clarified with clauses such as "if it is specified".

I do think that 'override' is a clearer term to use here than 'replace', as it explicitly denotes that the replacement is forcible in nature. It's also a term that is commonly understood in every-day language use; though less so than 'replace', but I'm not sure that that difference matters given the target audience.

**Comment by anoadragon453** [comment]
I'm not entirely sure. `overwrite` is clearer than `override` to me, but `replace` sounds the simplest and clearest of the lot.

This is purely my opinion though.
