### ISSUE TITLE
proposals script explodes if PR field doesn't match the expected format

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1332]
somebody opened a proposal doc with the full link to the PR rather than just the `#...` abbreviation.  The proposal script died and caused CI errors on other PRs.

cc @benparsons

PRs: https://github.com/matrix-org/matrix-doc/pulls/1340

**Comment by benparsons** [comment]
@richvdh: could you confirm #1340 to fix this

**Comment by benparsons** [comment]
(top comments edits for testing only)

**Comment by benparsons** [comment]
fixed by #1340
