### ISSUE TITLE
Spec query parameters of Protocol URLs 

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1343]
https://matrix.org/docs/spec/server_server/unstable.html#protocol-urls

`/state/{roomID}/?event_id={event_id}` is a valid and necessary endpoint however it is nowhere mentioned in the spec and thus requires reverse-engineering Synapse to discover.

This is just one example. There may be many other query parameters that are unaccounted for in this portion of the spec.

**Comment by turt2live** [comment]
Having gone through the entire server-server API, at least one of the PRs fixes this. I'm not sure if it is open still or has been merged. Closing this with the anticipation that this is fixed.

If it's still an issue come September, please reopen.
