### ISSUE TITLE
Improve documentation of how third party invites work

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1366]
This is a complicated dance possibly involving multiple HSes and multiple ISes. https://matrix.org/docs/spec/client_server/unstable.html#third-party-invites has some documentation but fails to document the full exchange_third_party_invite dance.

**Comment by richvdh** [comment]
Some of the implementation of this seems to have landed in https://github.com/matrix-org/synapse/commit/2cebe535 without any documentation as to how it is supposed to work.

Dave has started some notes at https://docs.google.com/document/d/1WR9fn5ar8WiWrYTFV6SSm0oN1CF3GsjQnT2vU3nkL6Y, which we can try to build from.

Sequence diagrams would be helpful.

**Comment by turt2live** [comment]
(doc not public)

**Comment by richvdh** [comment]
> (doc not public)

fixed I hope

**Comment by turt2live** [comment]
Dendrite PR: https://github.com/matrix-org/dendrite/pull/224
