### ISSUE TITLE
spec is wrong about what is allowed in a server_name

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1368]
In particular, https://matrix.org/docs/spec/appendices.html#server-name says the host part is as defined by RFC 3986, which allows %-encoding to be used in host names.

In practice, we do not allow this. What we actually allow are: IPv4 literal; bracketed IPv6 literal; hostname consisting solely of `[0-9a-zA-Z.-]`.

----

Copy/pasted on behalf of another user

**Comment by maxidor** [comment]
> In practice, we do not allow this. What we actually allow are: IPv4 literal; bracketed IPv6 literal; hostname consisting solely of [0-9a-zA-Z.-].

What is **we** here?

**Comment by turt2live** [comment]
"we" in this case is the ecosystem, given this is a spec issue.

**Comment by maxidor** [comment]
I disagree this can be considered as clarification.

The description of the label is "An area where the spec could do with being more explicit", but the spec is very explicit that `host` is to follow the RFC. There are also implementations in the wild that accept it, being spec compliant.

If **we** = synapse, then it seems like synapse is just not compliant with the spec. If `%` should indeed be denied, then that's a spec change with keeping in mind that it could (and most likely will) break production setups.

**Comment by ara4n** [comment]
'we' are developers & admins of synapse, the closest thing we have to a reference implementation of Matrix.  Please stop being so obtuse and pedantic.

**Comment by ara4n** [comment]
If anyone has real-world examples of people putting % in their server_names, then please show them.  Otherwise fixing a bug in the spec (where we were sloppy on the definition of a server_name) takes priority, and synapse's behaviour should be considered correct in this instance.

% URI sequences in server names feel like particularly undesirable misfeature, given it would cause an escaping explosion in all the HTTP endpoints, which would be way more pain to get right than it solves.

**Comment by ara4n** [comment]
Just to be clear on this specific issue (from my pov):
 * We were sloppy and made a mistake on the spec by saying that hostnames in MXIDs are allowed to be anything from RFC 3986.
 * This is very undesirable behaviour, as it makes ACLing MXIDs needlessly hard (you can't just match @ara4n:bar.com; if @ara4n:b%61r.com refers to the same server), and it would cause a ridiculous ugly explosion of URI encoding in the API and related escaping/unescaping bugs: 
 * We're not aware of a single mxid in existence which uses this misfeature; the matrix.org HS for instance has never seen such an event.
 * Meanwhile, the closest thing we have to a reference implementation (i.e. synapse) doesn't honour this (mis)behaviour.
 * Therefore we're making the most of the SS API being pre-release and fixing it as a bug in the spec, which it is.
 * If we debate each and every trivial edge case like this to death, it's going to just delay getting all of Matrix released across all APIs.  We're not going to look kindly on attempts to slow down progress on the spec (especially from folks who now have a vested interest in Matrix progressing slowly).

**Comment by maxidor** [comment]
> We're not going to look kindly on attempts to slow down progress on the spec (especially from folks who now have a vested interest in Matrix progressing slowly).

This was labeled as "clarification", not as "spec-bug" or "spec change". I really don't know what is your point, as I never put in question the technical validity of the change itself.

Thank you for clarifiying it is indeed a spec change, or possibly a spec bug, and not a point of clarification.
