### ISSUE TITLE
Proposal for Rich Bridging

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1410]
Documentation: https://docs.google.com/document/d/1uBxekDnl9WBPWA989W1_QeOWA560TZI27g-Xju9Uk3w/edit#
Author: @Half-Shot

**Comment by turt2live** [comment]
We really need this. I'm currently staring at a log as thousands of Telegram users are invited by ChanServ into a room, which the Telegram bridge says "you can't do that" and then leaves. Instead, the IRC bridge could see that those users are bridged users and not bother inviting them, or the Telegram bridge could happily ignore the rooms - both of which reduce server load.

**Comment by Half-Shot** [comment]
I'm considering splitting out the double bridging portion to it's own regular event, that then allows other ASes to interject and say "NO, STOP THAT". It's a little racey but better n nothing.

**Comment by Half-Shot** [comment]
This is superseded by #2346
