### ISSUE TITLE
Support rejecting invites with a reason

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1416]
Proposal: Tell clients that they can reject an invite with an optional `reason` on the `m.room.member`. Copying from kicks/bans.

Use case: A user may wish to reject an invite to say "no, I don't want to talk to you". The homeserver may also be able to enhance the ignored users stuff by auto-rejecting with "This user has ignored you" or something. Another use case would be potentially a bridge/appservice/bot refusing to participate in a room due to some condition.

**Comment by erikjohnston** [comment]
[MSC2367](https://github.com/matrix-org/matrix-doc/pull/23670) allows adding reasons to rejecting invites, amongst other things.

**Comment by aaronraimist** [comment]
> The homeserver may also be able to enhance the ignored users stuff by auto-rejecting with "This user has ignored you" or something.

I don't want a user to be able to tell that I ignored them so hopefully this would be optional

**Comment by turt2live** [comment]
I would hope it is optional.

**Comment by Half-Shot** [comment]
Can this be closed now that MSC2367 is merged?
