### ISSUE TITLE
The spec'ed algorithm for choosing of auth events is subtly wrong

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-doc#1430]
The actual set picked for an events is: https://github.com/matrix-org/synapse/blob/2c33b55738d54186d7655972a6707336b2168534/synapse/event_auth.py#L674-L706

**Comment by turt2live** [comment]
updated link: https://github.com/matrix-org/synapse/blob/33b60c01b5e60dc38b02b6f0fd018be2d2d07cf7/synapse/api/auth.py#L555-L619

**Comment by uhoreg** [comment]
fixed by #1593
