### ISSUE TITLE
Replace the speculator with Circle CI builds

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1432]
This is more of a tracking issue for finally killing off the speculator. Here's what needs to be done:

* [ ] Bot from @Cadair (work in progress)
* [x] Get swagger working with Circle CI (may need to just upgrade swagger)
* [ ] Replace/drop the diff support that the speculator offers (does anyone use this?)

This would 'fix' the following:
* https://github.com/matrix-org/matrix-doc/issues/1408
* https://github.com/matrix-org/matrix-doc/issues/1384
* Having to whitelist people manually

**Comment by richvdh** [comment]
I think this happened years ago.
