### ISSUE TITLE
Querying a non-existent user's full profile should have an error code of `M_NOT_FOUND`, not `M_UNKNOWN`

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1435]
The current synapse behaviour is to return `M_UNKNOWN`, therefore that will be landing in the spec. This should be changed to be `M_NOT_FOUND`.

Related: #1434

**Comment by richvdh** [comment]
> The current synapse behaviour is to return M_UNKNOWN, therefore that will be landing in the spec

must it? I find no value in speccing such a thing.

**Comment by turt2live** [comment]
moving to synapse as a bug
