### ISSUE TITLE
avatar notification issue 

### ISSUE THREAD

**Issue by vinay675** [matrix-org/matrix-doc#1460]
I want the notification should be changed from "your avatar has been changed" to "your profile picture has been changed" how I can do it

**Comment by turt2live** [comment]
This is more of a question for the client you're using. If that happens to be Riot, you'll need to modify the source code in `TextForEvent`. I suggest visiting [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) to ask your question.
