### ISSUE TITLE
The Local echo section seems to be outdated

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix-doc#1462]
The `Local echo` section now has the following paragraph that seems to predate `txnId`/`transactionId` introduction:

> Flickering cannot be fully avoided in the current client-server API. Two scenarios need to be considered:
> -    The client sends a message and the remote echo arrives on the event stream after the request to send the message completes.
> -    The client sends a message and the remote echo arrives on the event stream before the request to send the message completes.
> In the first scenario, the client will receive an event ID when the request to send the message completes. This ID can be used to identify the duplicate event when it arrives on the event stream. However, in the second scenario, the event arrives before the client has obtained an event ID. This makes it impossible to identify it as a duplicate event. This results in the client displaying the message twice for a fraction of a second before the the original request to send the message completes. Once it completes, the client can take remedial actions to remove the duplicate event by looking for duplicate event IDs. A future version of the client-server API will resolve this by attaching the transaction ID of the sending request to the event itself.

Should it be removed or rewritten to reflect the current status (whereas `transactionId` can be used as an echo identifier)?

**Comment by richvdh** [comment]
> Should it be removed or rewritten to reflect the current status (whereas transactionId can be used as an echo identifier)?

yes!
