### ISSUE TITLE
MSC Soft Logout

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-doc#1466]
Documentation: https://github.com/matrix-org/matrix-doc/pull/1467

**Comment by turt2live** [comment]
the implementation is tracked here: https://github.com/matrix-org/synapse/issues/4280

**Comment by turt2live** [comment]
riot-web has done an implementation at these places:
* https://github.com/matrix-org/matrix-react-sdk/pull/3177
* https://github.com/matrix-org/matrix-react-sdk/pull/3181
* https://github.com/matrix-org/matrix-react-sdk/pull/3182
* https://github.com/matrix-org/matrix-react-sdk/pull/3187
* https://github.com/matrix-org/matrix-react-sdk/pull/3188
* https://github.com/matrix-org/matrix-react-sdk/pull/3189
* https://github.com/matrix-org/matrix-react-sdk/pull/3190
* https://github.com/matrix-org/matrix-react-sdk/pull/3197

**Comment by richvdh** [comment]
synapse's (initial) implementation is at #5660, so I'm declaring this to be spec-missing.

**Comment by turt2live** [comment]
Spec PR (finally): https://github.com/matrix-org/matrix-doc/pull/2546

**Comment by turt2live** [comment]
Merged 🎉
