### ISSUE TITLE
Timestamp time zone?

### ISSUE THREAD

**Issue by alphapapa** [matrix-org/matrix-doc#1468]
I looked at every mention of "timestamp" in https://matrix.org/docs/spec/client_server/r0.3.0.html, and searched for mentions of "time zone" or "timezone", but I found no explanation of what time zone timestamps are in--the spec only says that they are "Timestamp in milliseconds on originating homeserver."  Some of the mentions of "timestamp" also say "Unix epoch," which may (or even should) imply UTC.  However, I think that the time zone should be made explicit in the spec.

**Comment by turt2live** [comment]
It is UTC, although yes: all mentions of it should say it's a unix epoch timestamp.

**Comment by richvdh** [comment]
unix timestamps don't have a timezone really - that's one of the nice things about them!

**Comment by alphapapa** [comment]
@richvdh Well, according to https://en.wikipedia.org/wiki/Unix_time:

> Unix time (also known as POSIX time[citation needed] or UNIX Epoch time) is a system for describing a point in time, defined as an approximation of the number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970.

The fact that they are (supposed to be) in UTC is important, because otherwise the time zone would have to be carried separately.  It also makes conversion to local time easier, because conforming implementations (e.g. Emacs's `format-time-string`) can automatically format timestamps into the local time zone for display.

**Comment by richvdh** [comment]
I think we're agreeing. The point is that the number of milliseconds since the epoch is independent of your timezone, because the epoch is at a defined point in time.
