### ISSUE TITLE
MSC Suggested Mentions

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1488]
PRs: #1489
Documentation: https://github.com/Half-Shot/matrix-doc/blob/hs/suggested-mentions/proposals/1488-suggested-mentions.md

**Comment by turt2live** [comment]
Updated the top comment for the format. Locking this as per tradition: please bring feedback about this proposal to the PR.

**Comment by turt2live** [comment]
Re-assigned the MSC number to the PR for clarity.
