### ISSUE TITLE
kill off intro.rst

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1500]

**Comment by turt2live** [comment]
this happened: https://github.com/matrix-org/matrix.org/commit/a6adb3cacbb49a3b901db11475034bdbb19e8ede

**Comment by richvdh** [comment]
it's still there, which is what I was complaining about: https://matrix.org/docs/spec/intro.html

**Comment by richvdh** [comment]
hrm. Can we just make it redirect to the index? I'm sure I'm not the only one with the old address cached in his browser.

**Comment by benparsons** [comment]
That works too! I'll make a JS redirect to preserve the in-page anchors
