### ISSUE TITLE
Room version upgrades

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1501]
PRs: #1502
Documentation: https://github.com/matrix-org/matrix-doc/blob/rav/room_upgrades/proposals/1501-room-version-upgrades.md

**Comment by richvdh** [comment]
(please take discussion to #1502)

**Comment by turt2live** [comment]
for links: this is heavily dependent on #1425

**Comment by richvdh** [comment]
spec pr is https://github.com/matrix-org/matrix-doc/pull/1791

**Comment by turt2live** [comment]
merged 🎉
