### ISSUE TITLE
Homeserver resource limiting error codes

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/matrix-doc#1504]
Documentation: https://docs.google.com/document/d/1_CgwkfLznU56fwLUFZXFnKivzVUPjjNsTO0DpCB9ncM/edit?usp=sharing

Encompasses #1470 (since M_SOFT_LIMIT_EXCEEDED covers M_MAU_LIMIT_EXCEEDED)

**Comment by turt2live** [comment]
How does `M_SOFT_LIMIT_EXCEEDED` cover `M_MAU_LIMIT_EXCEEDED`? Was the MAU error replaced?

It'd be nice to have the use case for having two different errors documented. A client doesn't appear to have instructions on what to do when a subset of users are disallowed versus all of them - it seems like it should only care if the requesting user is limited for some reason.

**Comment by neilisfragile** [comment]
How does M_SOFT_LIMIT_EXCEEDED cover M_MAU_LIMIT_EXCEEDED?  Was the MAU error replaced?Yes

It seems like it should only care if the requesting user is limited for some reason. I'd see it as more for the users benefit - they know *they* can't access the service but that the rest of the service is not down.

If it is not much use from a client perspective - then I'm not overly attached to it

**Comment by turt2live** [comment]
I think a single error code would be okay, given the user would (hopefully) be made aware of what's going on through other channels, such as the server notices room. Would love to hear from some client authors though, like @KitsuneRal and @mujx, as well as the wider client dev community.

**Comment by richvdh** [comment]
I think this has been implemented without ever having completed review, or indeed ever being written up into a coherent document :angry: 

I guess it needs speccing now

**Comment by turt2live** [comment]
Merged via https://github.com/matrix-org/matrix-doc/pull/1874
