### ISSUE TITLE
Table headings for request/response object schemas hard to find (was: Filter definitions are very cryptic in the CS API)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1508]
It's not clear what types are nested within which, or even which heading goes with which schema, or what things which filter subtypes actually apply to

**Comment by richvdh** [comment]
According to #1570 this now just needs CSS (at which point, see also https://github.com/matrix-org/matrix.org/issues/200 and https://github.com/matrix-org/matrix.org/issues/22)

**Comment by turt2live** [comment]
This is much clearer now - please reopen if there's disagreement.
