### ISSUE TITLE
Tag API is underdocumented

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix-doc#1565]
Namely, `Tags` and `Tag` structures are missing (`api/c-s/tags.yaml` and `event-schemas/schema/m.tag` use `type: object` for them). This causes ambiguity with regards to whether order should be a number or a string - all examples but one still use strings, even though the text mentions that `order` is a number.

**Comment by KitsuneRal** [comment]
WIP (almost complete): https://github.com/QMatrixClient/matrix-doc/tree/define-tag-structure

**Comment by richvdh** [comment]
#1639 could be seen as part of this larger issue
