### ISSUE TITLE
mark m.federate as obsoleted by server ACLs

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1578]
once some clients have UI support for server ACLs and we're confident they do what we need, we should kill off m.federate

**Comment by richvdh** [comment]
I'm really not sure they are the same

**Comment by Half-Shot** [comment]
Fwiw I am fine with client's removing support from ``m.federate`` from the UI but I agree they are not the same thing and there is definitely a good reason for keeping ``m.federate`` around.

**Comment by richvdh** [comment]
sounds like we're agreed this is not a thing we should do.
