### ISSUE TITLE
Better spec for room aliases

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1608]
PRs: #1607 
Documentation: https://github.com/matrix-org/matrix-doc/blob/human-id-rules/drafts/human-id-rules.rst

**Comment by richvdh** [comment]
This is ultimately intended to fix #668

**Comment by richvdh** [comment]
please take comments to #1598.

**Comment by turt2live** [comment]
I've rolled the number to 1607 given this is the only remaining example of weird process artifacts.
