### ISSUE TITLE
Grammar for client-provided secrets for 3pid validation

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1612]
The IS `/requestToken` and other APIs take a `client_secret` which has no formal specification for what is allowed here. Sydent accepts whatever fits into a `varchar(32)` in postgres/sqlite.

**Comment by richvdh** [comment]
I suggest we limit to the same grammar as is proposed for other opaque IDs in [MSC 1597](https://github.com/matrix-org/matrix-doc/blob/rav/proposals/id_grammar/proposals/1597-id-grammar.md#opaque-ids), and make sydent actually accept them up to 255 characters long.
