### ISSUE TITLE
All the specs are wrong about the changelog

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1623]
They all say "see master/changelogs/whatever.rst for the latest changes", but now that we use towncrier this doc is empty. Might need a comment at the top of each doc saying "please see matrix.org/the-spec/unstable.html" or something.

**Comment by aaronaxvig** [comment]
All five of the specs have good changelog sections, including the changes in the most recent version bump and a link to the full change history as compiled by TownCrier.

**Comment by turt2live** [comment]
They are still wrong, as mentioned in the issue description, the changelog file itself is missing information which makes the spec misleading here.

**Comment by aaronaxvig** [comment]
OK I am interested in working on this but I guess it needs to be described a little more explicitly.  In the [changelog section of the Client Server API](https://matrix.org/docs/spec/client_server/r0.6.0#changelog) for example, I see this:

> For the full historical changelog, see [https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst).

At that link I see details going back all of the way to r0.0.0.  Isn't that the "this doc" that was mentioned in the original issue description?  It isn't empty.

**Comment by turt2live** [comment]
This issue is one of historical accuracy. Previously we were not using towncrier so the changelog had the unstable details in it as well. However, when we switched to towncrier we didn't maintain the ability for the changelog file to have historical information.

Given this issue hasn't been touched in nearly 2 years, I'm lead to believe no one really cares though or just doesn't use that feature.

**Comment by aaronaxvig** [comment]
OK I think I am starting to understand.  The latest unstable changes are not very discoverable, and a link to https://matrix.org/docs/spec/client_server/unstable#changelog for each respective API would be useful.  Right?

**Comment by turt2live** [comment]
possibly. I'm not entirely convinced we need to do anything on this anymore.

**Comment by richvdh** [comment]
> They all say "see master/changelogs/whatever.rst for the latest changes",

They don't say this, and AFAICT they never had. They say: "For the full historical changelog, see https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst", which is accurate. 

I don't think we need to do anything here.
