### ISSUE TITLE
MSC: Replace event IDs with hashes

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-doc#1640]
Documentation: https://github.com/matrix-org/matrix-doc/blob/erikj/event_id_hashes/proposals/1640-event-id-as-hashes.md

This would basically mean instead of having IDs looking like `$foobar:example.com` they'd be something like: `7EQORdPaApfus7VgUPyupQ9d7P574HbgqqNKzgY7RoE`.

This would then mean that hashes wouldn't need to be included when referencing events in e.g. `prev_events`.

Open questions include: how do we specify the type of hash? Or do we mandate e.g. sha256 and if we want to change we create a new room version?

~~A fuller writeup will be along shortly.~~ see PR #1659

**Comment by ara4n** [comment]
Related: https://github.com/matrix-org/matrix-doc/issues/1127

**Comment by erikjohnston** [comment]
(MSC has been relabelled to MSC1659)
