### ISSUE TITLE
Redact Messages in Room After X number of Hours/Days

### ISSUE THREAD

**Issue by sraja415** [matrix-org/matrix-doc#1666]
Need a functionality to Redact Messages in Room After X number of Hours/Days as a setting at the room and 1-1 chat. 

Settings:
Delete after
- Read by All
- X Hours immaterial of read status
- Y Days immaterial of read status

**Comment by ma1uta** [comment]
Redact doesn't delete message. And redacted messages will be available in each server in the room. You can always get and read any redacted message from the database. Therefore automatic redacts doesn't make sense.

**Comment by richvdh** [comment]
https://github.com/vector-im/riot-web/issues/2497
