### ISSUE TITLE
No way to disinvite people you invite (unless you have ops)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1672]
Even if you have power in a room to invite users, you cannot disinvite them unless you have power to kick.  This feels very asymmetrical and unintuitive; if you accidentally invite someone you cannot do anything about it!

See also https://github.com/vector-im/riot-web/issues/7180 and https://github.com/vector-im/riot-web/issues/2989

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-doc/issues/664
