### ISSUE TITLE
clarify that /federation/v1/{state,state_ids} should return the state before the referenced event

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1683]
the spec isn't currently clear on what the result should be if the referenced event is itself a state event which changes the state.

It looks like it is meant to return the state *before* the referenced event.

**Comment by turt2live** [comment]
This should have been resolved by https://github.com/matrix-org/matrix-doc/pull/1587

**Comment by richvdh** [comment]
agreed. dup #1565
