### ISSUE TITLE
clarify the MSC process

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1694]
the MSC process has evolved since https://matrix.org/docs/spec/proposals was written, to the extent that it's unclear what the current process actually is.

**Comment by richvdh** [comment]
A particular case is over the `proposals` dir: there is exactly one proposal in there so far, and aiui said proposal is now merged into the spec. Is the idea that we keep the MSCs there forever? If so, when should they be merged? Also, #1693 changes an existing MSC: is that acceptable, or should it be a separate doc?

**Comment by maxidor** [comment]
@richvdh Just to be sure I understand the logic (I will not start a flame war) - why would the process be anything else than what is written? If it changed, shouldn't it be documented?

**Comment by richvdh** [comment]
We decided to experiment with some changes to see if they worked better for contributors and reviewers. They seem to be an improvement, so have de facto been adopted. The documentation has not yet caught up. Hence this bug.

**Comment by ara4n** [comment]
fixed by #1697
