### ISSUE TITLE
Fix swagger to not use matrix.org:8448

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1705]

**Comment by richvdh** [comment]
which bit of swagger, in particular, uses the incorrect host?

**Comment by turt2live** [comment]
Apparently the thing on matrix.org

**Comment by richvdh** [comment]
Ah the UI, yup: https://matrix.org/docs/api/client-server/

**Comment by jryans** [comment]
Is there a test server or something it should be changed to?

**Comment by jryans** [comment]
Hmm, it looks like 1fc64651687c48003f093b5e5f8e27ca02a4e4d3 intended to address this issue, but at the moment, the live [`api-docs.json`](https://matrix.org/docs/api/client-server/json/api-docs.json) still contains the old `host: "matrix.org:8448"` value.

Potentially this issue will be fixed next time docs are deployed to the production site? If not, perhaps the deployment process is skipping the step that regenerates this JSON file.

**Comment by jryans** [comment]
If I am following the deployment steps correctly, I believe the live `api-docs.json` is updated when a release of the C-S API happens.

* The most recent release was [r0.4.0](https://github.com/matrix-org/matrix.org/pull/220) on 2018-09-01
* The port fix in 1fc64651687c48003f093b5e5f8e27ca02a4e4d3 happened on 2018-10-08

So, the next release should include the port number fix. I opened matrix-org/matrix.org#269 to correct Swagger for the existing releases.

**Comment by richvdh** [comment]
for the record: @jryans fix got deployed yesterday, so this is now fixed \o/
