### ISSUE TITLE
Unmapping room state

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-doc#1723]
#### Background

The specification fails to provide adequate means by which implementations can *unmap* a `type,state_key` from their state map: whereby the event no longer appears in the endpoint responses or further affects the room's logic, etc. The only loosely related form of unmapping is perhaps in #1641 and other state-resolution behaviors. The purpose there is very specific and there is still no general means for unmapping. Also related is the ancient issue #456, which is still open after _four years_, but the discussion has different aims than what this issue suggests and is no longer relevant.

##### Security Implications

Unmapping is somewhat essential to the sound operation of a matrix room. Without it, any addition to the state map lives forever in that map. The inability to remove entries is a spam vector, and a metastasis of its size opens the door to a denial of service. This is different from an inability to remove entries from the timeline where there are different mitigation techniques available to compress and ignore old data.
- Though by default, room state cannot be added by unprivileged users, two special cases exist where it can be: `m.room.member` events and `m.room.aliases` events.
- Users who have *partial* privileges to add to the state map also assume exposure to these vectors. Just to be clear: a *partially* trusted user should not have the ability to *fully* kill the room via DoS. Let's leave that to fully trusted users first.

##### Feasible To Specify

What's at issue here is a *logical* function which is not *physically* deleting event data itself. This is why I've used the term *unmapping* and not *deleting* -- though the specification may use either. The point of this contrast intends to indicate it's possible to specify within the framework of the current r0 system. No major redesign of the protocol has to occur. Existing implementations should be able to tolerate divergence caused by an unmapping via the same means they currently withstand soft-failures and other state disagreements between servers.

##### Imperative To Specify Immediately

A heavy price for this oversight has already been paid and additional debt will occur if it is not remedied _now_. Fixing this now corrects the immediate and future direction of Matrix's design, specification and implementations. It is essential to all those working with this system that this missing function is available when they craft new features and fix old ones.
- The Alias system, essential to the core Matrix experience, has been shaped by hacking around the inability to unmap entries. This is well detailed by #1130. These effects have even caused the Matrix project principal @ara4n to consider aliases broken without any proper fix on the horizon.
- The Server ACL system was also mis-designed similar to Aliases due to the absence of unmapping. Furthermore, that system remains functionally incomplete as it lacks the endpoint suite required to workaround the effects; see: #1710.
- Various additional event types lack key-value granularity their functions would otherwise benefit from. For example the `m.room.power_levels` event follows the same single-array-list format; though admittedly, for that case, the singularity of the event is leveraged for consistency purposes in the new state resolution designed by @uhoreg -- other means of providing that consistency could also exist alongside a granular set of keys.
- Perhaps the design of room membership itself was compromised, very early on (as described in #456) by the inability to unmap state. Currently when a user joins a room, an entry is added to the room's state map with a `membership` value of `join`; when the user leaves the room the entry still exists in the room's state map with a `membership` value of `leave`. This makes it possible for any server to destroy any Matrix room by joining a few million (or whatever is necessary) users to it.

#### Suggested Solutions

1. Consider a redacted state event an unmapping. This is both UX and logically intuitive. It is also the least intrusive to the existing system, with only a few kinks to work out for the mistreatment of existing redacted state events (which are rare in the wild). These can be handled via soft-failure mechanisms by new implementations using this technique.

2. Introduce a new event type, similar in function to `m.room.redaction`, but specifically for unmapping state. At a glance the only advantage to a new type is that it won't conflict with existing redactions of state events. Nevertheless, old implementations won't know to unmap state events after encountering this type just the same as with the former suggestion, so I consider the former a bit more desirable.

**Comment by richvdh** [comment]
closing in favour of #456
