### ISSUE TITLE
"5.3.2   User-interactive API in the REST API" is inaccurate

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/matrix-doc#1725]
https://matrix.org/docs/spec/client_server/r0.4.0.html#user-interactive-api-in-the-rest-api

The spec says that "A client should first make a request with no auth parameter", to get the session key, and then later, "5.3.5   Fallback" says that "Once a client receives the notificaton that the authentication stage has been completed, it should resubmit the request with an auth dict with just the session ID".

Doing it this way causes the final request to fail, as the lack of an auth dict in the initial request and a request with an auth dict containing just the session ID means that a user cannot set a password. In the case where fallback is to be used, it appears that the password should be given as part of the initial request, rather than an empty auth dict.

**Comment by richvdh** [comment]
that sounds like a bug in synapse, not the spec.

**Comment by richvdh** [comment]
wait, I'm confused. Are you talking about setting a password (during registration), or giving the existing password (for some sort of re-authentication).

If the former, the password should be given in *each* request to `/register` *outside* the `auth` dict: the auth session is irrelevant.

If the latter, and you're doing the password auth via fallback auth, then there is no need for the client to pass the password to the server (the fallback auth page does that for you).

**Comment by turt2live** [comment]
@hawkowl I think we ended up discussing this out of band - are we able to close this?

**Comment by richvdh** [comment]
let's assume this is a non-issue
