### ISSUE TITLE
.well-known says to FAIL_ERROR in some identity server cases, but FAIL_ERROR is explicitly for homeservers

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1735]
due to

> At this point, valid data was obtained, but no **homeserver** is available to serve the client.

(emphasis mine)

**Comment by maxidor** [comment]
As this was kept from my original proposal, it's just a forgotten update - it was not meant as specific to homeserver - the scope really was the relevant type of Matrix server that was being validated in that section.
