### ISSUE TITLE
spec says that you only need CORS headers on OPTIONS requests

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1736]
... in practice, browsers expect the headers on other requests too.

**Comment by turt2live** [comment]
>  the homeserver should respond to pre-flight requests and supply Cross-Origin Resource Sharing (CORS) headers on all requests

The last part reads to me like it's required on all requests.

**Comment by richvdh** [comment]
hrm fair. Perhaps I should just read it more carefully. I looked at 

> When a client approaches the server with a pre-flight (OPTIONS) request, the server should respond with the CORS headers for that route

and inferred that I didn't need to add the CORS headers for other methods

**Comment by turt2live** [comment]
Even that section ends with "on all requests". There's probably some room to make it abundantly clear, however.
