### ISSUE TITLE
Examples have `membership` keys on event (in addition to event.content)

### ISSUE THREAD

**Issue by Johni0702** [matrix-org/matrix-doc#1766]
The examples in [this file](https://github.com/matrix-org/matrix-doc/blob/c1b630e975f2cde0b0101a46b11751dee204c666/api/client-server/rooms.yaml#L309) and [this one](https://github.com/matrix-org/matrix-doc/blob/c1b630e975f2cde0b0101a46b11751dee204c666/api/client-server/old_sync.yaml#L218) (and possibly others) have an additional `StateEvent.membership` entry (in addition to the one at `StateEvent.content.membership`), however those do not seem to be formally specified anywhere.

Synapse (0.34.0) also returns such state events from (at least) the `/sync` endpoint (haven't tested the above examples). So, if those additional `membership` entries aren't intended, an issue should be opened for synapse (in addition to fixing the examples).

**Comment by turt2live** [comment]
It's a legacy field that we should actually try and remove.
