### ISSUE TITLE
Link to mxid grammar in register endpoint docs

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-doc#1793]
The docs for POST /_matrix/client/r0/register go into some detail on how the grammar for mxids is restricted but only link to the actual grammar in the docs for the `user_id` *response* field. This feels like it belongs somewhere more prominent, eg. when it first talk about the grammar.

(Also we really need to split out a common spec section for this kind of thing: it being relegated to an appendix doesn't seem right).

**Comment by turt2live** [comment]
> Also we really need to split out a common spec section for this kind of thing: it being relegated to an appendix doesn't seem right

This is a general theme across the spec. We arguably also need to version the appendices, and possibly the index. We also need to clarify the relationship of spec versions (CS API advancing faster than the s2s spec, where both are slower than room versions...)
