### ISSUE TITLE
Github suggestions add a "Co-Authored-By" attribute - can we use this for sign off?

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1801]
eg: https://github.com/matrix-org/matrix-doc/pull/1790/commits/6e8739c989172c351a6ead66f073b413f6340326

**Comment by aaronraimist** [comment]
Kernel.org says this about "Co-developed-by" which is essentially the same:

> A Co-developed-by: states that the patch was also created by another developer along with the original author. This is useful at times when multiple people work on a single patch. Note, this person also needs to have a Signed-off-by: line in the patch as well.

https://www.kernel.org/doc/html/latest/process/submitting-patches.html#when-to-use-acked-by-cc-and-co-developed-by

**Comment by turt2live** [comment]
In practice we've been doing this, so it is probably fine.
