### ISSUE TITLE
bulk device delete api

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1809]
it's easy to end up with thousands of devices from a misbehaving script which keeps relogging in. this then breaks e2e and device list syncing. need to provide API to safely let users bulk delete devices which match some pattern

**Comment by turt2live** [comment]
We have this?
https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-delete-devices

**Comment by ara4n** [comment]
i'm not sure it helps much if my broken bot has been logging in every time it sends a message, so i have 150K devices...

**Comment by turt2live** [comment]
That endpoint should be able to handle a few hundred thousand devices, but might take a while to execute.

**Comment by turt2live** [comment]
also if the bot is logging in every time, it should probably call `/logout/all` every so often instead.

**Comment by ara4n** [comment]
i'm not sure that we can even query the full device list. but yeah, perhaps this is enough.

**Comment by ara4n** [comment]
will reopen if it proves insufficient.
