### ISSUE TITLE
Only send push if user is not online

### ISSUE THREAD

**Issue by ChristianPauly** [matrix-org/matrix-doc#1841]
At the moment push notifications are coming every time you get a message. So If you have one client, you will always receive the message from two ways. Or even worth if you have a mobile client and you are currently using Riot web, you will get every message with a sound on your phone too.

It would be awesome if there is a way that a push notification will only be sent if the user is not online with a client.

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/1293
