### ISSUE TITLE
The r0.1 S2S still talks about TLS fingerprints

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-doc#1842]
[Section 2.1](https://matrix.org/docs/spec/server_server/r0.1.0.html#retrieving-server-keys) of the S2S spec still reads:

> Homeservers publish the allowed TLS fingerprints and signing keys in a JSON object 

Which contradicts what is said in MSC1711:

> However, this fallback will be strictly time-limited, and Matrix S2S spec r0 will not accept self-signed certificates, nor will it include the tls_fingerprints property [...]

I assume this is just a simple oversight in the spec language?

**Comment by richvdh** [comment]
yes, this looks like an oversight. It shouldn't talk about tls fingerprints here.
