### ISSUE TITLE
Uncertainty on what matrix.to URIs look like with v3 events

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1867]
Should probably leave it as-is (https://matrix.to/#/!somewhere:example.org/$hash/with/slashes), but we may want to consider something else

**Comment by KitsuneRal** [comment]
Why would it change? Is it because slashes now can be but not necessarily are percent-escaped?

**Comment by turt2live** [comment]
Yea, it's an argument of figuring out if clients are too smart in parsing links. If they are, they'll break because of slashes.

**Comment by erikjohnston** [comment]
Is there a reason not to url encode it? That feels like something we should do anyway (don't we do that if we specify a room alias in there?)

**Comment by turt2live** [comment]
We don't currently specify that it is url encoded for anything. We treat it as a protocol uri (specifically saying it's not really a url), so there is some argument to saying it isn't encoded.

**Comment by erikjohnston** [comment]
But it is used as a uri, so not using the same rules feels like its going to result in issues
