### ISSUE TITLE
Exclude several types of account_data from /sync 

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-doc#1878]
At now `/sync` action return whole `account_data` object with all values, stored on server, from all defined types. 

Many bots and other services needs storage for local user data, and now they have only one place - `account_data`, even that stored data needed very rarely. So storing many keys in `account_data` will slow down every sync process, and transfer unneeded or rarely needed data every time.

For solve this problem, will be good to add something like `sync_exclude` boolean parameter to each type, stored in `account_data`, that will mark this type with group of keys for excluding from `/sync` reply.

**Comment by turt2live** [comment]
Clients can already filter out account data they don't care about by using a sync filter. They can either set it up as a whitelist or blacklist depending on their use case.

Is this not satisfactory?

**Comment by MurzNN** [comment]
Even if they can, this is not equal that all of them will do filtering by default :) I think that most of clients will load default `account_data` on `/sync`, without care of it contents, size and custom filtering.

So adding per-type default behavior of including/excluding it in `array_data` without filters will be good to have. At now I afraid to store many custom keys in my custom type of `account_data`, that needed only for one my custom client, because this will slow-up `/sync` process on all other clients.  

Also, can you provide an example how to filter `account_data` in `/sync` query now? I can't find any arguments for filtering `account_data` in spec https://matrix.org/docs/spec/client_server/unstable.html#id179 For example, which filter use Riot by default for loading `account-data`?

**Comment by turt2live** [comment]
Riot currently uses this:

```json
{
  "room": {
    "state": {
      "lazy_load_members": true
    }
  }
}
```

I'm not sure any particular client's bad behaviour is something we need to consider in the spec for this: we supply the tooling required for a client to make the right decision - if they don't use it, that's kinda their fault :(

A simple account data filter to only show `m.direct` changes would be:
```json
{
  "account_data": {
    "types": ["m.direct"]
  }
}
```

**Comment by MurzNN** [comment]
So, Riot now don't use filtering of `account_data`, and if I fill_up `account_data` with my 10000 keys like:
```
PUT /_matrix/client/r0/user/%40alice%3Aexample.com/account_data/my_custom_module_data HTTP/1.1
Content-Type: application/json

{
  "key1": "value1",
...
  "key9999": "value9999",
}
```
this array will be sent to Riot on each `/sync` query? That's bad, because I can't affect to other clients for exclude `my_custom_module_data` array from `account_data`.

**Comment by turt2live** [comment]
Not every sync query: it'll show up only when it changes or on an initial sync.

**Comment by MurzNN** [comment]
Ok, it will slow down only initial sync, and after this - Riot memory for storing unneeded data :)

So my current feature request is for provide per-user local storage for Matrix clients, that will be loaded only by direct query, not by default on each Matrix client via initial sync and other queries, that retrieve `account_data`.

**Comment by richvdh** [comment]
this feels a long way out of scope for what we want to do.
