### ISSUE TITLE
Spec says that dimensions on a thumbnail are optional, but does not define the expected behaviour if they are omitted

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1883]
https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-media-r0-thumbnail-servername-mediaid.

Personally I'm of the opinion that these should be mandatory, but if they are not we should define the expected behaviour. Note that synapse currently 500s if they are omitted: https://github.com/matrix-org/synapse/issues/2748

**Comment by turt2live** [comment]
Worth also noting that matrix-media-repo handles this nicely. I'm all for making them required though.

**Comment by richvdh** [comment]
what is matrix-media-repo's behaviour, ooi?

**Comment by turt2live** [comment]
picks the first configured thumbnail size in the config:
https://github.com/turt2live/matrix-media-repo/blob/master/src/github.com/turt2live/matrix-media-repo/api/r0/thumbnail.go#L42-L44

**Comment by richvdh** [comment]
I made an executive decision.
