### ISSUE TITLE
/room/${roomID}/messages requires "from" parameter, but should it?

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1892]
https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-rooms-roomid-messages

Synapse doesn't require the `from` parameter and functions well enough without it. I believe omitting from will get you the last N events in the room. This is useful for bridges/bots who wish to get messages they may have missed after being invited, who otherwise may have no existing token to use for `from`.

Can we drop this requirement and spec that a lack of `from` will pull the last N messages from the room?

**Comment by timokoesters** [comment]
Currently chat backups don't work on Conduit because of this bug. Either chat backups should set the `from` value or this should be changed in the spec soon.

**Comment by clokep** [comment]
[MSC3567](https://github.com/matrix-org/matrix-doc/pull/3567) makes it optional.

**Comment by turt2live** [comment]
Closing as fixed.
