### ISSUE TITLE
Application Service spec page still says unstable

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix-doc#1901]
On https://matrix.org/docs/spec/application_service/r0.1.0.html

>1   Changelog
>Version: unstable
>
>No significant changes.
>
>This version of the specification is generated from matrix-doc as of Git commit application_service/release-r0.1.0,4630c067.
>
>For the full historical changelog, see https://github.com/matrix-org/matrix-doc/blob/master/changelogs/application_service.rst

**Comment by turt2live** [comment]
gah, everything is awful. I really want to stop us from having generated output for specs >:(

**Comment by KitsuneRal** [comment]
Please keep generating but only data structures and calls :) Otherwise everything will become even awfuler.

**Comment by turt2live** [comment]
It's off topic for here, but something I'm experimenting with in room versions is to always generate it in the fly. Currently our specs get generated then left in the matrix.org repo to be forgotten.

So far, on the fly generation is working well enough for me to actually push forward on it everywhere.

**Comment by turt2live** [comment]
This just needs someone to update the appservice release branch on matrix-doc such that the changelog generates a real thing. Then update the matrix.org generated output. Blocked on https://github.com/matrix-org/matrix.org/issues/428 if I'm to do it.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix.org/commit/041fd573a5c0234b64833efaa1a4fe40ddcd3bd4 - the changelog generator had a bug at the time of release, so the changelog was wrong. The changelog itself was literally copy/pasted from the appservice changelog, which is what the script should have done.
