### ISSUE TITLE
Per room privacy settings: participating server whitelist

### ISSUE THREAD

**Issue by chresan** [matrix-org/matrix-doc#1918]
I'd like to propose that the per-room privacy settings allow to declare that either *any* homeserver may participate or otherwise  homeservers from a user definable whitelist are allowed.

My personal use case is that I need to be able to restrict certain rooms such that only accounts from my server can be in the room. (The implication being that the restricted rooms and their content do not get federated).

The generalization is that it is possible to define a whitelist of allowed homeservers. (In my case I allow only my own homeserver). Therefore federation can be limited per-room to whitelisted homeservers.

Currently the only way to prevent federation is to disable room invites for non-admins. 

I think that having control over ones own data is one of the main selling points of matrix/riot. My proposal further strengthens privacy.

**Comment by turt2live** [comment]
This sounds a bit like [Server ACLs](https://matrix.org/docs/spec/client_server/r0.4.0.html#server-access-control-lists-acls-for-rooms), although your use case might not fit perfectly within that.

**Comment by chresan** [comment]
Thanks for the hint. I'll read up on the server ACLs.

**Comment by chresan** [comment]
Ok, server ACLs seem to be exactly what I am looking for. Do you know if it is planned to make these settings accessible in the riot room settings dialog ?

**Comment by chresan** [comment]
Travis, this issue was actually meant as a prerequisite for a different issue I am currently preparing: regarding a room privacy option that allows to define the behavior of "redact"/remove for file/media objects. I think it should be possible to declare that files posted in a room do not get deduplicated (cache) and must be removed from the server if the user "redacts" a file. However, such an option would only make sense if the participating servers can be whitelisted to "trusted" servers.

**Comment by chresan** [comment]
Ok I close this issue since server ACLs fit.

**Comment by turt2live** [comment]
Sending server ACLs depends on the client. For Riot, it's tracked here: https://github.com/vector-im/riot-web/issues/7084

Regarding media redaction: https://github.com/matrix-org/matrix-doc/issues/790 covers the majority of it, although other issues and proposals of interest would be https://github.com/matrix-org/matrix-doc/issues/701, https://github.com/vector-im/riot-meta/issues/166, https://github.com/matrix-org/synapse/issues/2150, and https://github.com/matrix-org/synapse/issues/1263
