### ISSUE TITLE
Meta: Link to view the current specification is broken in speculator

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#1924]
Not sure if this is a matrix-doc issue or a matrix.org issue but it would be nice if there was only one way to look at the spec.

`@mayeul:mayeul.net` discovered that if you are looking at the spec through: 
https://matrix.org/speculator/spec/HEAD/client_server/unstable.html rather than 
https://matrix.org/docs/spec/client_server/unstable.html, the link to view the current specification is 404.

See: https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$155242013053bHbKf:mayeul.net?via=matrix.org&via=half-shot.uk&via=linuxgaming.life

Related: #1432

**Comment by turt2live** [comment]
The same happens for local development environments. `latest.html` is a matrix.org thing, but we should probably make it work. The argument for not bothering to make it work would be "as a developer, you probably wouldn't click it" but that's a fairly weak excuse.

**Comment by richvdh** [comment]
the speculator never came back after the april 2019 security incident.
