### ISSUE TITLE
support mounting APIs somewhere other than /_matrix

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1931]
there is at least one major 'run your own cloud' project which cannot ship Matrix currently because they demand all their services are mounted on specific subpaths on the server root, of which /_matrix is apparently not desirable. I suggest we make .well-known let you route to alternative subpaths.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-doc/issues/2780
