### ISSUE TITLE
Alias discovery is hard, allow it through room directory

### ISSUE THREAD

**Issue by MayeulC** [matrix-org/matrix-doc#1962]
During today's matrix.org outage, I tried to access a couple rooms I had not previously joined in from my homeserver. However, to do so, I needed a room alias. For instance, I was able to join `postmarketos:matrix.org` trough `postmarketos:disroot.org`, as I knew this alias beforehand.

However, I have no idea what aliases exist for `#matrix-spec:matrix.org`, or `#riot:matrix.org`. The traveler bot doesn't seem to publish this either, afaik.

I noticed that I could search a room located on another server's room directory by entering the remote homeserver's address in Riot's interface (_though it's not obvious in the UI_). However, it doesn't help if nobody registered an alias for that room.

 ------------
I would like to enhance alias discovery for cases such as this one with the following ability to search for a room's alias (example: `#riot:matrix.org` on ie, `kde.org`'s room directory
This would return the internal room id of that room on that server, and allow joining that room even if the canonical server is down.

Performing such a search could also be offered if trying to join `#riot:matrix.org` while matrix.org is down (and try to see if there's a consensus from the various homeserver's replies).

--------------

This would also cause the following issues:
* leak some information ("someone from that server has joined that room"), though it can be obtained by joining the room as well
  * Mitigate this somewhat by requiring a full mxid before returning an internal room id.
* expose to "phishing" (return a wrong room), though it would be less of a concern if there was a signed proof (by matrix.org) that the internal room id corresponds to the same room. I am afraid this isn't really fixable in practice, though, as this is an issue with aliases already.

**Comment by richvdh** [comment]
dup #1335
