### ISSUE TITLE
User-controlled Blog/Wall rooms with posts of greater prominence than comments

### ISSUE THREAD

**Issue by brettz9** [matrix-org/matrix-doc#1964]
My apologies, as I am quite new to Matrix, so I am just looking to get a high level overview for the moment...

Do you have any protocols working across server implementations that is akin to a Blog or Facebook Wall, whereby one user (or possibly a select group of users) has preeminent control, e.g., the ability to have a central comment of focus and maintain control of blocking users along with the ability to delete comments (of course if replicated across server, the user wouldn't be able to completely hide the details of those former replicated comments).

(Or, expanding on the possibilities with a central comment of focus, something like wikis, whereby a public group of users can edit a central post?)

**Comment by ma1uta** [comment]
Have you look at https://zotlabs.org/page/hubzilla/hubzilla-project or https://friendi.ca/?

**Comment by brettz9** [comment]
@ma1uta : Good to know about these, thank you.... But do you also happen to know if there are Matrix specs relevant to their social-media/blog features, or are these site-specific protocols/implementations?

**Comment by turt2live** [comment]
The Matrix spec can be applied to anything, although chat is one of the leading uses right now. Things like https://github.com/lukebarnard1/journal do exist as a thing on top of Matrix

In general, queries like this are best asked in the [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org) room
