### ISSUE TITLE
age field outside of unsigned under event context API

### ISSUE THREAD

**Issue by Sharparam** [matrix-org/matrix-doc#1968]
In [the Swagger docs for the event context API](https://matrix.org/docs/api/client-server/#!/Room32participation/getEventContext) the `age` field appears directly on the event object instead of inside an `unsigned` object like it does elsewhere.

Is this correct or should `unsigned` be added to the example JSON?

Edit: Also happens on [the state API](https://matrix.org/docs/api/client-server/#!/Room32participation/getRoomState).

**Comment by turt2live** [comment]
ftr it should be under `unsigned`. The age being top-level is a legacy representation of events that nothing should be using nowadays.
