### ISSUE TITLE
Inconsistency in parameters for join APIs

### ISSUE THREAD

**Issue by Sharparam** [matrix-org/matrix-doc#1978]
The [`POST /_matrix/client/r0/join/{roomIdOrAlias}`][joinRoomIdOrAlias] API takes a body parameter looking like:

```json
{
  "third_party_signed": {
    "signed": {
      "sender": "@cat:the.hat",
      "mxid": "@green:eggs.ham",
      "token": "random8nonce",
      "signatures": {
        "horton.hears": {
          "ed25519:0": "some9signature"
        }
      }
    }
  }
}
```

While the [`POST /_matrix/client/r0/rooms/{roomId}/join`][joinRoomId] API takes a body parameter looking like:

```json
{
  "third_party_signed": {
    "sender": "@cat:the.hat",
    "mxid": "@green:eggs.ham",
    "token": "random8nonce",
    "signatures": {
      "horton.hears": {
        "ed25519:0": "some9signature"
      }
    }
  }
}
```

This seems like a needless inconsistency to me (the extra wrapper object on the former API). Is this just a documentation error or is that how the APIs actually look?

[Original message in #matrix-dev.][context]

[joinRoomIdOrAlias]: https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-join-roomidoralias
[joinRoomId]: https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-rooms-roomid-join
[context]: https://matrix.to/#/!DYgXKezaHgMbiPMzjX:matrix.org/$155646799713YVFwU:matrix.sharparam.com?via=matrix.org&via=matrix.sharparam.com&via=berigora.net

**Comment by turt2live** [comment]
This is a spec bug: they are supposed to be the same.

From looking at Synapse, the expectation is:
```
{
  "third_party_signed": {
    "sender": "@cat:the.hat",
    "mxid": "@green:eggs.ham",
    "token": "random8nonce",
    "signatures": {
      "horton.hears": {
        "ed25519:0": "some9signature"
      }
    }
  }
}
```

I also failed to find an example of a membership event which claims the third party invite, but it looks like this:
```
{
  "type": "m.room.member",
  "sender": "@nvda_test:dev.t2host.io",
  "content": {
    "membership": "invite",
    "third_party_invite": {
      "signed": {
        "token": "redacted",
        "signatures": {
          "vector.im": {
            "ed25519:0": "redacted"
          }
        },
        "mxid": "@emailinvite:dev.t2host.io"
      },
      "display_name": "tra...@gma..."
    }
  },
  "state_key": "@emailinvite:dev.t2host.io",
  "event_id": "$155890428517YHyyA:dev.t2host.io",
  "origin_server_ts": 1558904285729,
  "unsigned": {
    "age": 12111
  },
  "room_id": "!tVwbflTVTPoszVQqna:dev.t2host.io"
}
```

So overall we have 1 bug and 1 clarification to make here.
