### ISSUE TITLE
Expected phone number format not well-specified

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#1982]
From [here](https://matrix.org/docs/spec/client_server/r0.4.0.html#phone-number):

```json
"identifier": {
  "type": "m.id.phone",
  "country": "<The country that the phone number is from>",
  "phone": "<The phone number>"
}
```

The specification does not define exactly what format the `country` field should have - should it be a country calling code, an ISO-3166 country code, or something else entirely?

It also doesn't specify what format the `phone` field should have, although I *assume* that it's expecting the phone number formatted as a local number.

Edit: To be clear, this is *not* about third-party identifiers with the `msisdn` medium, but about `m.id.phone`-type user identifiers.

**Comment by uhoreg** [comment]
From the Riot code, it looks like it's ISO-3166-1 alpha-2 code.  @dbkr can you confirm?

**Comment by turt2live** [comment]
ISO-3166-1 alpha-2 code looks right to me.
