### ISSUE TITLE
Buildkite takes forever 

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1993]
I may have been spoiled by CircleCI taking a matter of seconds to complete (usually well under a minute) - why does Buildkite take multiple minutes?

**Comment by richvdh** [comment]
Can you be more specific about where you see the delay? It looks like https://buildkite.com/matrix-dot-org/matrix-doc/builds/41#c7d8e153-e44c-4288-9e13-a3857d7079b9 started within seconds of the relevant commit being pushed and ran in under a minute. Is this more than you would expect? It looks like the bulk of that 55 seconds is actually running the python to build the spec, so I can't see any obvious reasons that CircleCI would be faster.

**Comment by richvdh** [comment]
Other factors might be:
* the circle builds seem to be using a prebuilt docker image to build the spec, whereas the buildkite build is creating a virtualenv from scratch
* each circle build does less than the buildkite build: this could be improved by splitting out more jobs for buildkite, to run on different agents
* It can take a few minutes to spin up new buildkite agents

It's worth noting that you're somewhat comparing apples and oranges: buildkite is replacing jenkins, not circle.

**Comment by turt2live** [comment]
We didn't have jenkins building PRs before though - just the master branch for deployment. Can we switch back to that?

**Comment by richvdh** [comment]
> We didn't have jenkins building PRs before though - just the master branch for deployment. Can we switch back to that?

sure! done.

**Comment by turt2live** [comment]
the history on this issue is completely out of order, but building just master seems fine so closing.
