### ISSUE TITLE
Clarify that empty strings === null === undefined unless otherwise stated

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2007]

**Comment by turt2live** [comment]
eg: https://github.com/matrix-org/matrix-doc/issues/2006

**Comment by erikjohnston** [comment]
Really? Where do we do this?

**Comment by richvdh** [comment]
Personally I thought that the general rules were:
* you weren't alllowed to pass `null` over the API unless it was explicitly mentioned
* you signal the absence of a value by not sending it
* empty string is a specific value which is *different* from `null` or \<absent>

**Comment by turt2live** [comment]
We indeed are saying null isn't allowed for the general case
