### ISSUE TITLE
Client spec doesn't define how unread notifications transition to read

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix-doc#2015]
The [sync response](https://matrix.org/docs/spec/client_server/latest.html#get-matrix-client-r0-sync) includes unread notifications for joined rooms, but the spec doesn't appear to discuss how a notification changes from unread to read.

Empirically, Synapse appears to use the user's last read receipt in the room to determine whether a notification is read. Could we just record that decision in the spec, or would an MSC be needed?

**Comment by turt2live** [comment]
it's explained in the read receipts section, so I think we just need to put a pointer from the sync module to that receipts module

**Comment by jryans** [comment]
Hmm, maybe the explanation is presented abstract in terms of events generally? I searched the read receipts section for the term "notification", but I didn't see anything there...

**Comment by turt2live** [comment]
clarification x2 I guess: the receipts module should also say those words

**Comment by ara4n** [comment]
(this doesn't need an MSC given it's a clarification, imo)
