### ISSUE TITLE
Identity service spec is missing some optional parameters for requests to /store-invite

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#2048]
https://matrix.org/docs/spec/identity_service/unstable.html#post-matrix-identity-api-v1-store-invite is mentioning four required parameters in requests: `medium`, `address`, `room_id` and `sender`.

Both Synapse and Sydent are sending/expecting more (optional) parameters, which are missing from the spec:

* `room_alias`
* `room_avatar_url`
* `room_join_rules`
* `room_name`
* `sender_display_name`
* `sender_avatar_url`
* `guest_access_token`
* `guest_user_id`

as per https://github.com/matrix-org/synapse/blob/master/synapse/handlers/room_member.py#L885-L962

Not sure whether the fault is on Synapse/Sydent for using undocumented parameters, or the spec for not documenting them, so in doubt I'm opening it here.

**Comment by turt2live** [comment]
last commit there was 3 years ago, so I'm calling that a spec omission
