### ISSUE TITLE
Clarify how thumbnailing is supposed to work

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2060]
Particularly the methods: crop/scale

**Comment by ara4n** [comment]
The intention is that crop removes data to make the image approximately fit into the requested aspect ratio, and scale shrinks the image down (inserting a background colour) to make the image approximately fit instead.  It's the same difference as between pan & scan (crop) versus letterboxing (scale), for those familiar with the terms.

The server treats the dimensions provided as an aspect ratio, and then should provide an image at least as large as the requested dimensions.  This approximation is to avoid DoS and let servers precalculate thumbnails for commonly requested dimension sizes.

It's worth noting that synapse currently gets this wrong; if you request a bigger thumbnail than the largest one it's precalculated, you get the largest thumbnail (https://github.com/matrix-org/synapse/issues/5302) which may undershoot.  Cropping apparently can also undershoot (https://github.com/matrix-org/synapse/issues/1222).  When you undershoot, the client has to scale up the resulting image, resulting in horrid blurriness artefacts.

**Comment by turt2live** [comment]
How should the server handle being requested to give a thumbnail larger than the source material?

**Comment by ara4n** [comment]
it should return the source material.
