### ISSUE TITLE
Request token endpoint has incorrect example

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#2062]
The [spec says](https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-account-password-email-requesttoken) a request to `https://matrix.org/_matrix/client/r0/account/password/email/requestToken` should return:

```
{
  "sid": "123abc"
}
```

Synapse returns:

```
{
"success": true,
"sid": "xxxx"
}
```

Those are not the same.

**Comment by richvdh** [comment]
they are not the same, but that's not necessarily the fault of the spec. Servers can add additional fields to their responses whilst remaining true to the spec...

**Comment by turt2live** [comment]
Unless `success` is proven to be used by something, I'm thinking this can be closed as won't fix.

**Comment by anoadragon453** [comment]
It is not used by Riot, and afaik no other client allows a password reset.

https://github.com/matrix-org/matrix-react-sdk/blob/19edc5c5a4dd3f807dae2d15e0476ef105ca9344/src/PasswordReset.js#L71

**Comment by turt2live** [comment]
Closing as just a weird thing synapse does then.
