### ISSUE TITLE
Specify format of origin_server_ts

### ISSUE THREAD

**Issue by jimmycuadra** [matrix-org/matrix-doc#2064]
The `origin_server_ts` event field is repeatedly described by the client-server spec as a "timestamp in milliseconds on originating homeserver when this event was sent." It's never stated explicitly in the client-server spec, introduction, or appendices what the format of this timestamp is. It's stated to be an integer, but not what the reference point of this value is. An experienced developer might infer that it's intended to be unix time, but that is traditionally represented in seconds and not milliseconds, so it's still ambiguous. It should be stated explicitly how to interpret `origin_server_ts` values.

This issue is a subset of #684.

**Comment by turt2live** [comment]
Going to count this as https://github.com/matrix-org/matrix-doc/issues/1468 because it'd be fixed at the same time.
