### ISSUE TITLE
Presence list API response does not match m.presence schema

### ISSUE THREAD

**Issue by jimmycuadra** [matrix-org/matrix-doc#2065]
In r0.4.0 of the client-server spec, the schema of the m.presence event is shown as:

``` json
{
    "content": {
        "avatar_url": "mxc://localhost:wefuiwegh8742w",
        "currently_active": false,
        "last_active_ago": 2478593,
        "presence": "online"
    },
    "sender": "@example:localhost",
    "type": "m.presence"
}
```

However, the response of the [presence list API](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-presence-list-userid) is shown with a different structure for the event:

``` json
[
  {
    "content": {
      "last_active_ago": 395,
      "presence": "offline",
      "user_id": "@alice:matrix.org"
    },
    "type": "m.presence"
  },
  {
    "content": {
      "last_active_ago": 16874,
      "presence": "online",
      "user_id": "@marisa:matrix.org",
      "currently_active": true
    },
    "type": "m.presence"
  }
]
```

I think the latter is wrong and from an older version of the spec before "user_id" was changed to "sender". Notice that "user_id" is inside the "content" object in the API response whereas "sender" is in the top-level object in the event. "avatar_url" is also missing in the API response.

**Comment by turt2live** [comment]
Presence lists were removed: https://github.com/matrix-org/matrix-doc/pull/1819
