### ISSUE TITLE
we should specify which servers must sign events

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2074]
We do not seem to specify which server(s) must have signed an event for it to be considered valid

**Comment by richvdh** [comment]
I'm not really sure if this belongs under [Checks performed on receipt of a PDU](https://matrix.org/docs/spec/server_server/r0.1.1.html#checks-performed-on-receipt-of-a-pdu), [Validating hashes and signatures](https://matrix.org/docs/spec/server_server/r0.1.1.html#validating-hashes-and-signatures-on-received-events), or even [Checking for a signature](https://matrix.org/docs/spec/appendices.html#checking-for-a-signature) in the appendix, but it ought to be *somewhere*.

**Comment by turt2live** [comment]
I'd probably vote for the first two, maybe one referencing the other.

**Comment by richvdh** [comment]
The rules are something like:

* for all events except invite events in response to a 3pid invite, the event must be signed by the server whose server name is in the `sender` of the event
* for room v1-v2, the event must be signed by the server in the `event_id`, where that is different.

See https://github.com/matrix-org/synapse/blob/aa530e68005d041ad037b081fe748d301a11291a/synapse/federation/federation_base.py#L213.
