### ISSUE TITLE
Clarify why /_matrix/federation/v1/event/ returns an array

### ISSUE THREAD

**Issue by JJJollyjim** [matrix-org/matrix-doc#2093]
Apparently `GET /_matrix/federation/v1/event/{eventId}` "Retrieves a single event".

The response contains an array `pdus` which "Must not include more than 50 PDUs".

May it ever include more than one PDU?

What if the same eventId is used in multiple rooms?

**Comment by JJJollyjim** [comment]
I'm pretty sure the answer is "it always returns one and event IDs duplicated between rooms are undefined behavior": in that case the field description text in the response text should probably be changed to something like "List containing a single persistent update to a room. Note that events have a different format depending on the room version - check the room version specification for precise event formats.".

**Comment by turt2live** [comment]
It returns a Transaction object, which awkwardly has a schema written for the `/transaction` endpoint. I believe we have words somewhere to say it "must only have 1 event", however this may have been lost in translation.
