### ISSUE TITLE
IS spec introduced invalid id_server params

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2118]
https://matrix.org/docs/spec/identity_service/r0.2.0.html#post-matrix-identity-api-v1-validate-email-requesttoken

**Comment by anoadragon453** [comment]
This happened [here](https://github.com/matrix-org/matrix-doc/pull/2101/commits/d1fde0837af4ecfde83532f0c027bde4f4c5ea10) btw

**Comment by turt2live** [comment]
yup, which is annoying because I really like how useful the $ref is there.

But, alas, we need duplication in order for the spec to make sense :(
