### ISSUE TITLE
Online specs have poor readability due to low contrast

### ISSUE THREAD

**Issue by chenz** [matrix-org/matrix-doc#2119]
The specs at https://matrix.org/docs/spec/ are hard to read due to the low contrast color choices of light gray on white for the main text, as well as light blue for links.

In Firefox, I tweaked the colors to `#000` (text) and `#00f` (links) for much improved readability.

**Comment by Half-Shot** [comment]
I hadn't noticed this before, but I agree its a bit hard to read unless you crank up your monitor settings.

**Comment by supersexy** [comment]
I just hit that wall, too - yes, please do not apply any "modern low contrast design" to any kind of documentation - it is already hard enough to tune in, no reason to distract users with additional problems. 

Regarding monitor settings: it should happen the other way around - if you are publishing docs that should be readable to everybody, lower the contrast of your monitor to better understand, if the contrast is  ok. 

Still, better keep the contrast as it is by default. There is no sane reason to add low contrast to the main text of anything that should be read by others. Low contrast text may be ok for not selectable menu or page items, but then you can ask yourself why it is visible at all. Actually there is no good reason for low contrast text anywhere. It is just a very ugly design anti-pattern that for some reasons people without formal design education adopt without knowing that they are hurting people with bad sight or people that just turn down the monitor contrast setting. This is not a matter of taste. 

Also please take a look at https://www.contrastrebellion.com/

Thanks!

**Comment by lazycipher** [comment]
The low contrast literally gives me trouble. I prefer changing color with inspect element instead of looking like an eagle to understand each word!

**Comment by ara4n** [comment]
fixed by matrix-org/matrix.org#852 (thanks @wbamberg!). closing in favour of #2805 for further discussion.
