### ISSUE TITLE
Identity service should do lookups based on hashed 3PIDs, not plaintext ones.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2130]
There is no reason for an IS to ever handle plaintext 3PIDs when doing a lookup; from a privacy perspective we should hash them.

**Comment by Half-Shot** [comment]
Related https://matrix.org/docs/spec/identity_service/r0.2.0#association-lookup

**Comment by turt2live** [comment]
ftr, there is a reason in the case of identity servers backed by another system, such as LDAP. The identity server might not know if a user exists based on hash (as it would be compute heavy to pull all the users from the external system and hash all their identifiers at that point in time), and therefore would need the plain text address so it can more easily do the lookup.

The more general cases though should be hashed, although I question to what extent we do this.
