### ISSUE TITLE
Why is `redacts` an event-level field?

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2145]
According to [the specification](https://matrix.org/docs/spec/client_server/r0.5.0#m-room-redaction), `redacts` is an event-level field, and not part of the `content`. However, it *seems* like it should be in the `content`, being specific to a particular event type, and no motivation is provided in the specification as to why it is event-level instead.

What's the reason for this being the case, and is there any overarching concept or concern in the protocol design that motivates this decision?

**Comment by richvdh** [comment]
dup #502
