### ISSUE TITLE
Docs list wrong key `threepidCreds` for email/id based user auth

### ISSUE THREAD

**Issue by eyecreate** [matrix-org/matrix-doc#2189]
When using the docs/spec to build out a client, I ran into an issue when trying to auth using email from id server. 

According to docs, the auth looks like this:

https://github.com/matrix-org/matrix-doc/blob/ad5d46d3317bd3d016ed7bf1e3fb5ce1f8d7fef1/specification/client_server_api.rst#L797

But according to synapse, it should be named this:

https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/handlers/auth.py#L454

So the two differences are the key name and whether it should contain an object or array.

**Comment by turt2live** [comment]
I'd consider that a bug in the implementation as the spec is considered consistent whereas the implementation is not.

**Comment by eyecreate** [comment]
Alright, I filed a bug against synapse over on that repo.
https://github.com/matrix-org/synapse/issues/5748

**Comment by richvdh** [comment]
I'm not so sure I agree. In practice, riot-web and synapse agree on it being called `threepid_creds`, which is consistent with the naming conventions elsewhere in the protocol. 

It looks like synapse was changed four years ago, but the spec never got updated to match: https://github.com/matrix-org/synapse/commit/a21861962608726a5fe443762421c80119517778. (Or possibly, the spec has been wrong from the start).

Changing the implementations to use the camelcased identifier with a spurious array sounds like a retrograde step. Can we just consider it a spec bug?

**Comment by turt2live** [comment]
riot-web would rather not support `threepid_creds` if it doesn't have to: https://github.com/matrix-org/matrix-react-sdk/pull/3211/files#diff-ecb026ca076d9eb268c19a3cbccd29f1R472

The one place it was missed was the password reset page: https://github.com/matrix-org/matrix-react-sdk/blob/19edc5c5a4dd3f807dae2d15e0476ef105ca9344/src/PasswordReset.js#L74

The array does indeed look spurious though, given neither implementation provides it as such. It's worth noting that the spec itself is older than the Synapse implementation not only in commits (https://github.com/matrix-org/matrix-doc/commit/8495d9451e893be6a0fdbe0682b3eca85f935452 vs https://github.com/matrix-org/synapse/commit/a21861962608726a5fe443762421c80119517778) but also in when the PRs were merged (https://github.com/matrix-org/matrix-doc/pull/15 vs https://github.com/matrix-org/synapse/pull/126). 

While I agree that we should be consistent with our own code style (we specify that underscores are preferred over camelcase) I would still argue that changing it requires a MSC at a minimum.

**Comment by richvdh** [comment]
> The one place it was missed was the password reset page: https://github.com/matrix-org/matrix-react-sdk/blob/19edc5c5a4dd3f807dae2d15e0476ef105ca9344/src/PasswordReset.js#L74

riot-web also has https://github.com/matrix-org/matrix-js-sdk/blob/9fb6eea/src/interactive-auth.js#L182, ftr.
