### ISSUE TITLE
3pid management in the client-server is inconsistent with itself

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2220]
`threepidCreds` vs `threepid_creds` vs `three_pid_creds`, non-RESTful endpoints, general duplication that isn't entirely needed

**Comment by richvdh** [comment]
related: #2189

**Comment by anoadragon453** [comment]
#2290 proposes to do away with `three_pid_creds` on the Client Server API.

**Comment by richvdh** [comment]
the `three_pid_creds` references are only on duplicated endpoints, and the `threepidCreds` ones are covered by #2189, so I'm going to close this.
