### ISSUE TITLE
spec incorrectly claims that `PUT /_matrix/federation/v1/send/{txnId}` response has a [200, ...] wrapper

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2236]
this is a bug. See https://github.com/matrix-org/matrix-doc/pull/1802#issuecomment-521959258

**Comment by richvdh** [comment]
Unlike the other endpoints mentioned in #1418 / [MSC1802](#1802), this is a spec bug: `PUT /_matrix/federation/v1/send` does *not* have a `[200, ...]` wrapper in the response.
