### ISSUE TITLE
Missing "Response format" for POST /account/3pid

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#2237]
Concerning https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-account-3pid. 

The "Response format" wasn't specified but the example response is non-empty.

Usually when there's no format, the example is an empty JSON object (like it was done [here](https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-rooms-roomid-kick)), but here the response example isn't empty.

**Comment by Dominaezzz** [comment]
Looks like the format was there https://github.com/matrix-org/matrix-doc/blob/2cafa7e1e878503c7d71d6c3ac21d66c516c84cd/api/client-server/administrative_contact.yaml#L140 . Just with wrong indentation :grin: .

**Comment by KitsuneRal** [comment]
That's worth a validation check :)
