### ISSUE TITLE
Missing enumeration for GET /capabilities

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#2242]
https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-capabilities .

For `RoomVersionsCapability.available`, it is a map of string to enum, but the enums aren't stated.
Usually there's something like `One of: ["invite", "join", "knock", "leave", "ban"]` in the doc.

**Comment by turt2live** [comment]
It actually shouldn't be an enum at all: it's a map of versions to stability, and it should say that instead.

**Comment by Half-Shot** [comment]
I think @Dominaezzz is correct here:

> it is a **map of string to enum**, but the enums aren't stated.

Where I'm going to hazard a guess that the values should be `["stable", "unstable"]`

```
{
    "capabilities": {
        "m.room_versions": {
            "default": "4",
            "available": {
                "1": "stable",
                "2": "stable",
                "3": "stable",
                "4": "stable",
                "5": "stable"
            }
        },
        "m.change_password": {
            "enabled": true
        }
    }
}
```

**Comment by Half-Shot** [comment]
Oh, it's already defined in the spec. Is it incorrectly defined or does our spec renderer suck?

https://github.com/matrix-org/matrix-doc/blob/72242e4ebbb81852277e72e05ac10e85c4005aba/api/client-server/capabilities.yaml#L97-L105

**Comment by turt2live** [comment]
wonderful... another case of our RST rendering being sub-par
