### ISSUE TITLE
Key not specified for room entries in `/sync`

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2269]
[The spec](https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-sync) says the following under "Rooms":

![Selection_186](https://user-images.githubusercontent.com/1663259/64063933-9182a980-cbfb-11e9-9a32-7fa9fa8cc610.png)

... which, as I understand it, means that each of those is an object keyed by *something*, mapping to a room data object. However, it's never actually specified what that key *is*, other than that it is string-shaped.

Is the key the room ID?

**Comment by turt2live** [comment]
the key is the room ID ftr
