### ISSUE TITLE
submit_url authentication unclear

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix-doc#2298]
For `requestToken` APIs, the spec says they may return `submit_url` "with identical parameters to the Identity Service API's POST /validate/email/submitToken endpoint".

That was likely clear when written, but now with MSC2140 having added a v2 IS API that also layers on auth, it has become less clear.

(I would assume this intention is for such URLs to be called as if they were a v1 IS API, so no authentication.)

**Comment by turt2live** [comment]
it is indeed not authenticated because the other parameters identify the requester.
