### ISSUE TITLE
Limits on prev_events and auth_events

### ISSUE THREAD

**Issue by lucavb** [matrix-org/matrix-doc#2307]
None of the room versions make any mention of limits on the fields `prev_events` and `auth_events`, however Synapse rejects events that come via the federation API that reference more than 20 "previous events" and more than 10 "auth_events". The events can be accepted by Synapse through backfilling if they are referenced by another accepted event. The reasoning behind this, is that many referenced events could trigger a potentially costly state resolution algorithm. And the reasoning for allowing it through backfilling is to prevent inconsistent and unsolvable states.

My question is: Should this be adapted in a new room version as official limits?

[Room Version 3](https://matrix.org/docs/spec/rooms/v3)
[Synapse rejecting via federation API](https://github.com/matrix-org/synapse/blob/master/synapse/handlers/federation.py#L1059)
[Synapse accepting via backfilling](https://github.com/matrix-org/synapse/blob/master/synapse/handlers/federation.py#L661)

I've referenced room version 3, because it is the last to define a full PDU and neither 4 nor 5 have made any changes to the fields.

**Comment by florianjacob** [comment]
Related synapse issue: https://github.com/matrix-org/synapse/issues/3124

**Comment by erikjohnston** [comment]
FTR #1594 effectively specs the limit of the number of `auth_events` an event can have
