### ISSUE TITLE
Advices to create a forum on top of matrix protocol

### ISSUE THREAD

**Issue by tobiasBora** [matrix-org/matrix-doc#2317]
Hello,

I'm very new to matrix, and I'm thinking to build on top of matrix a client that would provide to users a forum/stackoverflow-like interface. I was thinking (thanks to some advices online) to create a "community" that would contain all the threads as different channels, and then to use the search API to search through all the community threads, and create events based on "tags" so that all the interested users can get notified, eventually by email, when an event occurs... The moderation could eventually be done by automatically adding some moderators to the newly created rooms I guess. The "reply to"/"like" features would be implementer more or less like in Riot (I still need to check if Riot's "reply to" provides a link to a text). And if I want to allow users to edit their (or another user's) messages, I'm not sure yet but I guess it's always possible to create custom messages that say "Message XXX is not valid anymore, use message YYY instead."

The only thing that seems to be harder to implement right now seems to be how to provide a way to give marks to users depending on the number of "like" their answers got, as it implies a quite intensive search through the database. I may consider using a separate bot for this task, but it's not even clear how I would use it...

So here are my questions:

1) is matrix suitable for this kind of task?
2) if yes, why is there no forum client? Just a lack of time or is it a particular hard task to achieve?
3) do you think my "sketch of code" looks good, or is there some great alternative I missed?
4) do you have any advice on how I could implement efficiently the "points" system?
5) for this kind of task, should I write only client-side code, or am I also supposed to write a bit of server-side code/bots/...?

Thanks a lot for the good work!

**Comment by russelldavies** [comment]
Did you end up developing something in the end?

**Comment by ShadowJonathan** [comment]
1. Yes
2. There are several, https://hummingbard.com/ being a personal favourite that can develop into this, but it is entirely possible some are brewing under the surface without much mention

I would recommend keeping an eye on [TWIM](https://matrix.org/blog/) or skim through it, there have been some project mentions in the past for a slow/forum/discussion-type client/interface for matrix a few times.

**Comment by russelldavies** [comment]
Thanks for the links.

I was actually thinking about building an internal support based ticket system on top of Matrix. As sometimes there are rapid responses back and forth on a ticket, it would much better suited to have instant messaging solution.

The way I was thinking of structuring it was that each ticket is a room and the room topic is the ticket status (new, stalled, resolved, etc). In addition to standard message events I'd have a custom event for support techs to log their time spent.

This is still very much in the idea stage so if someone has done something similar please do let me know.

**Comment by ShadowJonathan** [comment]
Please keep in mind that rooms do not currently scale nicely on synapse, as it has to walk every room with a bit of overhead to get the latest response. What maybe more practical is to utilize only one room, and to use "relations" (search this repo for related MSCs) to that original event to effectively create threading.

Currently it is less overhead to do everything in one room than it is to do it in many rooms, though that'll most likely change in the future, as implementations get better at it, and another sync proposal comes out (v3) that helps with this scalability.

**Comment by richvdh** [comment]
I'm going to close this issue as it's not really the right place to discuss ideas for matrix clients.

**Comment by askender** [comment]
same topic: https://github.com/matrix-org/matrix.org/issues/43

**Comment by rokejulianlockhart** [comment]
@askender, this isn't the same. However, it shouldn't really be an issue. If you allow https://github.com/matrix-org/matrix-spec-proposals/issues/4012#issue-1696768273, you can transfer this into an issue for additional discussion.
