### ISSUE TITLE
Private information for devices

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-doc#2327]
Ability to store information against a user's device that is only visible to the themselves, including:

 * Some kind of private name for the device
 * IP Address (probably last one it was seen from?) plus geoip-ed location if server supports it
 * Name of client
 * Type of device ('iPhone' / 'OnePlus 6' / 'Google Chrome' etc.)

anything else?

**Comment by aaronraimist** [comment]
Dup of #1826
