### ISSUE TITLE
spec is contradictory about /context's support for filters

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2338]
According to [the spec](https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-rooms-roomid-context-eventid), /context supports lazy-loading of members; however, lazy-loading is configured via a filter, and the spec doesn't say anything about /context supporting filters

**Comment by turt2live** [comment]
What does Synapse do? (and is there a TODO comment to fix it?)

**Comment by richvdh** [comment]
synapse apparently supports filters on /context.
