### ISSUE TITLE
Allow clients not supporting a feature to display a human readable description of ignored events.

### ISSUE THREAD

**Issue by kaie** [matrix-org/matrix-doc#2410]
Scenario:

I'm using a client that doesn't support a feature.
I'm in a chat room and see "user: unknown event".
I'm frustrated that I might potentially be missing an important part of my conversation and decide I must stop using this client, and instead use the most powerful client available, to ensure I'm not missing anything.

Suggestion:

The matrix protocol should invent a general mechanism that can avoid the frustration in the above scenario.
Enable clients, which don't yet support all the latest features, to show a human readable description of the unknown event.

Examples:
- user-A sent an emoji reaction to an earlier comment by user-B
- user-A sent an invite to join a video chat room
- user-A shared a file of content type: image

Possible implementation:
For all types of events that cannot be assumed to be supported by 100% of all deployed client software, require that each sent event includes a human readable description and a event type identifier.
Suggest that for all currently supported event types, and require it for all new event types introduced in the future.
Client software could have a general implementation, that notifies about any unsupported events, and displays the human readable message and an event type identifier.
Users would either immediately understand if the missing information is relevant, or they could search the web for the given event type identifier. Or even better, standardize a https link, that clients can offer to open, which brings them to a page that describes the event type. E.g. "https://matrix.org/event-type/" + identifier "123 "

With this, frustration on the user side can be avoided. They can more easily decide if they need to switch to a more powerul client to guarantee full participation in the channel's event, or if they can safely ignore that type of event.

In addition, to avoid unnecessary noise, a client could have a universal implementation to slience all events of a given type (e.g. silence all events of type 123)

**Comment by turt2live** [comment]
How clients choose to handle it is up to them - some clients, like riot-web, just ignore them outright.

Overall this sort of discussion would be best put on the MSC for human representation of events: https://github.com/matrix-org/matrix-doc/pull/1767

**Comment by ara4n** [comment]
to be clear, #1767 is meant to effectively fix this by defining human fallbacks for everything to prevent the problems you're describing here.
