### ISSUE TITLE
Doc on /messages is unclear/untrue

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2420]
* It says `from` and `to` can't be a `next_batch` from a previous sync, but I'm pretty sure that riot-web relies on that and synapse supports it.
 * for the `start` and `end` parameters it says what they will be if `dir=b`, but I'm pretty sure those comments also apply if `dir=f`.

**Comment by ShadowJonathan** [comment]
From #3019, extra:

> Required. The direction to return events from. One of: ["b", "f"]

- This is ambiguous and not immediately clear what each of these two values do, even if it can be deduced, it should be declared explicitly.
