### ISSUE TITLE
Login flow documentation talks about multi-stage auth, but endpoints don't

### ISSUE THREAD

**Issue by emilazy** [matrix-org/matrix-doc#2436]
Searching the [User-Interactive Authentication API](https://matrix.org/docs/spec/client_server/r0.6.0#user-interactive-authentication-api) specification (and other parts of the Client–Server API) for `"stages":` turns up a bunch of results, and it also says things like:

> The process takes the form of one or more 'stages'. At each stage the client submits a set of data for a given authentication type and awaits a response from the server, which will either be a final success or a request to perform an additional stage. This exchange continues until the final success.

But the documentation for the endpoints, e.g. [`GET /_matrix/client/r0/login`](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-login), just defines `LoginFlow` as `{"type": string}`. It seems like multi-stage authentication flows have been added to the specification text and examples, but not to the endpoint format specifications, which I personally find quite confusing as a client developer!

**Comment by turt2live** [comment]
per elsewhere: `/login` doesn't support UIA but I think the endpoints that do aren't great at describing it either.

**Comment by emilazy** [comment]
Ah, after some talk on `#ruma:matrix.org` I see that my confusion here is that the "user-interactive authentication API" documentation does *not* apply to the login endpoints at present, only registration. I guess the real bug here is just that the specification wording is pretty confusing and could at least use clarification that it's only implemented for registration at present.

**Comment by richvdh** [comment]
see also: https://github.com/matrix-org/matrix-doc/issues/2187

**Comment by richvdh** [comment]
I think this issue is mostly a confusion between UIA and login.
