### ISSUE TITLE
E-mail invite to the same homeserver

### ISSUE THREAD

**Issue by notramo** [matrix-org/matrix-doc#2441]
Currently, the e-mail invitation link opens riot.im/app with matrix.org HS configured. It would be much better to prefill the same HS that the Matrix user is using who sent the invitation (so the new account would be created on that server instead of matrix.org).

**Comment by turt2live** [comment]
This would be a client feature.

**Comment by notramo** [comment]
OK, I will open an issue in the Riot repo.
The Riot Web version needs to know who sent the invite (from what HS). Is it included in the invitation URL?
