### ISSUE TITLE
Invite-only homeserver

### ISSUE THREAD

**Issue by notramo** [matrix-org/matrix-doc#2442]
It would be useful to have „invite only” homeservers.
The public registration would be disabled on these HS-es.
There would be a list of e-mail addresses which are allowed for registration.
When a user sends an invite to an e-mail address, that address would be added to the list automatically. If the invited user opens the URL, the homeserver and e-mail address would be prefilled in Riot, so the HS can decide if the e-mail addres is allowed.
(There should be an option to edit the list manually e.g. adding from a list of e-mail addresses of employees at a company.)

This feature would be useful for admins of small homeservers who don't want to allow public registration but also don't want to add every user manually (and this would allow users to invite friends easily).

**Comment by turt2live** [comment]
This would be a feature of the homeserver itself where the spec wouldn't concern itself with. There's a number of gateway services you can put in front of your server to have things like invite codes, additional checks, etc as well as Synapse already having the option to lock down/require registration with a particular set of email domains.

**Comment by notramo** [comment]
Is it possible as a regular Matrix user on a homeserver to send an invite to somebody on a closed-registration HS?
How user-friendly is it?

**Comment by turt2live** [comment]
The openness of registration has no bearing on invites.

**Comment by notramo** [comment]
> The openness of registration has no bearing on invites.

It has.
Let's assume an admin wants to operate a HS, but only for **his friends** and **their friends**.
He don't want to give admin access to his friends, so he would enable "invite-only registration".
His friends could send invitations to their friends in e-mail with the same UX as e-mail invite has currently. This would be an user-friendly way to allow creating new user accounts on a closed-registration server.

**Comment by turt2live** [comment]
The email invite doesn't have to go to that server though - it can be claimed on any other server which happens to federate with it, as long as the clients involved use the same identity server.

#matrix:matrix.org would be a better place to talk about this with the community than a GitHub issue if you're curious as to how this works.

**Comment by notramo** [comment]
Sorry, I forgot that identity servers also play a role in this. Obviously this would be more complicated in this case.
