### ISSUE TITLE
Notifications by keyword (IRC /hilight command)

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-doc#2446]
I really appreciate being able to ask Matrix clients to only notify me on messages that are mentioning my username.

Sometimes, however, I'd like to get also get notified when a keyword is used, be that my nickname, or maybe my key project, or some other topic I am interested in.

It would be amazing if Matrix allowed me to register notification preferences similar to IRC's `/hilight` command.

**Comment by turt2live** [comment]
This is already possible: you can define a push rule with the relevant matching. 

fwiw riot-web also has this - just click the literal work 'keywords' in the notification settings to experience the not-so-great UX.

**Comment by madduck** [comment]
Okay, now that is *very* obscure, and also not per-channel, though arguably, you'd want keywords across all channels (except maybe, across communities would make more sense).

**Comment by turt2live** [comment]
That would be a client feature - the spec already supports what you're asking for.
