### ISSUE TITLE
Cloning rooms, or room templates

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-doc#2450]
Setting up a bunch of rooms for a new community, I got bored half way through the second one… configuring the same privacy settings, adding to the same community, navigating the UI to set the name and description, upload a logo (DO NOT FORGET TO HIT SAVE NOW), set an alias, etc. etc..

I wish there was a way to either define a room template for a community, or just simply clone existing rooms, and be asked in one place to amend name, description, logo, and replace the alias.

Bonus points for migrating integrations!

Thanks for your consideration.

**Comment by turt2live** [comment]
This would be a feature of the client as the spec already supports ways of getting the room state of a room and sending it over to `/createRoom`.
