### ISSUE TITLE
Spec is unclear whether send_join state response should be deduped

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/matrix-doc#2464]
The [Federation API spec](https://matrix.org/docs/spec/server_server/r0.1.3#put-matrix-federation-v1-send-join-roomid-eventid) is unclear about whether a `state` key in the response to a `PUT /_matrix/federation/v1/send_join/{roomId}/{eventId}` can legally contain duplicate state-key tuples (for state resolution by the receiver), or whether it should be strictly resolved state with no duplicate state-key tuples.

**Comment by richvdh** [comment]
for the record: it should be the resolved state at (before? after?) the join event. The joining server lacks the information to do a state res.
