### ISSUE TITLE
Spec is unclear whether ver parameter for make_join should be stable or all versions

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/matrix-doc#2466]
For `GET /_matrix/federation/v1/make_join/{roomId}/{userId}`, the [SS spec](https://matrix.org/docs/spec/server_server/r0.1.3#get-matrix-federation-v1-make-join-roomid-userid) states that `ver` should contain:

> The room versions the sending server has support for. Defaults to `[1]`.

... but it is not clear whether this should be only room versions that are marked as `stable` on a given homeserver (e.g. like in a CS API `GET /_matrix/client/r0/capabilities` response) or if this should typically include all room versions, both stable and unstable.

**Comment by richvdh** [comment]
it's all the versions the sending server has support for.... I think that's pretty clear?

**Comment by turt2live** [comment]
Yea, stability has nothing to do with this.
