### ISSUE TITLE
Potential missing `knock` variant in /rooms/.../members endpoint?

### ISSUE THREAD

**Issue by NerdyPepper** [matrix-org/matrix-doc#2476]
Relevant API endpoint:  
https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-members

`membership` and `not_membership` query parameters may be one of four variants:
 - join
 - invite
 - leave
 - ban

should this perhaps be modified to include the "knock" variant as well?

**Comment by turt2live** [comment]
Knock is a reserved keyword and has no meaning: https://github.com/matrix-org/matrix-doc/issues/932

**Comment by jplatte** [comment]
Sure, but several parts of the spec already mention it, why not this one? Is it not supposed to be added there if it's added elsewhere?

**Comment by turt2live** [comment]
Because it wasn't included in the MSC which added the parameters, and it also isn't a valid membership state right now. In future when `knock` has meaning it'd be added here too.
