### ISSUE TITLE
iv parameter inconsistency in sending-encrypted-attachments

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/matrix-doc#2483]
There is an inconsistency in https://matrix.org/docs/spec/client_server/r0.6.0#sending-encrypted-attachments. The text specifies the Initialization Vector (IV) to be 64-bit and the unique counter block to be 128-bit. The iv parameter is definied as "The Initialisation Vector used by AES-CTR, encoded as unpadded base64", so it should be 64-bit, excluding the counter. In the example, "iv" is "w+sE15fzSc0AAAAAAAAAAA" or "U+k7PfwLr6UAAAAAAAAAAA". So, in the example, the iv parameter contains the 128-bit unique counter block and not the 64-bit Initialization Vector.

Riot expects "iv" to be the 128-bit unique counter block (source: https://gitlab.com/famedly/famedlysdk/-/issues/63).

#1420 even mentions this about the iv parameter:
> it contains the counter block (iv concatenated with counter)

It may be difficult to change the parameter name or its actual values (to 64 bit), because this would be a breaking change. However, the definition in the spec can be corrected easily. Instead of "The Initialisation Vector used by AES-CTR, encoded as unpadded base64", the definition should be "The unique counter block used by AES-CTR, encoded as unpadded base64".

The description of #1420 proposes to change the iv parameter to 64 bit. A sentence like "Implementations should accept 64 bit Initialization Vector in the iv parameter." could be added to make this change possible somewhen in the future.

**Comment by uhoreg** [comment]
For extra clarity, maybe "The initial 128-bit unique counter block, formed by concatenating the 64-bit random initialization vector with the 64-bit initial counter value of 0."

> The description of #1420 proposes to change the iv parameter to 64 bit. A sentence like "Implementations should accept 64 bit Initialization Vector in the iv parameter." could be added to make this change possible somewhen in the future.

Personally, I think it's more likely that we'd move things towards making it similar to https://matrix.org/docs/spec/client_server/r0.6.0#key-exports and not require that the counter start at zero.

**Comment by lukaslihotzki** [comment]
There are some reasons for keeping 64-bit IV: Having the counter-part set to zero may enable the use of some exotic crypto accelerators. For example, those supporting AES-GCM (but not CTR) like [EdgeHTML](https://caniuse.com/#feat=mdn-api_subtlecrypto_encrypt) can be abused for encrypt and decrypt according to this spec. Crypto acceleration is especially useful for files because they are relatively large commonly. On the other hand, 127-bit randomness counter provides no practical security benefit with one-time keys afaik.

Implementations accepting 64-bit IV would not prevent introducing 127-bit randomness counters. Riot Android does already accept 64-bit IV, and I have patched libs for [iOS (untested)](https://github.com/lukaslihotzki/matrix-ios-sdk) and [Web](https://github.com/lukaslihotzki/browser-encrypt-attachment).

However, if the spec bug is resolved just by enforcing the iv parameter to be the 128-bit unique counter block, that would be great too.
