### ISSUE TITLE
PDU definitions and appendix section about canonical JSON disagree on maximum integer value

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-doc#2485]
[The section about canonical JSON](https://matrix.org/docs/spec/appendices#canonical-json) states:

> Numbers in the JSON must be integers in the range `[-(2**53)+1, (2**53)-1]`.

The PDU definitons on the [room version v1](https://matrix.org/docs/spec/rooms/v1#persistent-data-unit-schema), [v3](https://matrix.org/docs/spec/rooms/v3#persistent-data-unit-schema) and [v4 page](https://matrix.org/docs/spec/rooms/v4#persistent-data-unit-schema) all say this about the `depth` field:

> Must be less than the maximum value for an integer (2^63 - 1).

Should the PDU definitions be updated or are they supposed to support a wider range of values than all the other integers in the spec?

**Comment by richvdh** [comment]
ideally, the pdu definitions should be updated. but there's a wider problem in that synapse doesn't correctly enforce the ranges specified by canonicaljson. see: https://github.com/matrix-org/matrix-doc/issues/1646

**Comment by turt2live** [comment]
This has now taken the shape of https://github.com/matrix-org/matrix-doc/pull/2540
