### ISSUE TITLE
`/preview_url` response format isn't fully documented

### ISSUE THREAD

**Issue by krkk** [matrix-org/matrix-doc#2489]
It has documented only `matrix:image:size` and `og:image` what is not true because the example shows that there's also `og:title`, `og:description`, `og:image:height`, and `og:image:width`.

https://github.com/matrix-org/matrix-doc/blob/78a0843758b3afa0251fc1fbae10061c01bcc7a5/api/client-server/content-repo.yaml#L379-L400

**Comment by turt2live** [comment]
This is intentional, you're meant to go look at the OpenGraph spec.

> The OpenGraph data for the URL [...] The differences from the OpenGraph protocol are described here.
