### ISSUE TITLE
MSC1946 example for storing backup key is confusing

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix-doc#2490]
In MSC1946, [it says](https://github.com/matrix-org/matrix-doc/pull/1946/files#diff-2a4bb463c1a2f8464cd2d99e2876c7a4R68) "For example, decryption keys for
key backups could be stored under the type `m.megolm_backup.v1.recovery_key`". This is just an example for how 4S _could_ be used, and in reality it differs from the _real_ value to use for this case.

[MSC1219](https://github.com/matrix-org/matrix-doc/blob/ce286dac02ca79e505592df58a658a63408497ff/proposals/1219-storing-megolm-keys-serverside.md#encoding-the-recovery-key-for-server-side-storage-via-msc1946) for the actual key backup feature states you should use `m.megolm_backup.v1` with 4S for this.

It might be easier to follow if MSC1946 were tweaked to use an entirely contrived example instead of key backup keys using an example ID that doesn't match the final one. Or alternately, adjusting the example to match the final value would also reduce confusion.

**Comment by turt2live** [comment]
@jryans it's best to leave these comments on the MSCs so they can be clarified at spec-writing time.
