### ISSUE TITLE
Clarify events that MUST be created on /createRoom

### ISSUE THREAD

**Issue by njouanin** [matrix-org/matrix-doc#2494]
Client specs (currently 0.6.0) specifies events (and their order) that must be created on /createRoom call. This includes `m.room.create`, `m.room.power_levels`. It seems that the `m.room.member` (with state `join`) is not listed in this list. May be it should in order to tell that the room creator has joined the room.
[This excellent article](https://matrix.uhoreg.ca/stateres/reloaded.html) gives an example where `m.room.member` exists as the second event created in the room.
Could you clarify mandatory events list.

**Comment by turt2live** [comment]
The membership event is implied because the spec requires that the room be kept valid. In order to send certain events, you must be a member of the room.
