### ISSUE TITLE
CS API says that avatar_url and displayname are added to m.room.member by the homeserver

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2496]
in https://matrix.org/docs/spec/client_server/r0.6.0#m-room-member it says 'The avatar URL for this user, if any. This is added by the homeserver.'. Surely this isn't true, given you can set per-room nicks etc?

**Comment by turt2live** [comment]
as discussed somewhere, this is technically correct because per-room profiles aren't a thing in the spec. We don't need to overcomplicate the spec with "This is added by the homeserver" though.
