### ISSUE TITLE
do not require password to add email address

### ISSUE THREAD

**Issue by squidink7** [matrix-org/matrix-doc#2505]
Right now, if a user forgets their password and does not have an email address attached, there is no way to reset it, or even close the account. It will remain unusable and the username will not be able to be used by anyone else ever again. This could be easily fixed if Matrix did not require the password to be entered when adding an email address on an already existing session.

**Comment by uhoreg** [comment]
Requiring a password is done on purpose to prevent account hijacking.  If a password is not required, then an adversary who has momentary access to a logged-in client could add an email address and reset the password, allowing them to take over the account.

If a user needs to regain access to their account legitimately, their best bet is to contact their homeserver admin.
