### ISSUE TITLE
status of encryption in telephony and video calls

### ISSUE THREAD

**Issue by aktivkohle** [matrix-org/matrix-doc#2515]
In this [this document](https://matrix.org/blog/2016/11/21/matrixs-olm-end-to-end-encryption-security-assessment-released-and-implemented-cross-platform-on-riot-at-last) from 2016 I read:

> Riot with some major limitations (no encrypted attachments; no encrypted VoIP signalling; no history sharing to new devices).

and

>  Obviously we don't recommend using the E2E for anything mission critical requiring 100% guaranteed privacy whilst we're still in beta

Then in the [current FAQ](https://matrix.org/faq#voip) it says:

> Are VoIP calls encrypted? WebRTC encrypts the media that's being sent. The signalling events that set up (and end) the call are encrypted if the room they were sent in has enabled encryption.

What is the current status of encryption of telephony and video calling over matrix in general and riot on different platforms? Is riot still the client you would recommend for that?

**Comment by uhoreg** [comment]
The FAQ is more up to date than the 2016 blog post, so if they disagree, then the FAQ is correct.

Currently Riot is the only Matrix client that supports VoIP.

In the future, please ask questions in #e2e:matrix.org rather than in here.
