### ISSUE TITLE
Use CommonMark in description fileds

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix-doc#2521]
Swagger (aka OpenAPI 2) stipulates that `description` uses GFM for rich text; and OpenAPI 3 settles down on CommonMark. Matrix API descriptions use ReStructuredText because of the tooling; however, this surprises the original Swagger tooling (used, e.g., to produce https://matrix.org/docs/api/client-server/, AFAICT - see the description for `one_time_keys` in [uploadKeys slot](https://matrix.org/docs/api/client-server/#!/End45to45end32encryption/uploadKeys)).

I don't think it's even possible (and reasonable) to remake the whole documentation in Markdown (RST is more expressive). The other option is to add Markdown support in Matrix.org tooling - either by prerendering pieces of Markdown to HTML and then embedding them in Jinja templates with `::raw html`, or imbue the used Jinja engine with Markdown support (a quick search returns a few projects; I have no idea about feasibility or stability of them). Or, well, lobby/upstream RST support in OpenAPI but that would take years and a release of OpenAPI 3.1 or 4.

**Comment by turt2live** [comment]
(warts are reserved for the protocol bits - we don't have labels for dealing with tooling triage beyond 'tools' because they're all bugs)

**Comment by afranke** [comment]
The spec was moved to Markdown as part of the website redesign. It can be seen working as intended in [the playground](https://matrix.org/docs/api/client-server/#overview). Feel free to reopen if there is any leftover work.
