### ISSUE TITLE
SRV records and resolving server names for delegated servers

### ISSUE THREAD

**Issue by MrJoe** [matrix-org/matrix-doc#2533]
Summarized: To me it looks like the specs for server delegation is wrong to use the Host: <hostname> as http header instead of using the delegated hostname as retrieved by the SRV records. I would suggest to use the 'correct' host name, in other words Host: <the hostname returned from the SRV record>

If I am not mistaken this is what the specs for Resolving server names says when using SRV dns records, lets assume we want to delegate example.org to matrix.example.com. 
Where example.org is running at 198.51.100.1 and matrix.example.com is at 203.0.113.1

Lookup the SRV record `_matrix._tcp.example.org`. The SRV record might contain the value `0 0 443 matrix.example.com`.

To me now there weird stuff happens: It will make an http request to the IP of matrix.example.com 203.0.113.1 with as Host header: example.org eg:
```
GET /_matrix/federation/v1/version HTTP/1.1
Host: example.org
```

However there might be a real possibility that 203.0.113.1 is not running example.org at all, and even worse (or better) it might not have the corresponding certificate for example.org because of security reasons it only has a certificate for matrix.example.com, actually I would assume that to be very normal and hopefully even a best practice.

Other srv records like for example _caldavs._tcp. and _submission._tcp or _xmpp-server._tcp al will use the certificate of the 'resolved' hostname. So the me it looks like the matrix specifications are doing something completely opposite to what to me seems normal.

I am aware there is the option to use `https://<hostname>/.well-known/matrix/server` however that option might not always be available, for instance if you don't or don't _want_ to control the url / site running at the main domain.

**Comment by uhoreg** [comment]
DNS records are not secure, so an attacker could point `SRV _matrix._tcp.example.org` to `evilhax0r.com`.  By requiring that the certificate in this case matches `example.org` we ensure that the target server has been authorized (or at least make it harder for an attacker to spoof).

This has been discussed previously (see, e.g. https://github.com/matrix-org/matrix-doc/pull/1708/files#diff-8d4fae5db100d485c237cab1206908daR170-R191 )

Also to note, we are doing the same thing as at least XMPP.  From https://wiki.xmpp.org/web/Securing_XMPP,

> Let's say you run an XMPP service for `example.net` (jids of user@example.net), you will need to order a certificate for with a subject or alt-name of `example.net` (not `server.example.net`) from your preferred cert provider.
