### ISSUE TITLE
New event type for bridges to indicate propagation

### ISSUE THREAD

**Issue by eternaleye** [matrix-org/matrix-doc#2535]
One recurring issue with bridges (particularly the IRC bridge) is that it can be unclear whether a message has made it across - and if it has, precisely what came out the other end.

It might be beneficial to introduce a new event type indicating that an event has been externally propagated, and what exactly the content propagated was.

If this uses the same machinery as reactions/edits, clients could present this as a tiny flair or similar, which the user could interact with to inspect what the bridge did with the message.

**Comment by turt2live** [comment]
This would largely be a conversation for https://github.com/matrix-org/matrix-doc/pull/2162
