### ISSUE TITLE
Overuse of OpenAPI's primitive types make reading the spec hard

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2551]
For instance on this:

![image](https://user-images.githubusercontent.com/1294269/82122807-a3a67700-978d-11ea-934a-5fb45a077d2b.png)

Rather than saying `{string: { string: string}}` why don't we actually name the types for what they are? `{ user_id [String]: { algorithm [String]: device_id [String] }` or whatever.

**Comment by uhoreg** [comment]
see also https://github.com/matrix-org/matrix-doc/issues/2514

**Comment by KitsuneRal** [comment]
I believe it's a dup of #2514: there are not too many other instances where a map of maps is stuffed in a single table row.

**Comment by turt2live** [comment]
Yea, let's count it as a duplicate.
