### ISSUE TITLE
one_time_keys section of /_matrix/client/r0/keys/upload is not properly specced

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2552]
We've specced `device_keys` nicely, but the `one_time_keys` param is pretty woolly in terms of typing:

<img width="981" alt="Screenshot 2020-05-16 at 15 58 36" src="https://user-images.githubusercontent.com/1294269/82122913-5aa2f280-978e-11ea-9db8-49c0e21882c7.png">

It says the format is determined by the [key algorithm](https://matrix.org/docs/spec/client_server/r0.6.0#key-algorithms), but in practice this gives us an example of:

```json
{
  "key":"06UzBknVHFMwgi7AVloY7ylC+xhOhEX4PkNge14Grl8",
  "signatures": {
    "@user:example.com": {
      "ed25519:EGURVBUNJP": "YbJva03ihSj5mPk+CHMJKUKlCXCPFXjXOK6VqBnN9nA2evksQcTGn6hwQfrgRHIDDXO2le49x7jnWJHMJrJoBQ"
    }
  }
}
```

...without really saying how the signature is calculated.  Is it over `{ "key":"06UzBknVHFMwgi7AVloY7ylC+xhOhEX4PkNge14Grl8" }` or just `"06UzBknVHFMwgi7AVloY7ylC+xhOhEX4PkNge14Grl8"`?

It feels like some additional OpenAPI typing could help a lot here - like we have DeviceKeys for the device_keys param.

**Comment by uhoreg** [comment]
https://matrix.org/docs/spec/client_server/r0.6.0#key-algorithms does say that it's a signed JSON, so the signature is over the entire object.  Though the wording could be clarified a bit.
