### ISSUE TITLE
Is Matrix serverless protocol?

### ISSUE THREAD

**Issue by jbrepogmailcom** [matrix-org/matrix-doc#2556]
In Wikipedia it is written that Matrix runs without central server. From documentation I understand that at least name server (synapse) is required. Can you please clarify? Can Matrix run between two users from beginning to end without server, if users exchange their public keys? Thank you.

**Comment by t3chguy** [comment]
Matrix is a federated protocol. Like email. Users communicate regardless of what server they use.

**Comment by jbrepogmailcom** [comment]
OK I understand, so **at least one server is required**.

**Comment by t3chguy** [comment]
Sure, nothing stops that server being in the client itself, p2p style. E.g https://p2p.riot.im
