### ISSUE TITLE
Session name privacy

### ISSUE THREAD

**Issue by foresto** [matrix-org/matrix-doc#2580]
I'm not sure this is the right tracker for my feature suggestion, but here goes:

When we name our devices/sessions, we tend to choose names that are easily recognizable to ourselves, and sometimes to our friends. Examples include names like "Alice's Laptop", "Netflix Office", or "Amsterdam iPhone". These reveal information about our real-world identities, family member names, employers, our whereabouts, and the kind of hardware we use. It's not a problem among friends, but this kind of information can be abused.

It took me months of using Matrix before I realized a problem here: My session names, along with the information they reveal, have been made available for harvesting by anyone who has ever shared a public room with me. They are also easily associated with my accounts on unrelated services, if I happen to have chosen an uncommon username both on Matrix and elsewhere. Moreover, the visibility of this info (and its related drawbacks) was not obvious to me when I was given the option to name my sessions.

Would it not make sense to mitigate this information leak somehow? Perhaps withhold custom session names from public rooms? Perhaps there is a better approach?

**Comment by turt2live** [comment]
Private device names would be a thing for https://github.com/matrix-org/matrix-doc/issues/1826
