### ISSUE TITLE
`m.id.thirdparty` should be renamed to `m.id.email`

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#2587]
[In the spec](https://matrix.org/docs/spec/client_server/r0.6.1#third-party-id), we currently have several different types of Identifier dictionaries, used for identifying a user that belongs to a homeserver:

* `m.id.user` for a username/localpart
* `m.id.thirdparty` for email addresses
* `m.id.phone` for phone numbers

It seems that either `m.id.thirdparty` should cover both email addresses and phone numbers, or `m.id.thirdparty` should be renamed to `m.id.email`.

**Comment by uhoreg** [comment]
`m.id.thirdparty` can be used for phone numbers as well, but `m.id.phone` is so that clients don't need to canonicalize the phone numbers.  Under `m.id.phone`, it says:

> If the client wishes to canonicalise the phone number, then it can use the `m.id.thirdparty` identifier type with a `medium` of `msisdn` instead.

**Comment by anoadragon453** [comment]
Aha, I missed that. Very interesting. I may stick a phone number example in the spec just to make things clearer.

Thanks for the clarification :)
