### ISSUE TITLE
Email Registration always fails

### ISSUE THREAD

**Issue by Wangmmx** [matrix-org/matrix-doc#2588]
can't register in Riot with matrix.web3.foundation

![image](https://user-images.githubusercontent.com/22836587/83223711-32fc5300-a1ae-11ea-88af-9ce861dc04f9.png)

email: wangmmx0725@163.com
 what's your email domain whitelist/blacklist choices? please tell me the correct email

**Comment by turt2live** [comment]
The error message is fairly clear. Contact the server administrator, as this is the wrong repository for issues of this nature.
