### ISSUE TITLE
/presence returns user_id but missing in docs

### ISSUE THREAD

**Issue by devNan0** [matrix-org/matrix-doc#2590]
[GET /_matrix/client/r0/presence/{userId}/status](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-presence-userid-status) also returns `user_id` but is missing in docs.

Example:
```json
{
    "presence": "offline",
    "user_id": "@user:example.com"
}
```

**Comment by Half-Shot** [comment]
Presumably synapse does, in this case it might be synapse not following the spec.

**Comment by turt2live** [comment]
Would this serve a purpose that makes it useful to document? Considering the user ID is in the URL, not sure why you'd want it in the response too.

**Comment by devNan0** [comment]
I think it makes easier when the user_id is in the response. For example when you make async request its quiet useful.

**Comment by turt2live** [comment]
The async request would still have to know the context of which user it requested presence for though.

**Comment by devNan0** [comment]
Of course. But for example in [matrix-nio](https://github.com/poljar/matrix-nio/) the response is handled in a other function than the request was called. The response function dosen´t know the requested `user_id`.

**Comment by turt2live** [comment]
It may be handled elsewhere, but surely the code which calls into the request knows the user ID or can have context on it? Where in matrix-nio does this sort of thing become impossible?

**Comment by devNan0** [comment]
Found a way. :)

**Comment by richvdh** [comment]
this is a synapse bug, not a spec one. https://github.com/matrix-org/synapse/pull/7606 fixes it.
