### ISSUE TITLE
How do you connect a client from c to the matrix server

### ISSUE THREAD

**Issue by stevedanOgochu** [matrix-org/matrix-doc#2598]
I am thinking of using matrix as a signalling server for a webrtc project I am working on. One of the client side is written in c while the other is in server. How to do i connect a client from c to the matrix server just for the intial signalling for the webrtc peer to peer connection. 

Thank you very much, 
Stevedan Ogocohukwu Omodolor

**Comment by turt2live** [comment]
Please ask questions like this in #matrix:matrix.org instead.

**Comment by stevedanOgochu** [comment]
Was not able to get a response there
