### ISSUE TITLE
secret undocumented m.rule.reaction default push rule

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2635]
https://matrix.org/docs/spec/client_server/r0.6.1#default-override-rules is incomplete: there is another rule:

```
    {
        rule_id: global/override/.m.rule.reaction,
        conditions: [
            {
                kind: event_match,
                key: type,
                pattern: m.reaction,
                _id: _reaction,
            }
        ],
        actions: [dont_notify],
    },
```

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-doc/pull/1849/files#r440302095

**Comment by jryans** [comment]
The push rule is tracked in [this separate MSC](https://github.com/matrix-org/matrix-doc/pull/2153), which seems to have been wedged in the state of saying it should be folded into MSC1849.
