### ISSUE TITLE
Unclear on what to do when homeserver private key is lost

### ISSUE THREAD

**Issue by Fidgetcetera** [matrix-org/matrix-doc#2640]
The docs don't really specify, far as I could find, what happens and what you should do if you lose a homeserver's private key.
The admin of my current server had a major outage and had backups of everything except the private key. Currently, they've put its public key into the old signatures list (old_signing_keys) but that may be the improper way to go about things, seeing as invitations to chats now break.

(Also, if this is a Synapse issue more than a documentation issue, let me know, but it seemed pretty solid to put it here.)

**Comment by turt2live** [comment]
This is essentially https://github.com/matrix-org/matrix-doc/issues/831
