### ISSUE TITLE
m.key.verification.accept should not have a 'method' field

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#2651]
probably a copy-and-paste error.  It wasn't in the original MSC, and doesn't really make sense to be there since the method is already determined at that point.

**Comment by Dominaezzz** [comment]
Related https://github.com/matrix-org/matrix-js-sdk/issues/1390 and https://github.com/vector-im/riotX-android/issues/1433 . Seems to be ignored anyway.

If it makes a difference, I think the `method` field can help with polymorphic serialization in strongly typed languages.

**Comment by Dominaezzz** [comment]
Does this mean `m.sas.v1` is going to be the only type of verification ever?

**Comment by uhoreg** [comment]
Currently, `m.sas.v1` is the only method that uses the `m.key.verification.accept` event.  In theory, other methods might in the future, but there are currently no plans for any other methods.  The method is already specified in the `m.key.verification.start` message, so it's not needed in `m.key.verification.accept`, because the `m.key.verification.accept` is already linked to the `m.key.verification.start`.
