### ISSUE TITLE
what is the expected behaviour when setting the actions/enabled on a non-existent rule?

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2655]
What is a server meant to do when you call `PUT /_matrix/client/r0/pushrules/global/underride/rule_i_made_up/enabled` ? Synapse accepts calls to `.../enabled` (storing the enabled flag for any future rule that gets created), but rejects calls to `.../actions`, all of which feels very buggy.

(Synapse even allows you to set the 'enabled' bit on non-existent `.m.rule.*` rules)

**Comment by reivilibre** [comment]
In progress: #2663
