### ISSUE TITLE
Broken links to "Receiving notifications"

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#2656]
Both the `/sync` response spec and the "Receipt" section link to https://matrix.org/docs/spec/client_server/latest#receiving-notifications as the "Receiving notifications" section, but its actual URL is https://matrix.org/docs/spec/client_server/latest#id91 (or `#id81` on `/unstable`).

**Comment by Half-Shot** [comment]
Dupe of #2623
