### ISSUE TITLE
Something in/around the r0.6.1 release broke most of the link references

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2661]
There's a huge number of broken links across all specs for some reason, and they were either broken in the most recent release or the one prior. We used to have these working based off titles automatically, which is why we use them, so it's weird that they no longer function at all.

**Comment by richvdh** [comment]
can you give specific examples? I've not spotted that many, other than https://github.com/matrix-org/matrix-doc/issues/2623

**Comment by turt2live** [comment]
Most of the spec appendices, quite a bit of the client-server API. I don't really have specific examples, just a feeling of it being more horrible than usual to navigate.

It looks as though many of the named anchors are in the table of contents instead of in the actual document?

**Comment by IvoWingelaar** [comment]
@richvdh A specific example can be found [here](https://matrix.org/docs/spec/server_server/r0.1.4#checks-performed-on-receipt-of-a-pdu). The link to `Signing Events` doesn't work.

**Comment by richvdh** [comment]
@IvoWingelaar thanks. That's another case like #2623 where we should use proper RST internal links rather than using the implicit anchor from the section title.

What I don't really understand is why docutils decided to give the "Signing Events" section an autogenerated anchor id rather than the human-readable one.

**Comment by turt2live** [comment]
I am presuming this is fixed with the new platform. If not, new issues are appreciated.
