### ISSUE TITLE
State Events can appear in a Room Event timeline

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2681]
Possibly related: matrix-org/synapse#1597

The `/sync` spec states that the `timeline` property for a joined room holds a `Timeline`, which has an `events` property that contains an array of `Room Event`s. 

However, in practice, that array can also contain `State Event`s, which have an additional `state_key` property, but this is not expressed in the spec.

I'm unsure whether:

1. The spec should say `Room Event | State Event`, or
2. The spec should clarify that a `State Event` can appear anywhere a `Room Event` can, as it is a more specific subtype, or
3. This shouldn't happen at all and purely happens because of the Synapse bug referenced above.

**Comment by turt2live** [comment]
> In addition to the fields of a Room Event, State Events have the following fields.

https://matrix.org/docs/spec/client_server/r0.6.1#state-event-fields

**Comment by joepie91** [comment]
That only defines that State Events build upon the structure of Room Events, not that State Events are therefore automatically valid wherever a Room Event is expected, though.

**Comment by turt2live** [comment]
It's under a heading called "Types of room events", which says they are split into two categories: State events and Message events.

**Comment by turt2live** [comment]
... and a whole bunch of state events are under a section called "Room Events". It should be blatantly obvious.

**Comment by joepie91** [comment]
It isn't, though. If you are looking at it from the perspective of the `sync` section, for example (which is totally separate from the "Types of room events" section, it is not stated anywhere that a State Event can also appear where a Room Event is expected; and the State Event and Room Event types are separately defined there as completely separate types, no reference to the "Types of room events" section either.

If it is indeed true that State Events can be generally considered a more specific subset of Room Events and are therefore always valid where a Room Event is expected, then that can be made clear with only a small added passage, like:

> As a State Event is a more specific type of Room Event, it is valid wherever a Room Event would be accepted.

Adding this wherever State Event and Room Event are defined (which, AFAIK, is just the `/sync` endpoint + the "Types of room events" section), would resolve the ambiguity.

**Comment by IvoWingelaar** [comment]
@joepie91 It is somewhat explicitly mentioned in the CS API section 9.4, under the note and rationale of the `state` list. They give an example in which the `timeline` contains state events that clients should add to the events in the `state` field to determine the current state.

But I understand the confusion, I also originally interpreted the "split into two categories" line, that events where partitioned into two types, with the `state` and `timeline` fields *somewhat* suggesting this.

**Comment by KitsuneRal** [comment]
The description for `timeline` is also quite explicit that this subobject contains messages _and_ state changes.
