### ISSUE TITLE
Duplicate `m.room.redaction` event type specification

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2683]
The following two sections appear to contain identical information:

1. https://matrix.org/docs/spec/client_server/r0.6.1#id40
2. https://matrix.org/docs/spec/client_server/r0.6.1#m-room-redaction

Not sure if these sections are internally sourced from the same documentation source, but the spec size could at least be reduced by hyperlinking from one to the other; from 2 to 1 is probably most logical, centralizing towards a single event type list.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-doc/issues/2171
