### ISSUE TITLE
Unspecced `age_ts` event-level property

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2685]
In some State Events in the `timeline` for a room, an event-level `age_ts` property appears, like so:

```js
{
	"content": {
		"avatar_url": null,
		"displayname": "redacted",
		"membership": "join"
	},
	"origin_server_ts": 1594422179585,
	"sender": "@redacted:example.com",
	"state_key": "@redacted:example.com",
	"type": "m.room.member",
	"age_ts": 1594422183344,
	"unsigned": {
		"age": 2810
	},
	"event_id": "$redacted"
}
```

But this property does not appear anywhere in the spec, and I have no idea what it is meant to signify. #684 does mention it, but only in the context of being stored internally in `unsigned` data, which is not where the property appears in this case.

**Comment by richvdh** [comment]
its existence is essentially a bug in synapse: https://github.com/matrix-org/synapse/issues/8429.
