### ISSUE TITLE
API documentation doesn't seem to render correctly on Safari

### ISSUE THREAD

**Issue by rryan** [matrix-org/matrix-doc#270]
Not sure what's wrong -- but the text seems to be rendered transparently: 

URL: http://matrix.org/docs/api/client-server/
Safari Version 9.0.3 (11601.4.4)
OS X 10.11.3

![screen shot 2016-02-04 at 10 01 22 am 1](https://cloud.githubusercontent.com/assets/26527/12824498/4c8d5f0c-cb26-11e5-80d6-048de6a9d721.png)

**Comment by ara4n** [comment]
the webfont isn't loading for some reason; presumably it's not referencing a format or url that safari can display. @oddvar can you check your jekyll template?

**Comment by rryan** [comment]
Hm, sorry for not digging in a little more -- I played with the CSS a bit and the computed font-weight for the text is "normal" and the font is Droid Sans. The webfont is downloading fine, but I think only weight 700 is available based on this: http://matrix.org/docs/api/client-server/css/typography.css


If I change font-weight to 700 the text shows up.

**Comment by oddvar** [comment]
Hi Ryan, thanks for your help in debugging this. I think I've found the culprit - it works on my local mac/safari setup. Can you check it's working for you as well?

**Comment by Kegsay** [comment]
@rryan ping

**Comment by richvdh** [comment]
Let's assume it's fixed unless we hear otherwise.

**Comment by rryan** [comment]
:+1:, looks good to me now. thanks!
