### ISSUE TITLE
server-server protocol : HTTP and SSL?

### ISSUE THREAD

**Issue by StEvUgnIn** [matrix-org/matrix-doc#2718]
Hi, 
The specification establishes in the diagram that HTTPS is mandatory to connect a homeserver to another:
https://matrix.org/docs/spec/#matrix-apis

A simple reading shows this could be a mistake or the fact that a SSL authenticate certificate was omitted in the specification body. 

Thanks a lot

Link: https://github.com/matrix-org/matrix-doc/blob/master/specification/index.rst#id2

**Comment by richvdh** [comment]
it is correct that matrix federation requires TLS.
