### ISSUE TITLE
Unclear whether redaction power levels also applies to own redactions

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2733]
The powerlevels spec says, for the `redact` key:

> The level required to redact an event. Defaults to 50 if unspecified.

... but does not specify whether this means just redacting *other people's* events, or also one's own events. This is only mentioned in the dedicated Redactions section, which is not linked from the powerlevels documentation.

(FTR: It only applies to someone else's events.)

**Comment by richvdh** [comment]
related: #2172

**Comment by aaronraimist** [comment]
This has been clarified by #2814
