### ISSUE TITLE
Push notification rules should not resolve the matrix host as a username or display name keyword

### ISSUE THREAD

**Issue by wvffle** [matrix-org/matrix-doc#2735]
Push notification rules should not resolve the matrix host as a username or display name keyword. In case where you have an username which is the same as the host and any other user on the same host is replied, you'll be notified of this.

Example: If matrix tag is `@juniorjpdj:juniorjpdj.pl` and when message of `@somebody:juniorjpdj.pl` is replied to, `@juniorjpdj:juniorjpdj.pl` will get the notification due to the host being the same as the username.

Same goes with the display name. If the display name is for example: `wvffle` though the username is `@waff:wvffle.net` and `@somebody:wvffle.net` is replied to, `@waff:wvffle.net` will get a push notification.

I still want to receive the notifications just fine when someone actually pings me, so disabling push notifications for display name or username is not what will resolve my issue.

This is related to https://github.com/vector-im/element-web/issues/14943

**Comment by JuniorJPDJ** [comment]
I think it should resolve matrix host as username, but it shouldn't especially in tags.
When I talk about tags I mean something like this: `<a href='https://matrix.to/#/@juniorjpdj:juniorjpdj.pl'>@juniorjpdj</a>`
Tags should be treated like a whole thing - and if whole tag doesn't match user it shouldn't make him notified.

**Comment by turt2live** [comment]
This is configurable with push rules.

**Comment by JuniorJPDJ** [comment]
We are talking about annoying default approach.

**Comment by JuniorJPDJ** [comment]
This isn't really configurable, as at example I'd like to be notified for @juniorjpdj and for @test:juniorjpdj.pl not and I can't find good enough rule to get both. As far as I understand states for @wvffle.

**Comment by turt2live** [comment]
Turn off notifications for your username, change your display name so it doesn't match, and set up an extra keyword rule to match against `@yourname` so it doesn't pull the domain part.

In general, using your preferred display name as a domain is discouraged for this reason. It's not only a problem for unexpected mentions, but permalinks too. For permalinks it's nearly impossible to tell if the mention was intentional or not.

**Comment by t3chguy** [comment]
> I think it should resolve matrix host as username, but this should be skipped especially in tags.


Push rules never see the tags as they run against the `body` not the `formatted_body`
