### ISSUE TITLE
Login with a phone number

### ISSUE THREAD

**Issue by Rik44444** [matrix-org/matrix-doc#2740]
Hi,
I love Matrix, esp the focus on bridges. I would like to start recommending it to friends and family, but the Element app is really only acceptable to them if it is possible to register and login automatically with their phone number, without a password, and with sms id confirmation. So like with WhatsApp and Signal. This is a feature request to make this possible on Matrix as well, perhaps add it as an option in the login screen. I think it should be feasible (but I'm no expert), to assign randomly generated new user names and passwords to new phone numbers, and allow users to register and login without ever having to see either, so that they can just login with their phone number.

see also here: https://github.com/matrix-org/synapse/issues/8099

**Comment by turt2live** [comment]
The spec supports this sort of approach through guest accounts, user-interactive auth, and some clientside trickery.

**Comment by Rik44444** [comment]
hi, OK, but at the moment it is not possible to login just with your phone nr, right? Or did i miss the option? If so, where would be the right place to raise this request?

**Comment by bmarty** [comment]
Hello @Rik44444 I (and @clokep as said in matrix-org/synapse#8099) that this is the right place to ask for such new authentication type. Feel free to propose a new MSC as per https://github.com/matrix-org/matrix-doc/blob/master/CONTRIBUTING.rst.

**Comment by Rik44444** [comment]
>  Feel free to propose a new MSC as per https://github.com/matrix-org/matrix-doc/blob/master/CONTRIBUTING.rst.

Hi, sorry for the noobness here, but i do not understand. The website you are referring is about contributing to the Matrix documentation right? How does that relate to my feature request for making passwordless logins with phone number possible in the Element app?

**Comment by bmarty** [comment]
Who will send the SMS to confirm that you own the number? The feature you are requiring involves changes also on the server implementation so it has to be discussed at the protocol level.

**Comment by Rik44444** [comment]
Hi @bmarty , I am not sure who will send the SMS, that is up to the people implementing this on the app side. Re changes at server implementation and protocol level: yes, I agree. Where would be the right place to raise a request for those changes?

**Comment by KitsuneRal** [comment]
@Rik44444, as said above, this repo is the right place for the request about a new authentication type (I don't think this functionality can be implemented without introducing some kind of `m.login.sms` auth type in the spec, hence this should be reopened). What he further proposed is that you write a Matrix Spec Change (MSC) proposal in order to change the protocol if you want this change to happen sooner. Just setting expectations: someone else can surely do it too but waiting for that someone to show up may take an indefinite amount of time.

**Comment by turt2live** [comment]
`m.login.password` with a 3pid type to identify the user?

**Comment by KitsuneRal** [comment]
Oh; you're right. I now remember that's even how something similar used to work in the early days of Matrix. Agree that a combination of guest accounts, UIA and arranging the process on the client-side should - not sure any server-side changes are even necessary.

**Comment by Rik44444** [comment]
hi @KitsuneRal , thanks for the explanation - this clarifies a lot, the documentation was just a bit too much for me to understand quickly. Is an MSC proposal something I will be able to write as a relative noob in your opinion? Is it just a feature request according to some guidelines? Or do i need to draw someone in with tech expertise?

**Comment by KitsuneRal** [comment]
@Rik44444 - as I mentioned in the last comment, indeed an MSC is not needed here: it mostly needs changes on the client side (in Element), and (probably but not necessarily) on the server side (in Synapse). Sorry for pushing you around so many times. I think your original ticket (https://github.com/vector-im/element-android/issues/2026) is actually the right place for that, though I'm not entirely sure - not an expert in mobile clients.

**Comment by bmarty** [comment]
Not sure to understand where this issue is going to. I though it was about **creating** an account with a phone number, not login with a phone number.

**Comment by Rik44444** [comment]
> 
> 
> @Rik44444 - as I mentioned in the last comment, indeed an MSC is not needed here: it mostly needs changes on the client side (in Element), and (probably but not necessarily) on the server side (in Synapse). Sorry for pushing you around so many times. I think your original ticket ([vector-im/element-android#2026](https://github.com/vector-im/element-android/issues/2026)) is actually the right place for that, though I'm not entirely sure - not an expert in mobile clients.

hi @KitsuneRal , thanks, sorry i did not understand before from your earlier reply that that meant that an MSC was no longer needed. OK, i will go ahead and re-post in the Element github.

**Comment by Rik44444** [comment]
> 
> 
> Not sure to understand where this issue is going to. I though it was about **creating** an account with a phone number, not login with a phone number.

hi @bmarty , I think it is about both? My request is just as a user to allow people to log into matrix as they do with Signal and Whatsapp and Telegram - with their phone nr. For that I guess creating accounts with phone nrs and logging in with phone nrs are both needed.

**Comment by ilmaisin** [comment]
Matrix indeed might benefit from a counterpart of [Quicksy](https://quicksy.im/). It would reduce the barrier of entry for nontechnical users. Currently, many people will likely either use a weak password or opt to not use Matrix at all.

Is there any appropriate place for this kind of requests?

**Comment by KitsuneRal** [comment]
As discussed above, Matrix as the set of protocols in the current state should be sufficient to enable this. The actual implementation seems to be entirely client-side; so you should request a feature in the repo of the client application you use.

**Comment by SeerLite** [comment]
@KitsuneRal Account creation too? The idea is to be able to register with an SMS code and then login in the same way later, like with Quicksy.

If I understand @bmarty correctly (here[https://github.com/vector-im/element-android/issues/2228#issuecomment-705815349]) this still needs a change in the spec.

Thanks

**Comment by clmnin** [comment]
This need a spec change. Only then can it be implemented at the client side.

1. Client connects to `Phone Auth` provider (eg firebase)
2. Client submits phone number and OTP
3. `Phone Auth` provider responds with `id_token`
4. Client sends id_token to `synapse` which connects to `Phone Auth` to get validate the token
5. `synapse` creates new user with randomly generated user-name

In the above example it is clear both the client and the server has to make changes

**Comment by Rik44444** [comment]
thanks @clmnin this is v helpful. I still think this would be a great addition! Not sure why this topic is closed. Do you think we could request to have it reopened?

**Comment by clmnin** [comment]
@Rik44444 I think it a bit of work and their is no urgent need from the community. We could use a module that would help us work around this for now

Check out - [matrix-synapse-shared-secret-auth](https://github.com/devture/matrix-synapse-shared-secret-auth)

And this small code can auth Phone OTP
```python
@app.post("login")
def login(token: str) -> str:
    decoded_token = authenticate_firebase_token(token)
    uid = decoded_token["uid"]
    user_id = f"@{uid}:example.com"
    
    # get access token from Synapse
    access_token = obtain_access_token(user_id, homeserver_api_url, shared_secret)
    return access_token
```

Or even build a new module that will use an auth provider we assign and authenticate users using OTP.

**Comment by Rik44444** [comment]
hee John,
i didn't really ask for myself :)  i think it would open up a whole new range of users for Matrix (mainstream users) 
thanks for the suggestions though,
Rik

**Comment by bagvand** [comment]
@Rik44444 
@turt2live 
Can we use keycloak by opt enabled for login with phoneNumber?
