### ISSUE TITLE
Add email (or other contact) for room deletion

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/matrix-doc#2750]
Greetings, we want to delete a room, but we do not know where/what to contact to delete a room.

It would be appreciated if you can create a new email (or other contact place) for us to contact you for room deletion

**Comment by turt2live** [comment]
Deleting a room is the responsibility of the homeserver operator. For matrix.org, that is support@matrix.org

**Comment by CipherOps** [comment]
To explain in more detail, as you can see from my profile and contributions I am the owner of Linux Cafe, and TheEvilSkeleton is my right hand in our operations off Discord excluding hosting of services. The former owner Jan created https://matrix.to/#/+unc:matrix.org and we recently discovered it is still alive. 

You can check on our [Reddit](https://reddit.com/r/LinuxCafe) and here on [GitHub](https://github.com/LinuxCafeFederation) and [Gitlab](https://gitlab.com/LinuxCafeFederation) to verify we are who we say we are, and that this is our project now.

Before we were Linux Cafe we were called Discord Linux Fork, and then Unnamed Linux Community (as seen on the [Matrix] group.

Please help us figure out who to contact about removing this community running with our name.

Thank you for your time,
Tyler

**Comment by turt2live** [comment]
> What do we need to say to verify this is our project and the old community needs to be removed?

The support team will ask for any information they require.
