### ISSUE TITLE
Request: Abstract HS Migration Specification

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#2760]
I'm currently looking to host a public matrix homeserver in the future, once dendrite, construct, or conduit has released a stable build.

However, I'm concerned that migrating from a (previous) synapse server, or between any of those three server implementations (if they turn out unstable or unusable in any fashion) will be a lengthy, error-prone, or simply impossible task.

I also see this possibly apply to more than just this one situation, and when in the near future 3 or 4 "robust" homeserver implementations will exist, i think some administrators would like to switch between implementations with relative ease, to not have a "lock-in" effect.

Is it possible to have an "export" and "import" specification of data from any such implementation? To allow the core user data (user devices, sessions, room timelines, tags, etc.) to be importable easily, and only then to have fringe data (configuration data, web client implementation, etc.) be ported manually, but this would allow any homeserver to be "interchangable" easily, to allow a HS to adopt newer, faster, and/or better HS implementations when they come and go.

**Comment by turt2live** [comment]
Something like this would likely be best solved using a form of nomadic identity on the user level, such as proposed by https://github.com/matrix-org/matrix-doc/pull/1228

Other, future, proposals will also be potential avenues for this sort of thing, along the same lines as MSC1228

**Comment by turt2live** [comment]
There's nothing stopping you from setting up a new server with the exact same name and doing the transfer with that.

**Comment by valkum** [comment]
But you are polluting the ServerName space, aren't you? All references (internal and external of matrix) to your servername get invalid as well.
You wold need to switch twice to avoid that problem.


The question boils down to: Do you plan to migrate matrix.org from synapse to dendrite once dendrite is stable? 
If yes: How do you plan to do that? Can we spec that publicly to benefit from it for other HSs as well.

**Comment by turt2live** [comment]
I don't think an issue is the correct way to discuss this - an MSC would be a lot better.

**Comment by ShadowJonathan** [comment]
@turt2live why was this closed? this issue was specifically opened for the idea of in-place server upgrades, and explicitly *not* to have server upgrades happen also laterally through a DNS name update

> I don't think an issue is the correct way to discuss this - an MSC would be a lot better.
i opened this issue for discussion and feedback, not to directly create a MSC from this, as i want to receive constructive criticism on the issue

Could you please re-open the issue?

**Comment by turt2live** [comment]
Things like this are generally best discussed as an MSC, even if listed as work in progress, due to their complexity. A github issue does not lead to constructive conversation on issues such as this.

The idea proposed here is built out enough to warrant a WIP MSC.

**Comment by ShadowJonathan** [comment]
Alright, then i'll look at how i can create one, sorry for the mess

**Comment by turt2live** [comment]
https://matrix.org/docs/spec/proposals has a whole lot of information on the MSC process, but is definitely overkill for this early stage conversation. https://github.com/matrix-org/matrix-doc/pull/2745 is an example of an MSC which proposes a general direction, though the full technical details haven't been worked out yet.
