### ISSUE TITLE
/capabilities keys for disabling the ability to set your own profile data

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#2793]
https://github.com/matrix-org/synapse/pull/7096 added support for disabling setting a displayname/avatar in synapse, but there is no way to communicate this to the client. Ideally this feature should be part of the spec, whereby it is signalled in `/capabilities`

**Comment by turt2live** [comment]
I'm not sure this is a good fit for capabilities. Please open an MSC.

**Comment by Half-Shot** [comment]
The issue is intended for some kind soul to write an MSC :)

**Comment by Half-Shot** [comment]
>I'm not sure this is a good fit for capabilities

https://matrix.org/docs/spec/client_server/r0.6.0#m-change-password-capability exists though :p

**Comment by turt2live** [comment]
that is a capability that exists, and it serves a different purpose. An MSC would be a great place to discuss.

**Comment by dklimpel** [comment]
See also the new MSC: https://github.com/matrix-org/matrix-doc/pull/3279

**Comment by zecakeh** [comment]
This is now part of the spec since v1.2 with [MSC3283](https://github.com/matrix-org/matrix-doc/pull/3283) and #3614.
