### ISSUE TITLE
Why is a room version string length 32 codepoints?

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#2804]
### The Problem
Due to a joke in a watercooler room, I noticed that 32 codepoints for a room version string isn't actually that long.

The proposed (joke) room string `net.maunium.watercooler.v13` was 27 codepoints, hitting the limit, and I thought that would become a problem if room version naming could/would eventually become more elaborate.

What was the original idea behind this limit? Would it be sensible to expand it? (e.g. to 64/128/255)

### Additional context
Quasi-related to #2802, because of potential new interest in more room versions/types.

[Size Limits] defines:

> `type` MUST NOT exceed 255 bytes.

This is similar to the room version scheme, which also follows java package name conventions.

**Comment by richvdh** [comment]
https://docs.google.com/document/d/1urKgReoHqxX8R_XtySB17dPi-DZcKhqTEL2_s895Wz0/edit#heading=h.djuv92tg9d2m:

>  32 codepoints is chosen as a balance between allowing room for experimentation and keeping the length of the make_join query string within reasonable bounds.
