### ISSUE TITLE
Make files findable and searchable

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-doc#2820]
If a file is forwarded from an encrypted room to an unencrypted room, it won't show up in the files list.  It ought to, though.  Also it would be really good to allow searching in the files list.

**Comment by t3chguy** [comment]
The spec issue here actually is that it is impossible to filter by msgtype, and `contains_url` is not sufficient for all usecases.

**Comment by Biep** [comment]
Searching = filtering

**Comment by turt2live** [comment]
Effectively https://github.com/matrix-org/matrix-doc/issues/593
