### ISSUE TITLE
Rendering HTTP APIs

### ISSUE THREAD

**Issue by wbamberg** [matrix-org/matrix-doc#2831]
(This is part of https://github.com/matrix-org/matrix-doc/issues/2822)

If we're to move the spec into a new platform we need replacements for all the things the current templating engine takes care of. One of the biggest pieces here is the way HTTP APIs get rendered from the OpenAPI specifications.

I've implemented a first version of this for feedback, and it's deployed to https://adoring-einstein-5ea514.netlify.app/spec/client-server/ (at the time of writing only for `login` (https://adoring-einstein-5ea514.netlify.app/spec/client-server/#login) but I'll keep adding more).

Not everything is implemented at the moment: in particular, examples aren't rendered and enums are not enumerated. There are probably some other bugs too.

I've filed this issue to explain some of the choice I've made and collect feedback.

## Architecture choices

Turning the OpenAPI into the rendered HTML is a bit involved: the current templating engine spends several hundred lines of Python on it, and Hugo templates seem to be a bit limited in their power.

I can think of a few options here:

1. change the authoring format used for the HTTP APIs into one more friendly to the renderer. I don't think we want to do this, because using a standard format has all kinds of benefits.

2. learn of new powers Hugo templates have, that I was unaware of. Such as the ability to define new functions they can call. This would be great, except that as far as I know they don't exist.

3. use a different SSG that has more powerful templates. This might end up being a good choice, but it would come with its own tradeoffs.

4. write a Python script (or adapt the existing one) to preprocess the OpenAPI specs into something Hugo-friendly. This is OK, but not as clean as just running "hugo serve".

For the time being I've chosen (4), because it seems reasonable and is the quickest way forward.

## Style choices

We also have to choose how to style the HTTP APIs in the spec. For a first attempt, I have leaned a bit on the representation used by SwaggerUI: https://petstore.swagger.io/:

* I've used the same colors (including the background color)
* I've used a [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element

I think having a background is nice here, as it indicates that this section is its own thing in the context of the spec. In the current spec the HTTP API spec bleeds into the main page, and it's not always obvious where it starts or stops.

But I'm very open to alternatives and would be happy to hear from a real designer here.

## Structure choices

We also have to decide how to structure the information. In general I've tried to present the same information as we have now, but I've reorganized it a bit.

In this first attempt I've adopted a structure like:

```
# Title: Method + Endpoint + Summary

# Description

# Requires auth/rate-limited table

# Request parameters (if any)

    ## Body parameters (if any)

    ## Path parameters (if any)

    ## etc

# Responses

    ## Summary response table

    ## 200 response details (if any)

    ## 403 response details (if any)

    ## etc

# Additional types (if any)

    ## Additional type 1

    ## etc
```

**Comment by ara4n** [comment]
@nadonomy can we please cheekily steal some designer time to look at this at some point?

**Comment by nadonomy** [comment]
Yup for sure, I think I actually have some relevant comps in Sketch already from when we re-designed matrix.org (last year?) when we moved from the old WordPress to the current implementation.

@wbamberg I'm lacking some context around related issues, so might be easiest if we chat on Matrix to back/forth a little there first and figure out a plan of attack. Feel free to ping me!

**Comment by richvdh** [comment]
we have a starting point here - I'm not sure it's perfect, but let's track further changes in more targetted issues.
