### ISSUE TITLE
Append-only rooms

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-doc#2833]
**Is your feature request related to a problem? Please describe.**
High-latency networks are commonly found and they are going to be more common in interplanetary communication scenarios, which is inevitable in a decentralised protocol.

**Describe the solution you'd like**
A new room property called `appendonly`, which will only be allowed to be set during room creation. When `true`, participants will not be able to edit or delete messages and/or change privileges of any user of a room other than themselves, or kick/ban any user. This flag will not be modifiable after room creation.

**Comment by turt2live** [comment]
How is this different from Matrix today, which is already append-only by nature?

**Comment by erkinalp** [comment]
It makes the content append only, not the protocol, which is already append-only.

**Comment by turt2live** [comment]
I'm still failing to understand. The room is append only still. Sure, there's features which allow you to replace content in individual messages, however there's no requirement for that to actually happen - a client could easily render an edit as the IRC-style "* oops".

**Comment by uhoreg** [comment]
Rooms are already append-only, and disallowing kicks/bans/permission changes seems like a bad idea.  Closing this issue.
