### ISSUE TITLE
Spec authoring with Hugo

### ISSUE THREAD

**Issue by wbamberg** [matrix-org/matrix-doc#2838]
(This is part of https://github.com/matrix-org/matrix-doc/issues/2822)

I'd like us to decide on a sensible way to author the specification in Hugo-land.

At the most basic level Hugo expects site content to be kept in the /content directory, and individual files in there to correspond 1-1 with the web pages that get generated. So in the simplest world, when people edit the spec they just edit files in /content, that correspond 1-1 with web pages.

## The current (pre-Hugo) spec platform

In the current spec platform, content as-authored is transformed into web pages in a couple of ways:

1. **data is transformed using templates**: some content (in particular but not exclusively HTTP APIs) is represented as data, not just prose, and this gets transformed using the Batesian templating engine.

2. **prose content is reorganised**: some prose content does not correspond 1-1 with web pages. Instead, gendoc.py assembles pages out of various pieces. This sometimes necessitates rewriting the section heading levels.
    * the client-server spec is assembled from the main doc and 30 or so individual .rst files documenting the different modules
    * the "appendices" page is assembled out of a collection of .rst files, one per appendix

How do we want this all to work in Hugo-land?

## Dealing with data

As far as (1) is concerned, we can use Hugo templates to render HTTP API documentation from the YAML. There are a couple of wrinkles here, neither of which seem fatal:

* Hugo's ToC implementation doesn't include headings that were generated by templates (https://discourse.gohugo.io/t/shortcode-processing-order/16554). It looks like this might eventually get fixed. I think this is OK for this kind of content.

* Hugo's templating language is kind of awkward, so for now I've conceded that we will have a preprocessing step that mashes the Swagger data into a format that's easier for templates to consume. I'd much rather not do this and still hope that we'll be able to write sophisticated enough templates that will be able to consume the Swagger data as-authored.

## Dealing with prose content

As far as (2) is concerned, we have a couple of options:

1. **stop reorganising prose content**: just author prose as MD files in /content, and have as-authored files correspond 1-1 with web pages. In practice this seems to mean:
* author the appendices page as a single MD file. This seems reasonable to me.
* author the client-server spec as a single MD file including all modules OR represent each module as a separate page. Both options have drawbacks: the first makes the source document for client-server (even more) huge and cumbersome to edit. The second means we will have many more pages, which makes our site nav much bigger. This will break our current layout, which essentially that the site nav is tiny (because it fits both site nav and ToC in a single column).

2. **preprocess prose content**: this means, again, having some code that glues together the modules and so on, before Hugo runs. Although the gluing code is easy, it adds complexity in terms of deciding when this glue code should run, and breaks the appealing directness of Hugo.

My preference here would be to choose (1), and to author the client-server spec and modules as a single file.

**Comment by ara4n** [comment]
how big actually is the CS spec + modules if considered as a single file?  I've been a bit torn on having it broken up into nice bitesized chunks versus never quite remembering how the chunks are glued together, and could probably get behind it being one big doc - but @turt2live may well have Thoughts on this.

**Comment by turt2live** [comment]
Breaking it out into modules is slightly better writing-wise, if only for a keyword search across the whole project while writing - because the files would have names, like they currently do, it makes narrowing down results a bit easier. An example of this is trying to find the `/requestToken` endpoint on registration - sometimes it's easier to mash shortcuts to find the file instead of remembering that it's `registration.yaml` (or whatever).

With a large single document this wouldn't be the end of the world, but would wear down the experience over time of having to find things.

I'd be fairly okay with losing the giant single page document and splitting the modules out sensibly to their own 1:1 pages. Might even help loading time for the spec.

**Comment by wbamberg** [comment]
What would be your overall preference:

1. **author the client-server spec as multiple MD files, and have a preprocessor glue them together into a single web page**. (consequence: have to write the preprocessor and decide how and when to run it, breaks the simplicity of Hugo authoring)
2. **author the client-server spec as multiple MD files, and present them as multiple web pages**. (consequence: breaks the current layout we have with site nav and ToC sharing the LHS columns)
3. **author the client-server spec as a single MD file, and present it as a single web page**. (consequence: huge source file is hard to author)

> how big actually is the CS spec + modules if considered as a single file? 

The MD file I have currently rendering is 4306 lines (https://raw.githubusercontent.com/wbamberg/matrix-hugo/main/content/en/spec/client-server.md). This breaks down into about 2000 lines of not-modules and about 2300 lines of modules.

Annoyingly, if it weren't for the [ToC problem](https://discourse.gohugo.io/t/shortcode-processing-order/16554) it would be easy to glue the pieces together using a template. But headings in the content that the template inserted would not be included in the ToC :(. So yet another option is to abandon the generated ToC and generate our own using client-side JS, which [some other people have done](https://discourse.gohugo.io/t/create-a-custom-page-toc-mini-toc-with-javascript/16665).

**Comment by turt2live** [comment]
personally speaking, 2 then 1 then 3 in that order.

**Comment by wbamberg** [comment]
I'm going to propose that we should choose (3) at least for the time being (Sorry Travis).

It seems there's a lot of attachment to rendering the client-server spec as a single page, but I haven't seen a lot of reasoned justification for then authoring it as multiple pages.

**Comment by turt2live** [comment]
It's a bit hard to justify why the multiple files are so nice for authoring, but the overarching principles are easier search, logical structures for potential contributions, and not having to use in-file navigation tools which IDEs typically have poor support for. Most of the time you'll end up scrolling up and down and memorizing line numbers to be able to jump to them if authoring was a single file - instead, when using multiple files, tab workflows can be used to keep track of where everything is going and what it looks like.

We'd probably need a preprocessor anyways for the swagger/Open API stuff - we can just extend it to also gluing the files together. The single page presentation is seemingly important for us, so option 1 from above would be preferable even if slightly more ugly looking. Alternative tooling, like [Cuttlebelle](https://cuttlebelle.com/) (which is not my favourite answer, but it works well enough for these sorts of things) might be more worthwhile.

On Cuttlebelle, it's not a super serious suggestion from me - I happen to have experience using it and it's fairly quick at doing what it does. It has live reload capabilities, layout options, implicit abilities to glue pages together, and does incremental builds for development. It might be something to look at, though I am certain there is a better tool out there.

**Comment by ara4n** [comment]
I totally missed the comments here - sorry :(

My pref would option 1 + 2: that we author as multiple MD files, and then template them into both a single web page and ideally multiple pages too (a bit like classic unix documentation generated from TeX often comes in both one-big-HTML-page and one-page-per-chapter form factors - e.g. GDB has the page-per-chapter view https://sourceware.org/gdb/current/onlinedocs/gdb/ and then the one-big-page in HTML/PDF/DVI at https://sourceware.org/gdb/current/onlinedocs/).

The rationale is as follows:
 * Multiple files for authoring has the advantage of:
    * We stand some chance of preserving history with the current files, which are one file per section aiui
    * We can jump around between tabs easily, keeping position in the respective tabs
    * History is tracked on a per-file granularity, making changelogs much easier to navigate
    * Searching for content is just shift-cmd/ctrl-F or similar across multiple files, so no advantage to all being in one page.
    * I'm about 6-7/10 in strength of feeling on having multiple files for authoring fwiw.
 * One-big-page output has the advantage of:
   * Ctrl-F on a single page to find a search term, without having to indirect via a google/glimpse style web search.  I cannot overstate that this is the primary way I navigate the spec today - I open the spec page, and hit ctrl-F and start typing the API or param or field name to find out about it.  I suspect many other people do too, and would be sad to lose it.
   * We can avoid breaking links and permalinks to the existing monolithic spec pages.

However, I totally agree that the massive page is indigestible and scary to newbies, and by default it would be best to show a chapter-per-page view (4-5 out of 10 strength of feeling).  For powerusers though I'd really like to avoid regressing from also providing the single-big-page that we have today though (and this is a 8-9 out of 10 strength of feeling).

I think I'm a bit confused though, because I thought the earlier preview where everything was on one big page (with the ToC on the LHS underneath the main indexes) looked really great - I'd have been happy to ship it as is, as a first cut (as I think/hope i said on matrix).

How did we end up going into page-per-chapter sections?

**Comment by wbamberg** [comment]
> I think I'm a bit confused though, because I thought the earlier preview where everything was on one big page (with the ToC on the LHS underneath the main indexes) looked really great - I'd have been happy to ship it as is, as a first cut (as I think/hope i said on matrix).
>
> How did we end up going into page-per-chapter sections?

In the preview, specs were authored as a single file: that is, there was a 1-1 mapping between authored files and rendered web pages. So no need for preprocessing. I filed this issue to decide whether that's an acceptable option. The first feedback I got was that multiple files->multiple web pages (option 2 in https://github.com/matrix-org/matrix-doc/issues/2838#issuecomment-718965812) was preferred, so I tried that out.

But now it looks like that isn't an acceptable option, and we want multiple files-> one web page (option 1).

> It's a bit hard to justify why the multiple files are so nice for authoring, but the overarching principles are easier search, logical structures for potential contributions, and not having to use in-file navigation tools which IDEs typically have poor support for. 

It seems to me that many of these considerations also apply to the rendered pages :). But I'm not going to keep beating this particular horse.

So if we want this asymmetry between authored files and rendered files, we have to ask whether that's possible in the context of the SSG we are using, or whether it has to be some separate preprocessing step.

I'm not that familiar with Hugo, but it seems to me that although it's simple to glue files together using a template we are stymied by Hugo's ToC implementation, which doesn't pick up headings added by templates (https://discourse.gohugo.io/t/shortcode-processing-order/16554). So we could get around this in one of three ways:

1. implement the ToC outside Hugo (using client-side JS, say)
2. add a custom preprocessing step  outside Hugo, which glues the files together
3. use something else

I'd really like to avoid (2). With respect to:

> We'd probably need a preprocessor anyways for the swagger/Open API stuff - we can just extend it to also gluing the files together.

If we have one anyway, extending it is easy. But I'm hopeful we would be able to write Hugo templates that can handle OpenAPI data. Although doing this is quite painful, I think it is worth it because avoiding a preprocessor would be really beneficial in various ways:

* simpler to use: you just run `hugo serve` and you get automatic reloading
* simpler to implement: the actual code to preprocess is easy but deciding when to run it can be a bit tricky. Case in point: in the current setup the "hot reload" code doesn't work at all for me.
* faster: almost certainly it will be *much* faster to run a Hugo template than something like gendoc.
* it feels like fighting the SSG to have a separate preprocessor

I'm open to (3) - I'm sure we can switch to an SSG that deals with this better. But it's extra work to find one and get it looking all right.

> We stand some chance of preserving history with the current files, which are one file per section aiui

I hadn't thought of this! How important is it to preserve Git history? I'm not sure how good Git is at remembering history across file renames and moves.

**Comment by ara4n** [comment]
It's not critical to preserve git history (prolly 6-7/10 imo). git is pretty good at remembering it across renames & moves though, and personally it's a bit of a bugbear if you `git blame` only to have to start chasing a rabbit hole to figure out why a file says what it says.

In terms of the rest of the concerns... they make sense.  It kinda feels like we could solve this all if only Hugo had better ToC support.  It might be worth quickly looking for other SSGs to see if any have a silver bullet?  Alternatively we can steal some golang hacking to fix Hugo and hope they're open to an upstream fix (which seems plausible).

**Comment by wbamberg** [comment]
> Alternatively we can steal some golang hacking to fix Hugo and hope they're open to an upstream fix (which seems plausible).

Yes, I wondered about this too. I think it would be great to so this, and  it seems like the maintainer thinks it would be a good idea: https://discourse.gohugo.io/t/shortcode-processing-order/16554/5 although I can't find the issue.

If we did that maybe we could live with one of the other options (JS ToC or preprocessor) in the meantime.

**Comment by richvdh** [comment]
I think this can be closed, thanks to @wbamberg's hard work.
