### ISSUE TITLE
Federated join room clarification

### ISSUE THREAD

**Issue by gnieto** [matrix-org/matrix-doc#2856]
Ruma's implementation for the `send_join` endpoints (Federation API) is different from the one in Synapse/Dendrite and we would like to clarify which is the expected layout for this endpoint. In this case, Ruma is not including `room_id` and `event_id` on the request body because they are already on the path param.

- `send_join` body should be a representation of a PDU described on the Room version specification?
   - If it should, what happens if the room_id field on the body is distinct from the roomId on the path parameter?
   - If it should, what happens if the event_id field (in case of Room versions 1 and 2) is distinct from the eventId on the path parameter?

Thanks!

**Comment by richvdh** [comment]
excellent questions. Synapse largely ignores the path params, using the body params instead. TBH I think the path params should probably be removed (https://github.com/matrix-org/matrix-doc/issues/2330), but in the meantime returning a 400 seems reasonable.

I'm going to close this in favour of https://github.com/matrix-org/matrix-doc/issues/2330.

**Comment by gnieto** [comment]
@richvdh Thanks for the response. 

Could you confirm that `room_id` (and `event_id` on room versions 1 and 2) should appear on the body, please?

**Comment by richvdh** [comment]
yes, they should.
