### ISSUE TITLE
Register Server Port at IANA

### ISSUE THREAD

**Issue by 6543** [matrix-org/matrix-doc#2861]
At the moment only [Wikipedia](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) has 8090, 8008 and 8448 listed.

If you look at the [Service Name and Transport Protocol Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) it only shows
 * **8446-8449** as [Unassigned](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=111)
* **8090** as [opsmessaging](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=109)
* **8008** as [http-alt](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=108)

The suggestion Would be to get 8448 or the whole range, depending on future needs ...

**It would be good to catch this Port officially so others cant.**
(*Service names are assigned on a first-come, first-served process, as documented in [RFC6335].*)

**Comment by 6543** [comment]
sorry I'm not sure if this is the right place or if it's a dublicate to #1742 - but #1742 do not mention  the 8448 port ...

**Comment by richvdh** [comment]
I'd actually rather get rid of 8448 altogether and use port 443 as the default. That's a bit of a difficult process though.

**Comment by 6543** [comment]
well after running my homeserver quite a while - i think 443 would be best - so I'll close this issue

to get the legacy things removed is another thing ...
