### ISSUE TITLE
Suggest a better way for all clients to handle link previews & encourage no disabling of link previews in encrypted rooms

### ISSUE THREAD

**Issue by ell1e** [matrix-org/matrix-doc#2862]
**Is your feature request related to a problem? Please describe.**
Currently, encrypted rooms aren't that feasible for less experienced users as social rooms: this is because not only is link previews disabled by default for encrypted rooms, there is also no way to revert that per room. Instead, every user needs to manually opt-in to link previews (which inexperienced ones won't) which breaks the only way to share more custom reaction images. Big flashy images is simply how many people express themselves nowadays, and due to also custom stickers and proper gif integration not existing, link previews becomes **the** most important way to do this.

As a consequence, this is IMHO a considerable roadblock to wider adoption of encrypted rooms: even if matrix itself becomes ever more popular, using E2E rooms for a "casual" audience will just mainly lead to complaints given other E2E chats like WhatsApp (even though they're inherently worse for other reasons, e.g. closed source/Facebook association/...) present media just fine, while E2E rooms in Matrix just don't. Even worse, most regular users probably won't even notice what rooms are E2E and just that images don't work in some of them, *even when they enabled link previews in their local client-wide settings*, which is extremely confusing on top of things. The according room-specific opt-in is just extremely well hidden. It took me and another programmer and network engineer/linux user, a short while to even decipher why the link previews still didn't work and that this is indeed intended. That doesn't seem feasible for a general audience.

So I think this default really should be changed, but after a few weeks of pondering I think this is not really an element-specific problem since there should be some sort of agreement on how to handle this on a protocol level so it works for everyone.

The main reason that link previews currently default to off in E2E apparently is to avoid both home server link privacy leaks, and IP address leaks of participating users.

Let me therefore propose how this could be handled to avoid these effects while enabling link previews, and additionally propose that there is some sort of client-agnostic discussion to talk about how this could be suggested to be solved.

**Describe the solution you'd like**

I think there is technical approach to fix this which however the clients currently don't seem to implement (and I'm not sure if the protocol allows this right now): the sender client needs to always generate the link preview locally on link paste, and send it along as actual binary image data. This fixes that the link needs to be either shared with the homeserver, or that the target users can be targeted with an IP steal attack with a malicious link of a server that records connecting client IPs to uncloak everyone in the chat room. The only user having their IP exposed is the one sending the link, which means if done to "capture" somebody's IP it will only net your own unless you trick somebody else into pasting & sending that link. To my knowledge, Telegram also uses this approach.

**If** this or some other solution is agreed upon as feasible, clients should be encouraged not only to use it, but to also allow E2E rooms to opt-in to previews being enabled by default for everyone, with clients preferably respecting that setting to allow wider E2E adoption.

**Describe alternatives you've considered**
I already made a ticket for element only here: https://github.com/vector-im/element-web/issues/14570 however, I figured this is might be better discussed as an ecosystem-wide problem if it's supposed to "just work" for all the participants.

I think the obvious alternatives are:

- to keep homeserver resolved links and allow enabling link preview by default for E2E rooms anyway and make clients generally respect this. However, I can see how this would be undesirable regarding the privacy expectations of an encrypted room
- another alternative would be to change nothing at all, or just leave element to figure this out and ignore everyone else. I don't think these are great approaches to get anything changed about this, however

**Additional context**

**Comment by turt2live** [comment]
Thanks for the detailed issue! It's always great to see someone thinking through the problem :) 

Most of this seems to be specifically targeted at Element, which is known to have poor accessibility on the options for URL previews. The remainder of this ticket appears to be roughly in the shape needed for an MSC, so I'm going to encourage that it be opened there for larger discussion - particularly, the discussion about how to prevent falsely sending a preview.

**Comment by ell1e** [comment]
@turt2live well as reasoned above, if only element does the right thing this doesn't really address the problem. This is why I would suggest to discuss this with all clients, so that others like fractal etc will join in with the "correct" behavior.

**Comment by turt2live** [comment]
That is what the MSC process is for.

**Comment by ell1e** [comment]
Ah okay. I'm still not sure I understand why this would be on the element bugtracker then rather than some more central location (like here), but admittedly I have no idea how your protocol planning is coordinated in general so I guess I'll trust your judgement :smile:

**Comment by turt2live** [comment]
It fits in both, mostly. The UX side of the toggle options being difficult is purely an Element issue that the spec can't solve (as the spec generally doesn't deal with UX). The alternative approach to URL previews would fall under https://matrix.org/docs/spec/proposals - this document is a bit of a long read, but the tldr is to find a proposal which roughly matches the format you're looking for in the `proposals/` directory of this repo and copy/paste it, edit it, then PR it - we'll guide you through the rest as needed.

**Comment by ell1e** [comment]
I think any element options UI is just window dressing, the problem is how link previews are done. So I don't think just discussing this for element does it justice.

I would suggest a protocol spec proposal is necessary for a solution as suggested by me here in the initial ticket, but I don't think I'm a good choice to write one - I really just don't know enough about the matrix protocol to suggest actual endpoints etc, at all, and I think what I am suggesting is conceptually *very* simple so it doesn't really need me to make an actual concrete proposal. If really nobody else wants to I could look into it, but I can't promise I'll get around to it soon. (I have exactly zero pull requests with either clients or servers, I'm just a user at the end of the day, albeit with some network protocol knowledge from other projects.)
