### ISSUE TITLE
Handle voip call signalling on high latency servers

### ISSUE THREAD

**Issue by notramo** [matrix-org/matrix-doc#2865]
Simultaneously starting calls happens often even on low-latency servers. In this case, it is impossible to answer the call from Element.

Alice places a call (sends m.call.invite), and Bob places a call too (before seeing the Incoming Call from Alice because of server latency). Both of them has sent an m.call.invite
In this case, both Alice and Bob has a dialing screen, and can't accept either call because Element would need to display an Incoming Call screen.

I can imagine 2 solutions:
- Could the two m.call.invite data somehow be used to set up the WebRTC connection? If yes, then this should be done.
- Otherwise, when both Alice and Bob receives the other m.call.invite (2 calls are active simultaneously), use the one with newer server timestamp. Send hangup for the one with older timestamp. Send accept for the newer timestamp. In this case, the one who sent the newer timestamp version, has their call answered.

**Comment by uhoreg** [comment]
This issue is called "glare", and is already solved in the spec ( https://matrix.org/docs/spec/client_server/r0.6.1#glare ).  However, clients might not have it implemented correctly (e.g. https://github.com/vector-im/element-web/issues/2199 ).
