### ISSUE TITLE
FAQ not available for inline comments on GitHub

### ISSUE THREAD

**Issue by almereyda** [matrix-org/matrix-doc#287]
As the website FAQ doesn't seem to be line commentable, I have here to refer to the third paragraph in the question [What ports do I have to open up to join the global Matrix federation?](http://matrix.org/docs/guides/faq.html#what-ports-do-i-have-to-open-up-to-join-the-global-matrix-federation).

Given the experiences from @meriac I have just stumbled accross a sentence on [a user page of him](http://www.openbeacon.org/User:Milosch).

> Don't use the same RSA key set for signing and encryption.

Am I falsely assuming my reverse proxying errors, due to the lacking availability of the certificate used on the load balancer from within [a given Matrix container](https://github.com/allmende/docker-matrix), are exactly caused by this: Using the same key for signing (within Matrix) and encryption (of the transport)?

**Comment by richvdh** [comment]
We'd need some more details of the problems you are seeing. I suggest you join [Matrix HQ](https://vector.im/beta/#matrix:matrix.org) and seek support there.
