### ISSUE TITLE
Userside mass leaving of joined rooms (IRC /JOIN 0)

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-doc#2887]
**Is your feature request related to a problem? Please describe.**

I am hoarding too many rooms and have no idea what is going on in the most of them and I find it draining.

**Describe the solution you'd like**

I would like a way to leave many of them simultaneously or manage them as groups. For example IRC's `JOIN 0` would on most IRC servers make me leave all channels immediately. 

**Describe alternatives you've considered**

I have tried:

* to leave the oldest rooms first in Element Web copy-pasting `/part` into rooms, but that makes the channel list scroll back to top, so it's unusable.
* to manually click the three dots in Element Web and select part which takes about ten seconds before anything happens.
* to leave rooms in FluffyChat which upon selecting a room again sends me to top of the room list.

**Additional context**

This is probably somewhat rare feature and even some IRCds have removed it, but I am aware of some users having made scripts that do this (I didn't find any on decision to open an issue for further discussion, please feel free to suggest them at me) so there are people doing it and this is something Matrix could do to help users mental health while they feel overwhelmed with the amount of rooms and notifications Matrix is throwing at them.

For the usecase of leaving everywhere, if I don't start missing the room, I probably don't actually need it.

I am also not sure if documentation repository is the right place to open an issue, but this affects at least two different Elements [which meta issue tracker is closed permanently/archived](https://github.com/vector-im/riot-meta/) and Fluffychat.

**Comment by turt2live** [comment]
While annoying, I think this is fundamentally a client-side problem. The spec provides avenues for clients to offer better UX, but the spec cannot solve clients making it difficult to bulk leave rooms. I would suggest issues on their respective issue trackers.

**Comment by Sorunome** [comment]
> The spec provides avenues for clients to offer better UX, but the spec cannot solve clients making it difficult to bulk leave rooms.

actually, at famedly we had to develop a server-side microservice for exactly that, the client-side experience is so much nicer now

**Comment by uhoreg** [comment]
Sounds like this could mostly be solved by making `/leave` not ratelimited.

**Comment by Sorunome** [comment]
not really, doing 1k http requests is way more likely to fail than doing one more http request. plus what if you turn off your phone during that?

2. 11. 2021 15:24:47 Hubert Chathi ***@***.***>:

**Comment by turt2live** [comment]
Arbitrarily large/intensive requests are something we're trying to move away from on the spec, which is another one of the reasons which contributed to this being closed.

If people think there's a solution that doesn't put unreasonable burden on the server (or client), please open an MSC :)

**Comment by Mikaela** [comment]
Could this issue be reopened while such a solution is being thought of?

**Comment by FSG-Cat** [comment]
I think that a compromise that doesn't make the spec much more complicated would be to reuse the code we use when accounts are deactivated to leave all rooms for this mass leave feature. Does this make the spec a lot more complicated? Im not sure it would make it a lot more complicated and its not like the code to do this is new. Its just an alternative way to trigger the leave all rooms function in deactivate but you don't deactivate the account in the process.

**Comment by uhoreg** [comment]
I'm not sure how reusing code relates to how complicated the spec is, but my understanding is that the request here is to have an endpoint that takes a list of rooms and leaves those, rather than to have an endpoint that leaves all rooms.

**Comment by FSG-Cat** [comment]
> 
> 
> I'm not sure how reusing code relates to how complicated the spec is, but my understanding is that the request here is to have an endpoint that takes a list of rooms and leaves those, rather than to have an endpoint that leaves all rooms.

The purpose would be an endpoint that leaves all rooms. Thats whats being requested.
