### ISSUE TITLE
Move deprecated endpoint indicator up higher in the request representation

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2890]
![image](https://user-images.githubusercontent.com/1190097/101381541-18e5b080-3874-11eb-91f5-3f64720739f3.png)

It should be on the same line as the `POST /path` imo so that people don't spend time reading deprecated APIs.

**Comment by wbamberg** [comment]
I've just pushed a change like this: https://adoring-einstein-5ea514.netlify.app/client-server/#post_matrixclientr0account3pid

<img width="823" alt="Screen Shot 2020-12-07 at 10 58 40 AM" src="https://user-images.githubusercontent.com/432915/101392897-2fdbd100-387b-11eb-9338-9e0a8b0fea04.png">

...we could choose to drop the bigger banner underneath now.

**Comment by wbamberg** [comment]
@turt2live , are you happy that this is fixed?

-> https://adoring-einstein-5ea514.netlify.app/client-server-api/#post_matrixclientr0account3pid

**Comment by turt2live** [comment]
yup, thank you!
