### ISSUE TITLE
Some links can't be clicked due to excessive header padding

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2892]
![image](https://user-images.githubusercontent.com/1190097/101381968-a45f4180-3874-11eb-959f-5588c82badbd.png)

The `/3pid/onbind` link is obscured here.

**Comment by wbamberg** [comment]
Should be fixed now by https://github.com/wbamberg/matrix-hugo/commit/df82430705e8559d093a3316c32548a2a1f34480 .
