### ISSUE TITLE
New spec doesn't let you click on the numbers in the table of contents

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#2899]
Minor thing but it feels weird not being able to click on the numbers next to items in the table of contents. Not a big deal when it is like "1 API Standards" but when you get down to "12.23.1.1.1 Security considerations" almost half of the item is not clickable.

**Comment by wbamberg** [comment]
Good call! This should be fixed by https://github.com/wbamberg/matrix-hugo/commit/39dd568128b35ff415ab287eadc98eaaa0b6c74b .
