### ISSUE TITLE
Inline code is a little tricky to discern from regular text

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#2902]
Consider the following screenshot:

![image](https://user-images.githubusercontent.com/1342360/101927784-c0dce000-3bcc-11eb-8ba2-aca7f9f67a39.png)

While the current style for inline code looks good when isolated, when next to regular text it's a bit tricky to pick out, especially when there's multiple instances close together.

We may want to try adding a different color background to inline code, or something equivalent to make the difference more noticeable?

**Comment by wbamberg** [comment]
By default there is a background for `code` but I had suppressed it because I thought it looked ugly when there was a background color.

By default you get `background-color: rgba(0,0,0,.05);`:

<img width="813" alt="Screen Shot 2020-12-11 at 9 57 50 AM" src="https://user-images.githubusercontent.com/432915/101937999-81e06780-3b97-11eb-9c75-5120e7e574f5.png">

...which does look a bit murky IMO. But maybe we could use the same colour as the `<th>`?

<img width="800" alt="Screen Shot 2020-12-11 at 10 01 07 AM" src="https://user-images.githubusercontent.com/432915/101938274-e8658580-3b97-11eb-98ad-f7fb2534192e.png">

**Comment by anoadragon453** [comment]
Hmm, the second image does look quite good. Does that still work with normal, non-light blue backgrounds?

**Comment by wbamberg** [comment]
> Does that still work with normal, non-light blue backgrounds?

I think it would be a little subtle with the white background.

Current:

*******

<img width="635" alt="Screen Shot 2020-12-11 at 10 23 42 AM" src="https://user-images.githubusercontent.com/432915/101940280-1ac4b200-3b9b-11eb-8b92-7cd178b0ff42.png">

*******

With this change:

*******

<img width="638" alt="Screen Shot 2020-12-11 at 10 23 50 AM" src="https://user-images.githubusercontent.com/432915/101940372-3def6180-3b9b-11eb-81d0-83f3768812d2.png">

*******

So I would suggest only applying this background when inside one of these coloured blocks. Actually I think these coloured blocks will change with @harrisondean 's design, so perhaps we should wait a bit and also ask him :).

**Comment by anoadragon453** [comment]
Yes, that second image is probably too subtle indeed.

> Actually I think these coloured blocks will change with @harrisondean 's design, so perhaps we should wait a bit and also ask him :).

Sounds good, looking forward to it!

**Comment by wbamberg** [comment]
For now I have implemented the second option from https://github.com/matrix-org/matrix-doc/issues/2902#issuecomment-743341872: 

https://adoring-einstein-5ea514.netlify.app/client-server/#post_matrixclientr0useruseridfilter
https://github.com/wbamberg/matrix-hugo/commit/3488be88939e6f1b0546e65ea7264d53d45bdbff

**Comment by anoadragon453** [comment]
![image](https://user-images.githubusercontent.com/1342360/102206189-1f070d00-3ec4-11eb-94ca-ecc4aab2102c.png)

Much better, thanks! I now realise how inconsistent we are with code tags in some places :D

**Comment by wbamberg** [comment]
@anoadragon453 , can we close this? I didn't get any design input, but I think it's looking acceptably readable.

**Comment by anoadragon453** [comment]
I think it looks good now too, thank you!
