### ISSUE TITLE
Reactions aren't encrypted in E2EE rooms.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2905]
We should figure out how to do encrypted reactions in E2EE rooms properly and actually implement it.

**Comment by erkinalp** [comment]
Just encrypt them as if they were message events?

**Comment by t3chguy** [comment]
@erkinalp the server has to know which event they relate to so that it can give clients list of relations per-event. Also that isn't the issue, the issue is doing it whilst respecting some form of backwards compatibility as `m.reaction` didn't go through a sane speccing process.

**Comment by Sorunome** [comment]
Relevant thoughts on this on a relevant MSC: https://github.com/matrix-org/matrix-doc/pull/1849#discussion_r446515510

**Comment by Sorunome** [comment]
Also duplicate of https://github.com/matrix-org/matrix-doc/issues/2678 ?

**Comment by uhoreg** [comment]
> Also duplicate of #2678 ?

Yes.  I *knew* there was an issue for this already.
