### ISSUE TITLE
We should have a custom 404 page

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2911]
It even suggests we should have one:
![](https://i.imgur.com/uidpKjN.png)

**Comment by wbamberg** [comment]
https://github.com/wbamberg/matrix-hugo/commit/505e2c354fe470d8a44c7b87c425c181938d69de -> https://adoring-einstein-5ea514.netlify.app/something

This isn't exactly delightful, but at least I removed the link to the docs.
