### ISSUE TITLE
[Feature Request]:  Joining and Leaving Must be Community Based.  Channel based Joining and Leaving must be Removed

### ISSUE THREAD

**Issue by Ryu945** [matrix-org/matrix-doc#2915]
When running any communication group, your going to need to be able to organize the types of channels you have in that communication group.  You can't rely on those joining the communication group to stay up to date with how your organizing the communication group.  Even if they could, it is to time consuming to expect someone to have to constantly fix something that should be automatic.   The user of a communication group doesn't have the knowledge to make these decisions on their own.  If they did, they would be able to run the communication group.    Thus, allowing people to join and leave channels is not conducive to good communication.

Joining and leaving Matrix needs to be forced to be community based and not channel based.   Users can choose to hide channels from their view but they should be apart of all channels of that community.    Community managers can choose to hide channels from a member in that community but they that person is still technically part of the community as joining is community based and not channel based.

I have considered the alternatives and can't think of any other solution that allows the level of organization you can get from Discord's Guild based system.   Discord is actually a good model on how joining, leaving, channels and ranks should be done.

I know that Matrix is suppose to link with other other services.  Even services that are not community based.    Matrix can treat these services in a special way.   When talking on IRC, your have a community called Freenode which is where all channels in the Freenode server are located.   You can then join and leave on a channel basis within Freenode community.

edit:

From discussing this it seems the best solution is to put both systems in.  Let the creator of the room decide whether they want to have a more guild based system like Discord where channels are apart of the guild.   You view the channels by clicking on the guild or if the creator wants to use what we have now.  I suspect the Guild based system will be more popular as people get familiar with it but at least this gives people choice and doesn't lock them into one system or the other.

**Comment by notramo** [comment]
This would produce a
- lot of traffic for HS
- lot of notifications

Better solution would be to have rooms that can be joined individually, but make it a config option to be Space-based room, which could be joined only if user joins a given space.
"This room cannot be joined without joining [...] space."

**Comment by Ryu945** [comment]
> 
> 
> This would produce a
> 
>     * lot of traffic for HS
> 
>     * lot of notifications
> 
> 
> Better solution would be to have rooms that can be joined individually, but make it a config option to be Space-based room, which could be joined only if user joins a given space.
> "You can't join this room because you are not member of [...] space."

1)  Why do you believe this will be a problem?   What would be wrong with HS storing the text chat of every community someone is in?

2)  Why do you believe there will be a lot of notifications?  It feels like your making some assumption and I am trying to figure out  that assumption.

**Comment by KitsuneRal** [comment]
Thanks for the idea. Most of it is covered by #1772, although in an opt-in, rather than opt-out, manner. I don't think that the opt-out ("forcing") approach that you promote is viable in general in Matrix. You seem to come from your specific experience with Discord that you found convenient, and you make several assumptions that don't necessarily hold outside of Discord's native ground - gaming. Communities in scientific research, commercial setting, software development work in a different way. With that said, the idea of having a kind of a "hub" through which users can easily stay updated on what's happening within the community (including changing its rooms but not only) and also auto-join _some_ rooms definitely makes a lot of sense.

**Comment by notramo** [comment]
> Why do you believe this will be a problem? What would be wrong with HS storing the text chat of every community someone is in?

This would need **huge** amount of storage. Imagine if a user on a self-hosted Raspberry Pi server wants to join a room with 30 member, which is in a community with 150 rooms, some community rooms having thousands of members. If he can't join a single room without the other rooms, he can't join that small room either, because his hardware isn't capable of
1. processing this huge amount of traffic of 150 rooms and tens of thousands of users
2. storing lot of messages
3. transmitting messages on network connection

Also, imagine this in P2P Matrix, where the browsers/phones will store messages...

> Why do you believe there will be a lot of notifications? It feels like your making some assumption and I am trying to figure out that assumption.

Because I don't want to spend time hiding 45 rooms in a community where there are 50 rooms, but I only talk in 5. So I will get lot of notifications. Or I spend time on hiding them.

**Comment by Ryu945** [comment]
> 
> 
>     1. processing this huge amount of traffic of 150 rooms and tens of thousands of users
> 
>     2. storing lot of messages
> 
>     3. transmitting messages on network connection
> 

That sounds more like an issue with hardware.  If they provide inadequate storage and processing power then they put the server on inadequate resources.

>
> Also, imagine this in P2P Matrix, where the browsers/phones will store messages...
> 

Discord has no problem running on a phone.  Matrix in a community based system should also not have any problem.


> > Why do you believe there will be a lot of notifications? It feels like your making some assumption and I am trying to figure out that assumption.
> 
> Because I don't want to spend time hiding 45 rooms in a community where there are 50 rooms, but I only talk in 5. So I will get lot of notifications. Or I spend time on hiding them.

I had a feeling that was your assumption.   Why do you believe you will get notifications if you don't hide a room?   Notifications should only come if someone's name or rank is pinged.  It should also come if someone pings everyone.     General chatting should not create a notification unless you specifically opted into receiving notifications on regular messages.   This is one thing Discord does badly.  They have their servers defaulted to ping on any message.    It should be defaulted to no ping on any message.   Only if you specifically get pinged will you recieve a notification like pinging your name, rank or everyone pings.


>My main UX concern about this is actually related to the current default push rules behaviour. If you are auto-joined to even 5 of the most active rooms in a space, you are going to get bombarded with pushes until you manually go through and change them all to mentions only.

Looking at this person's message we see the real problem.    Matrix servers are set to ping on any message as the default.   They should not have this set as their default.   This should have to be manually turned on.



> 
> 
> Thanks for the idea. Most of it is covered by #1772, although in an opt-in, rather than opt-out, manner. I don't think that the opt-out ("forcing") approach that you promote is viable in general in Matrix. You seem to come from your specific experience with Discord that you found convenient, and you make several assumptions that don't necessarily hold outside of Discord's native ground - gaming. Communities in scientific research, commercial setting, software development work in a different way. With that said, the idea of having a kind of a "hub" through which users can easily stay updated on what's happening within the community (including changing its rooms but not only) and also auto-join _some_ rooms definitely makes a lot of sense.

The change I mentioned should fix any problem with making Matrix community based.

>Communities in scientific research, commercial setting, software development work in a different way.
I have been in software development rooms.  I can't think of any down side to making Matrix community based and it seems like it would solve a lot of usability problems.   Can you provide any kind of organization downside to making it community based?  I can only think of advantages and no disadvantages.  It may be I just know how to setup anything I want in a community based system so I already know the solutions to any potiential problems.  Thus I can't think of any problems on my own.  It is why I am asking you.

**Comment by KitsuneRal** [comment]
> > Communities in scientific research, commercial setting, software development work in a different way.
> 
> I have been in software development rooms. I can't think of any down side to making Matrix community based and it seems like it would solve a lot of usability problems. Can you provide any kind of organization downside to making it community based?

The problem with your suggestion is that communities usually overlap in complex ways. What would be the key "theme" of each community in your proposal? Is it a piece of software? a specific implementation project? a wider cause ("Open Source", "climate change")? If some project or organisation has internal structure, how is it reflected in communities? E.g., in Matrix we have homeserver developers; client application developers (desktop and/or mobile - they overlap); Matrix-related professional services; translators; general users (just to name a few). What would the community structure look like here?

The most problematic situation, as I see it, is with rooms that cross over several "verticals". Biophysicists real-life community overlaps with that of biologists and another of physicists. Should they get a community of their own; or join both other communities, even though the vast majority of physics things (astronomy, nuclear physics, theoretical physics) don't have anything to do with biophysics (and the same goes to biology)?

**Comment by Ryu945** [comment]
I usually see communities related to an area.   For example,   Discord has a bug testing guild.  There is a Discord bot programming guild.  There is a programming guild that has a channel for different languages and they usually direct conversation about Discord bot programming to the Discord Bot programming guild while answer programming related questions.    Different people have made different fitness related guilds.   Each guild has channels organized in a way that make communication work best.  Often, different rooms are for different things.  For any organization structure large enough, you make a community for a particular part.  

> E.g., in Matrix we have homeserver developers; client application developers (desktop and/or mobile - they overlap); Matrix-related professional services; translators; general users (just to name a few). What would the community structure look like here?

I haven't seen the channels for myself but from your description, that sounds like a single community focused on development of Matrix.   Your have different channels in the community for different specialties you listed.   Some specialties might want more then one channel depending on their needs.

> Should they get a community of their own; or join both other communities, even though the vast majority of physics things (astronomy, nuclear physics, theoretical physics) don't have anything to do with biophysics (and the same goes to biology)?

There are two ways you could organize that.  First you could give each type of physics its own community if each one has many rooms it needs anyway.    You could also go the other route and make each type of physics its own room in one community.  Which way is choosen really depends on how the chat rooms are used.     You could even subdivide it further into different groups in each physics community.  Each of these could have their own community.

**Comment by Ryu945** [comment]
Translations is likely a specialized enough area that it could be its own community.  It is based on how things get organized into logical parts.   In practice,  I have never seen a Discord Guild have trouble with what parts should be in a community and what parts should be their own community.   It is like organizing code.   See what makes since to be grouped and what makes sense as its own separate function.   This way, we have people that are an active part of the organization making the decision on organization and not some random person joining something and being unsure what channels they should pay attention to and what they should ignore.

**Comment by KitsuneRal** [comment]
Well, sure; but why limit to community-based membership if a person may pick the rooms from the assortment offered by the community instead - and even create their own sharable "community" out of the selected subset across several others, if they so desire?

**Comment by Ryu945** [comment]
`Well, sure; but why limit to community-based membership if a person may pick the rooms from the assortment offered by the community instead `

A person can pick which channel they pay attention to in a given community.  The point of the community approach is that when someone joins a community, they start out as part of the channels relevant to that community.  As they get experience with the community, they will figure out which channels that need and simply not use the ones the ones they don't need.   As needs change or as the community adapts; they will be able to use the other rooms they don't normally use or even seen new rooms made because needs are changing.   It is essentially the person running the community being able to organize with the members of the community much easier.


`and even create their own sharable "community" out of the selected subset across several others, if they so desire?`

All channels of a community are administrated by by the same person/group of people.  There is not making a new community out of existing channels.   I am not sure why you said that though because even non community based chat platforms has only one person/group running a channel and you can't just make a new community out of someone else's channels.

**Comment by KitsuneRal** [comment]
I understand that the point is discoverability; but you can discover channels without joining them. If I get joined to a hundred channels at once, there's no way I'll read them all; I need to start with something. And if I know what to look for, cleaning away unneeded rooms is simply inconvenient, as several people already said above. Why should we design that inconvenience into our system?

As for the second part - my question was "why limit", and your answer seems to be "because limits"? In Matrix, a [Space](https://matrix.org/blog/2021/05/17/the-matrix-space-beta) may include rooms operated by different people, and Spaces themselves can be created by everyone. What's wrong with that?

**Comment by Ryu945** [comment]
In practice, I have never seen any guild in Discord has hundreds of channels and it is easier to manage them in the interface because they are within a guild menu.   To see the channels, you first click on the guild.  From there, you see the channels related to the guild.   You only see the channels of that one particular guild at a time.   To see channels of another guild, you have to click on that guild.  I was seeing it work like that for communities so that it is not confusing.  

Not having guilds subdivide the channel can actually make the interface extremely confusing as your see channels and have no context for what that channel is apart of.  Is that Team1 channel part of work or is that a League of Legends room?   It also puts limits on channel names as each channel name in every single channel in existence has to be unique.

> I understand that the point is discoverability; but you can discover channels without joining them

How is someone suppose to know if one of the 50 communities someone is apart of gets a new channel they are suppose to start using for specific types of communication?   They are not actively monitoring changes of 50 different communities.


It seems a lot of people are unfamiliar with the benefits of a guild system.  It make wonder if a half way fix might be a better solution instead.   Instead of out right changing every channel to a community, we add both.   Since the word community seems to be used as a way to bundle channels then we might need a new word.   We would essentially add the guild based system where channels are part of the guild.  To be in those channels, you must be in the guild.   Then let people decide whether they want to make a guild or an individual channel like we have now.  I suspect guilds will be more popular in the long run.

**Comment by notramo** [comment]
Related: https://github.com/matrix-org/matrix-doc/pull/3083

**Comment by Ryu945** [comment]
> Related: #3083

If I understand that correctly; that is about other home servers besides the home server that started the room being able to invite members without asking the original home server for permission?

What I am talking about in a guild system is having channels organized behind a guild.   This shows what channels are associated with the guild.   It also means those in the guild are part of all channels in that guild.  Even future ones added and you don't need to put out a PSA telling everyone to join the new channel.  If I misunderstood what was said then clarify.

**Comment by KitsuneRal** [comment]
> Not having guilds subdivide the channel can actually make the interface extremely confusing as your see channels and have no context for what that channel is apart of. Is that Team1 channel part of work or is that a League of Legend room? It also puts limits on channel names as each channel name in every single channel in existence has to be unique.

From the past 5 years of observation, this has never been a real problem in Matrix. We have tags (although they were recently dropped from Element in favour of Spaces), and people can/could assign them freely doing their classification, instead of being imposed to someone else's. You can have a work space and a League of Legend space. If you happen to be a League of Legend developer, you may end up having the same rooms in both spaces, and that's fine: contexts overlap.

> How is someone suppose to know if one of the 50 communities someone is apart of gets a new channel they are suppose to start using for specific types of communication? They are not actively monitoring changes of 50 different communities.

You imply that _everybody_ wants to be aware of every new channel in every guild? While this assumption may be true for some kinds of communities it may be well wrong for others, such as a company's lineup of channels. My company's Google Chat conveniently updates me on a dozen new rooms more created every month. I never used that. I understand that Discord guilds are structured differently. They can (to an extent, see my comments above about opt-in vs. opt-out) be modelled in Matrix. That's not the only, and not always the best, way to structure communication channels.

> It seems a lot of people are unfamiliar with the benefits of a guild system. It makes wonder if a half way fix might be a better solution instead. Instead of out right changing every channel to a community, we add both. Since the word community seems to be used as a way to bundle channels then we might need a new word. We would essentially add the guild based system where channels are part of the guild. To be in those channels, you must be in the guild.

That's exactly a part of #3083 mentioned above.

**Comment by Ryu945** [comment]
> You imply that _everybody_ wants to be aware of every new channel in every guild? While this assumption may be true for some kinds of communities it may be well wrong for others,

That is why I started thinking having both options would be better and let the creator of the space decide what is best.


> That's exactly a part of #3083 mentioned above.

If I use what is mentioned in here, can I create a group of channels where you have to be in them all to be in any of them?  If I add a new channel, those that are part of the space will add the channel automatically?  If I delete a channel, those that are part of the space will delete the channel automatically?   Can I hide a channel based on rank assigned in that space?   I read something about this feature saying you have to be in the space to be able to add the channel but it wasn't clear if it came with auto adding and deleting of channels of those in that space as well as hiding via rank.

**Comment by Ryu945** [comment]
With the implementation of Spaces, the feature being requested will eventually be built.
