### ISSUE TITLE
Proposals page has an unstable warning

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2920]
This page isn't technically spec so shouldn't be covered by the unstable warning. We might be able to ignore the problem and prepare the page for migration out of matrix-doc though.

**Comment by wbamberg** [comment]
It's easy to add a bit of metadata to the page, that the version-banner partial can look at and decide not to show the banner. But this really feels like the wrong approach to me. This whole collection of pages (and data) is presented as "the spec", and as such is governed by the change control process and the versioning system. It feels very out of place and surprising for some arbitrary pages to be not part of the spec. Another way to say this: the absence of the "unstable" banner is a very obscure way to communicate to people that this page is not "part of the spec". It's much more likely that people would think they were looking at the current version of the spec, which of course omits this banner too.

It would be much better for this page to live outside the spec, as other meta-content like https://matrix.org/foundation/ does.

**Comment by turt2live** [comment]
yea, let's ignore the problem for now and leave it for a later migration.

**Comment by richvdh** [comment]
The proposals page is https://spec.matrix.org/unstable/proposals/. I don't see an unstable warning, so I'm assuming this is fixed.
