### ISSUE TITLE
Margins/padding on API responses which contain lists is a bit funky

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2922]
![](https://i.imgur.com/838FZZ8.png)

**Comment by wbamberg** [comment]
Oops. https://github.com/wbamberg/matrix-hugo/commit/1b07d673731c83f7c5d5bfc73b785844933ee741 should fix this:

<img width="887" alt="Screen Shot 2020-12-22 at 4 53 12 PM" src="https://user-images.githubusercontent.com/432915/102946702-40dd3280-4476-11eb-9970-6148ed58ca97.png">
