### ISSUE TITLE
Synchronise the playback position with room members in YouTube widget

### ISSUE THREAD

**Issue by notramo** [matrix-org/matrix-doc#2924]
This would enable watching videos together.
If one person pauses the video, it should stop for everyone, if another starts it, start for everyone. When someone rewinds or fast-forwards, then go to that position at the other members too.

**Comment by turt2live** [comment]
This is the sort of thing that should be done in the client side rather than in the spec given the spec is more about the tools used to create things like this rather than the actual features themselves.

**Comment by notramo** [comment]
@turt2live Where should I open it then? Element? Or Dimension? Or Scalar?

**Comment by turt2live** [comment]
Probably Element for now.
