### ISSUE TITLE
Session verification wildly inconsistent

### ISSUE THREAD

**Issue by ManDay** [matrix-org/matrix-doc#2930]
**Disclaimer:** I file this bug on the spec, because I, with a lot of support from various people from different rooms (Element-Web, Element-Android, and Matrix) have not been able to determine where or how exactly this goes so badly wrong over the course of an entire day. Since, using three clients (Devel Element Web, Stable Element Web, and Stable Element Android), there is no possible combination in which this works, I can only suspect there is something wrong on the server side or in the protocol.

**Premise:** *User A*, multiple sessions, all verified, cross-verification is confirmed to work by the clients. *User B*, one session, one device.

**Behaviour:** I will only give one example for how this does *not* work, as we have tried countless combinations and they all lead to some similarly broken result (i.e. one where *User B* is not verified across all sessions of *User A* and the verification state is strangely inconsistent *within* a single session/client, too), among which one scenario in which my own session claims that my own messages from another session could not be verified.

*User A* initiates a verification request using Element Android in session *S*, which prompts both parties for Emoji comparison. Verification is then (allegedly) successfully completed. The verification is not respected by any of the other sessions of *User A* (in these sessions *User B* still shows as unverified). Meanwhile, in *S*, the user still shows as *Unverified* ("Black Shield" icon) in the room's user list, while they appear as *Verified* ("Green Shield" icon) in their profile.

**Comment by turt2live** [comment]
This sounds like a potential bug in Element Android based off the example. Unfortunately the sort of behaviour you're seeing is a client bug somewhere - I would encourage picking a platform and submitting a bug report to them.
