### ISSUE TITLE
@room message reply notification

### ISSUE THREAD

**Issue by Jaedotmoe** [matrix-org/matrix-doc#2934]
### Description

When an admin/mod replies to a message from a non-mod/admin user containing `@room`, it notifies the whole room.  
Edit: it also seems that it works with a user which the username is `@room` as well (also when mentioned by a mod/admin).

### Steps to reproduce

 - Ask for a non admin/mod user to send `@room`
![image](https://user-images.githubusercontent.com/76598503/103413516-2d1e8400-4b7a-11eb-924e-92319af8aa6c.png)

 - Reply to his message
![image](https://user-images.githubusercontent.com/76598503/103413487-124c0f80-4b7a-11eb-8bed-8d1165fe1a13.png)

 - Everyone gets notified (view from another non mod/admin user)
![image](https://user-images.githubusercontent.com/76598503/103413526-3c053680-4b7a-11eb-966c-3430d49ff6cf.png)

### Describe how what happens differs from what you expected.

The reply shouldn't have triggered the notification of everyone in the room.

### Version information
Element desktop app:
- **OS**:  Arch Linux
- **Version**:  1.7.16-1

**Comment by uhoreg** [comment]
This is covered by https://github.com/matrix-org/matrix-doc/issues/2736
