### ISSUE TITLE
replace 3PID with Certificate Authority

### ISSUE THREAD

**Issue by Axeltherabbit** [matrix-org/matrix-doc#2952]
**Is your feature request related to a problem? Please describe.**
Currently to login and use matrix I have to use third party services, I would like to being able to use a certificate.

**Describe the solution you'd like**
A certificate system is used in [ZeroNet](https://zeronet.io/docs/site_development/cert_authority/) and is great

**Comment by t3chguy** [comment]
> Currently to login and use matrix I have to use third party services, I would like to being able to use a certificate.

How do you? The IS is only used optionally for 3PID invites/user discovery. It is completely optional. For login it isn't needed. 3PIDs for login are resolved by the server to which you are connecting only.

**Comment by arnab15** [comment]
hello,
I have knowledge of javascript ,nodejs,reactjs,expressjs, Mongodb but I haven't contributed to any open-source project before so I'm a beginner. I would like to contribute to this project.
how should I start can anyone suggest to me the way should I start contributing.
