### ISSUE TITLE
New spec: some characters in examples are unnecessarily encoded

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#2972]
e.g. in the example for [initialSync](https://adoring-einstein-5ea514.netlify.app/client-server/#get_matrixclientr0initialsync), the example contains

![image](https://user-images.githubusercontent.com/1012976/104962466-79edc180-59a6-11eb-834c-04c6005ae6fd.png)

whereas the old spec page has

![image](https://user-images.githubusercontent.com/1012976/104962538-a1dd2500-59a6-11eb-995c-424974946132.png)

**Comment by wbamberg** [comment]
This seems to be related to https://discourse.gohugo.io/t/jsonify-is-escaping-strings/25161 , but I don't know how to fix it at the moment :(.

**Comment by wbamberg** [comment]
@uhoreg , I think this is fixed now: https://adoring-einstein-5ea514.netlify.app/client-server-api/#get_matrixclientr0initialsync ? (although [I am not proud of the fix](https://github.com/matrix-org/matrix-doc/blob/69144023381daadcda872d9d36764f4ab02ec893/layouts/partials/openapi/render-responses.html#L84-L85))

**Comment by uhoreg** [comment]
Well, a fix is a fix, even if it's hacky. ;)
