### ISSUE TITLE
Sample events for voice, video and other real-time data

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-doc#2995]
**Is your feature request related to a problem? Please describe.**
There is a voice call feature but this currently only works for 1:1 calls. The same thing applies to sensor-actuator networks that require causal ordering to be preserved across locations.

**Describe the solution you'd like**
Hard real time sample events that will retain latency relationships among speakers, when played back. This is desirable if you have business meetings that needs to be recorded or a long-distance sensor network that coordinates across different locations, as reordering speech/sensor data will cause completely different meanings.

Hard real time would be provided by adding additional latency to each user's samples, such that latency difference between two particular users is the same when listened by any client. This would be provided by calculating a virtual apex point, according to where all latency additions would originate from. As users connect and drop, the latency added to sample events will gradually increase and decrease to keep the reproducibility invariant.

**Describe alternatives you've considered**
Extension of voice calls to many to many but the current network middle-boxes are not good for that.

**Additional context**
Requires binary transport to be implemented first, the latencies would skyrocket with JSON over HTTP.

**Comment by uhoreg** [comment]
Dup of https://github.com/matrix-org/matrix-doc/issues/2851
