### ISSUE TITLE
m.login.terms UIA step is unspecified

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3001]
Some time ago, Synapse added support for an `m.login.terms` User-interactive Auth step, which is now required by many homeservers, including `matrix.org`, when registering.

Presumably therefore, all client implementations that support registering also support the `m.login.terms` UIA step.

IMHO it is therefore a de-facto part of the spec and should be documented as such.

([MSC1692](https://github.com/matrix-org/matrix-doc/pull/1692) appears to be a proposal for it; I've not checked how close the implementation is to that proposal.)

**Comment by richvdh** [comment]
> Presumably therefore, all client implementations that support registering also support the m.login.terms UIA step.

I guess this isn't quite true: clients might be using `/_matrix/client/r0/auth/m.login.terms/fallback/web`. Still, at least the Element clients aren't doing that, so I still think it is a de-facto part of the spec.

**Comment by turt2live** [comment]
This is an MSC: https://github.com/matrix-org/matrix-doc/pull/1692

The implementation is a small percentage of the MSC. I would not feel comfortable putting the MSC into the spec as-is, or even this part of UIA into the spec as-is.

**Comment by turt2live** [comment]
reason for not being comfortable with it is largely not being convinced the implementation is correct, and not letting past mistakes continually appear in this way: an MSC was written, so the process should be finished.

**Comment by richvdh** [comment]
well, we can't change the spec now, so what's the point of the MSC process?

**Comment by turt2live** [comment]
We can change the API, it's just difficult and annoying because we didn't have namespace requirements at the time. 

There's a lot of historical MSCs which are in this same boat - it shouldn't be possible for them to land in the spec without proper review just because a namespace wasn't used.

**Comment by richvdh** [comment]
I'm still unconvinced by this. I hear your point, that implementing something shouldn't be a way of skipping the spec process, and I hope that we're doing better at that than we were back in 2018.

But still, the point remains: you can't sensibly implement registration in a client today without implementing `m.login.terms` support as Synapse currently expects it. It is therefore, de facto, part of the spec, and the fact that the actual words in the spec don't cover it is a bug in the spec.

I think that sticking to our principles in this way simply raises the barrier to resolving the problem high enough that the problem *doesn't* get resolved.

Still, this is probably not the right forum for further discussion, and I won't get into a war with you about it. But whatever the process should be, I wish we would get on with it rather than continually failing to do so.
