### ISSUE TITLE
user name mention notifications happen when user name is mentioned without any qualifying prefix/suffix

### ISSUE THREAD

**Issue by Be-ing** [matrix-org/matrix-doc#3011]
**Describe the bug**

My Matrix user name is simply `be`, which is a common English word. Element triggers a notification anyone uses my user name, which is almost always not actually trying to send a message to me. This makes notifications from Matrix clients basically unusable. User name mentions should only trigger a notification with an appropriate prefix such as `@` or a suffix such as `:`. 

**To Reproduce**
1. Use a common word as a user name
2. Be annoyed by a bunch of irrelevant notifications

**Expected behavior**
I should only be notified by messages specifically directed at me.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser: Firefox
 - Version: 84.0.2

**Additional context**
I reported this first on the [Element Web tracker](https://github.com/vector-im/element-web/issues/16465) and they directed me here.

**Comment by uhoreg** [comment]
FYI, in Element, you can turn off notifications for "Messages containing my display name" and "Messages containing my username".  This will stop notifications when someone just writes "be", but will still notify you when someone writes your full Matrix ID.

![image](https://user-images.githubusercontent.com/1012976/108152617-66b63a80-70a7-11eb-8824-cdbec445db60.png)

**Comment by weeman1337** [comment]
@uhoreg I have tested this. Like you explained switchting it off disables all notifications including the "@" ones. This isn't an option for me because then I am missing "@" mentions.

In many highly acitve rooms I have disabled notifications except "mentions & keywords".

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/matrix-doc/issues/1549

**Comment by richvdh** [comment]
I think being notified when a message contains "be" is expected behaviour if your username is "be" and you have "messages containing my username" enabled. The fact that you then aren't pinged by @mentions is covered by #1549.

Certainly this stuff is a total mess, and it pains me that we've not had the time to rework it.
