### ISSUE TITLE
[nitpick] /messages "dir" parameter is ambiguous

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3019]
> Required. The direction to return events from. One of: ["b", "f"]

This is ambiguous and not immidiately clear what each of these two values do, even if it can be deduced, it should be declared explicitly.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/matrix-doc/issues/2420

**Comment by ShadowJonathan** [comment]
I'd say #2420 is the original issue on this, i'll close this and put the message on there as well.

Duplicate of #2420

**Comment by ShadowJonathan** [comment]
Oh wait no, that issue is more related to undefined behaviour with real-world examples, this is more a clarification issue, i'll re-open this
