### ISSUE TITLE
Remove `aliases` field from /publicRooms

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3056]
... or at least make a suggestion that servers don't return it

**Link to problem area**:

https://spec.matrix.org/unstable/client-server-api/#get_matrixclientr0publicrooms

**Issue**

The spec for `/publicRooms` suggests that servers should return an `aliases` field from the `/publicRooms`. However, [MSC2432](https://github.com/matrix-org/matrix-doc/pull/2432) changed most of the rest of the spec so that `m.room.aliases` events are no longer treated specially, and https://github.com/matrix-org/synapse/pull/6970 removed support for this field from Synapse.

Although this endpoint was never called out explicitly in MSC2432, I think that was just an oversight. It might be nice if the situation was at least made clearer in the spec.

**Expected behaviour**

Remove the field altogether? Or call out that it may not be returned by common server impls, and recommend that servers don't populate it?

**Comment by turt2live** [comment]
ah ha, we do have an issue for this. In a different line of investigation we ran across this exact issue. Proposed for removal here: https://github.com/matrix-org/matrix-doc/pull/3624
