### ISSUE TITLE
Spec links don't always move to the right section

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/matrix-doc#3064]
Take a link like this for example: https://spec.matrix.org/unstable/client-server-api/#client-config

On my Firefox 86, this load the page at the right spot. Then some layouting happens, and I am in a random spot. Refreshing seems to land me in the right spot after that. Best case this would not be necessary!

Browser: Firefox 86
Resolution: 2560x1600

**Comment by MTRNord** [comment]
On my PC reload always lands in the wrong part (way above where it should be). However having the tab while loading in background gets me fairly close to the correct spot. though still a bit above the correct header but close enough to find it easily

**Comment by richvdh** [comment]
think this is a dup of #3057

**Comment by deepbluev7** [comment]
Yep, probably, I didn't see that one! Sorry about that!
