### ISSUE TITLE
Fix redirects to room versions

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3109]

**Comment by heylix** [comment]
Where are they now so we can look them up in the meantime? :D

**Comment by aaronraimist** [comment]
@heylix on the new spec website https://spec.matrix.org/unstable/rooms/

**Comment by turt2live** [comment]
Yes, it was mentioned yesterday but I haven't gotten to it yet.

**Comment by turt2live** [comment]
Redirect is pending ops approval/deployment
