### ISSUE TITLE
Remove unstable warning from stable room versions

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3110]

**Comment by turt2live** [comment]
...maybe. There's a possibility that we shouldn't do this because v1 might get added things, but at the same time they are frozen in time. Room versions are complicated :(

**Comment by richvdh** [comment]
I think this refers to pages like https://spec.matrix.org/unstable/rooms/v1/, which has at the top:

![image](https://user-images.githubusercontent.com/1389908/145557040-2dfb7331-dcb2-439f-a2bf-b9603c3b9c51.png)

**Comment by richvdh** [comment]
I'm not sure we should do this to be honest. We're versioning room versions just like other parts of a spec - eg, they have a changelog (https://spec.matrix.org/unstable/changelog/#room-versions) - so I think it's fine for them to carry the unstable banner.

**Comment by turt2live** [comment]
yea, nowadays it's a lot better. April was a very different time :D
