### ISSUE TITLE
swagger dump doesn't include all endpoints

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#3132]
https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/third_party_lookup.yaml is left out of the `api-docs.json` dump.
This seems to be because of the lack of tags. Why?

**Comment by Dominaezzz** [comment]
Yeah what is this about? https://github.com/matrix-org/matrix-doc/blob/11a0c2447ce7d5453e195ed090e8eb4f53645a42/scripts/dump-swagger.py#L101

**Comment by turt2live** [comment]
The tags are used for categorization, so it's a reasonable check. Is the third party API the only one left out?

**Comment by Dominaezzz** [comment]
No there's a few more.
The request token for email/msisdn APIs.
The add3pid API.
The redirect sso API.

That should be it.

**Comment by afranke** [comment]
Related: #3326

**Comment by turt2live** [comment]
@afranke I think we fixed this with the linked PR?

**Comment by afranke** [comment]
I don’t know for sure that *all* untagged endpoints have been tagged. @KitsuneRal [said](https://github.com/matrix-org/matrix-doc/pull/3326#issuecomment-1005033243)

> there don't seem to be many untagged operations remaining. I guess it's fine to merge this PR and then tag them whenever someone feels like doing that.

I reckon we can close this for now, but we should have an issue about `dump-swagger.py` complaining for untagged operations.

**Comment by afranke** [comment]
https://github.com/matrix-org/matrix-doc/issues/3687
