### ISSUE TITLE
m.login.email.identity example has threepidCreds defined as an array, not an object

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3156]

**Comment by turt2live** [comment]
also msisidn

**Comment by deepbluev7** [comment]
It is also spelled threepidCreds in the spec and synapse answers to that with the helpful error: `Missing threepid_creds`

**Comment by turt2live** [comment]
See https://github.com/matrix-org/matrix-doc/issues/2220

**Comment by richvdh** [comment]
this appears to be a direct duplicate of #2189
