### ISSUE TITLE
Lowercasing email addresses actually means to say casefolding

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3175]
https://github.com/matrix-org/matrix-doc/pull/3167#discussion_r625714158

**Comment by richvdh** [comment]
sorry, I know it's picky, but I think calling it "lowercasing" is likely to mislead people.

**Comment by turt2live** [comment]
yup, just tracking this outside of the PR as notifications on merged PRs tend to go completely missing for me (due to my workflow, but still)
