### ISSUE TITLE
Use the term Group instead of Room

### ISSUE THREAD

**Issue by J-F-Liu** [matrix-org/matrix-doc#318]
Compare the following sentences:

We are in a room.
We are a group.
We are a team.

The relationship of room members is loose and temparory, of team members is too tight, so group is  suitable.

Rooms are just a public place we come and go, while groups mean a personal socializing tool we use.

One selling point of Matrix is group chat, use the term Group match better.

**Comment by aliencq** [comment]
I personally like term "channel" :)

**Comment by richvdh** [comment]
Thanks for the suggestion; we use 'group' to mean something else.

Not all physical rooms are public places, but some are. Similarly, some Matrix rooms are public, and some are private. In all cases, they are places where people can come to talk to others, or leave to find some quiet.

I think 'room' is a good term.

**Comment by ara4n** [comment]
(for the record, we use 'groups' to mean, well, groupings of users - much like in UNIX a group is a set of users, which can then be reused in different places within Matrix, e.g. room membership, ACLs, invites, etc)

**Comment by J-F-Liu** [comment]
I see, thanks.
