### ISSUE TITLE
Connecting existing Matrix accounts to social accounts

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [matrix-org/matrix-doc#3213]
## Suggestion

For the context, please see https://github.com/vector-im/element-web/issues/17448 (while the mentioned issue is filed on the Element Web client, this idea applies on the Matrix spec).

In the current state of SSO with social logins, the Matrix server does not connect any existing Matrix accounts into social account an user attempted to use, and instead create an new one, because the server doesn't found any existing account this sociap account is connected to. This may cause unexpected account duplication for most cases.

In this spec idea, I would like to suggest to have an `Connect existing account` link on the social login callback page to connect their social account they used in login/signup to their existing accounts (with requiring them to re-enter their passowrd for security and confirm access with login prompts in their cross-signing supported apps they use if it's anew login detected).

I also suggest to have an API endpoint for managing connected social accounts without going to the login page/prompt in Matrix clients.

**Comment by richvdh** [comment]
I don't think this needs to be in the spec, and indeed doing so would be counter to our intentions to replace matrix auth with generic OAuth2. It can be implemented entirely in the server, and it is covered for Synapse by https://github.com/matrix-org/synapse/issues/9441.
