### ISSUE TITLE
OpenAPI spec doesn't label URI properties

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/matrix-doc#3235]
Some `type: string` properties are specified to contain URLs ([avatar_url](https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/profile.yaml#L130), [Pusher url](https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/pusher.yaml#L221), [well-known base_url](https://github.com/matrix-org/matrix-doc/tree/master/data/api/client-server/definitions/wellknown), [og:image](https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/content-repo.yaml#L390)), but this isn't machine readable.
JSON Schema allows to [specify URL strings](https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers) with the formats uri, uri-reference, iri, and iri-reference. [OpenAPI v2](https://swagger.io/specification/v2/#data-types) doesn't define these, so the JSON schema definitions apply. The questions which format to use are:
- Do these URLs have to be absolute? I suppose so, because the base url would be unclear, so let's not use the -reference formats.
- Are raw non-ASCII characters allowed in these URLs? I would favor it, so let's use the iri format.

Do you agree with the iri format? Would you accept a PR that adds an URL format to these properties?

**Comment by KitsuneRal** [comment]
Now that I looked into both spec documents again, not using `format` in those cases does look like an omission; on top of what you said, the Swagger spec explicitly opens the door for freeform `format` values. That said, `iri` is a Draft 7 addition, while OpenAPI v2 is based on Draft 4 that only defines `uri` - I guess we should follow that. Also, it's known if those `format` values are supported by all kinds of tooling used both for Matrix spec text generation and for actual code (for one, I use a code generator in my client library, and I know a couple other projects that generate code from OpenAPI descriptions). Submitting a PR to see what the CI pipeline should be straightforward and provide at least some basic validation.
