### ISSUE TITLE
Ephemeral room versions

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-doc#3240]
**Suggestion**

Matrix has resolved moderated instant messaging over open federation(s) just fine. However, existing room versions 1 through 7 are all persistent rooms. To make Matrix one true communication medium and messaging protocol, we need ephemeral room versions too, alongside all the persistent room versions we have now. However, we will have to tackle with the moderation problem over federation in an ephemeral information exchange situation, which is more difficult as servers would not be able to ask for older state in ephemeral rooms.

**Comment by KitsuneRal** [comment]
> To make Matrix one true communication medium and messaging protocol, we need ephemeral room versions too

You again jump to conclusions without elaborating the logic behind them. I, for one, fail to grasp how the right part of the quoted statement implements the left part of it - especially with the caveat you leave after "However".

**Comment by erkinalp** [comment]
I thought it was obvious — simply put, not everything is worth persisting.

**Comment by uhoreg** [comment]
What is an "ephemeral room version"?

**Comment by erkinalp** [comment]
An ephemeral room version is a room version that only accepts ephemeral events and rejects persistence. Ephemeral communications, even in moderated group chat settings, have significant use cases. Not everything is worth or even suitable for persisting.

**Comment by Pandapip1** [comment]
I think it could be useful for the PubSub use case (#951)

**Comment by uhoreg** [comment]
I forgot about this issue.

> An ephemeral room version is a room version that only accepts ephemeral events and rejects persistence.

First of all, we can't have a room that has absolutely no persistence.  Some things must be persisted (e.g. `m.room.member`).  Secondly, even if we make an exception for state events, we don't need a room version that disallows persistence.  Instead, we can have rooms that allow both ephemeral and persisted events, and allow the room to be configured to allow one or the other, or both. [MSC2477](https://github.com/matrix-org/matrix-doc/pull/2477) does this by allowing power levels of ephemeral events to be specified separately from regular events.
