### ISSUE TITLE
Puritan room version for extreme high latency and high reliability use cases

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-doc#3243]
**Suggestion**

The room versions 1 through 7 all have various state reset vulnerabilities. I propose a room version, subtracting the features that cause authorisation reversals, hence stopping almost all the possible ways to achieve state resets:

* The join rule will not be allowed to be made into more permissive (hence, in the progression of public-knock-invite-private, backwards transition will not be allowed)
* No user will be allowed to gain more powers than it has at the time of first join (initial power levels on the invite event will still be allowed) or a previous power adjustment on the user
* Kick=ban (if wanted, [`join`→`leave`]=[`join`→`ban`] could also be added to those constraints)

That room version would be useful in high latency use cases such as interplanetary and/or interstellar communication, and high reliability use cases where state resets are absolutely undesirable.

**Comment by turt2live** [comment]
This is worded as a proposal but isn't a proposal. Closing in favour of discussion elsewhere as part of the pre-MSC recommend process.
