### ISSUE TITLE
Link to Persistent Data Unit schema in SS API broken

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#3257]
**Link to problem area**: https://spec.matrix.org/unstable/server-server-api/#adding-hashes-and-signatures-to-outgoing-events

**Issue:**
<img width="743" src="https://user-images.githubusercontent.com/5855073/123197196-cca93900-d470-11eb-9e73-a885e41f890b.png">

**Comment by aaronraimist** [comment]
It looks like in previous versions of the spec such as https://matrix.org/docs/spec/server_server/r0.1.4#id98 this just linked to https://matrix.org/docs/spec/server_server/r0.1.4#persistent-data-unit-schema which doesn't actually contain an example of a signed event. It just links you to the room versions spec to find an example.

**Comment by turt2live** [comment]
> It just links you to the room versions spec to find an example.

It used to contain the schema, but that was moved out with the format changes. Theory at the time was that we could just keep the PDU schema links around until someone refactored each section to optimize the link, but that hasn't exactly happened at a reliable speed :p

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-doc/pull/3528
