### ISSUE TITLE
[Feature] Wiping a room (not deleting)

### ISSUE THREAD

**Issue by MartinX3** [matrix-org/matrix-doc#3273]
#### Is your suggestion related to a problem? Please describe.
I can't wipe all messages from a room without deleting it.

#### Describe the solution you'd like.
Just clear/wipe/delete/remove all messages in a room.

#### Describe alternatives you've considered.
Using the deletion api and recreate the room maybe.
But all the users need to be readded...

#### Additional context
N/A

**Comment by richvdh** [comment]
I think this is a duplicate of https://github.com/matrix-org/matrix-doc/issues/440
