### ISSUE TITLE
Fix documentation loop between rooms v3 and s2s spec

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3274]
Reference hashes in v3 link to the server-server spec, which link back to room versions.

**Comment by richvdh** [comment]
The server-server spec says:

> It is used for event identifiers in some room versions. See the room version specification for more information.

That seems useful context for how a reference hash is used, rather than a loop?

**Comment by turt2live** [comment]
Not sure what this was referencing.
