### ISSUE TITLE
Documentation for the differences between "federation" and "client" event format

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3305]
There doesn't seem to be any clear documentation of the differences between "federation" and "client" event format.

A non-exhaustive list:
 * clients always get an `event_id` even where this does not exist in the federation format
 * a bunch of fields present in the federation format are stripped out before sending to clients; examples: `depth`, `origin`, `auth_events`, `prev_events`, `hashes`, `signatures`.
 * other fields such as `prev_content`, `prev_sender` and `age` are added to `unsigned`.
 
 ---
 
  - server event format over federation

**Comment by MadLittleMods** [comment]
Looks like it maybe documented here, Persistent Data Unit (PDU), https://spec.matrix.org/unstable/rooms/v1/#event-format

But I would expect to find out and link to that from https://spec.matrix.org/unstable/server-server-api/

**Comment by richvdh** [comment]
I'm planning to cover this as part of some work on #684. Bear with me for a week or two.
