### ISSUE TITLE
Push rules spec still has references to per-device scopes

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/matrix-doc#3313]
Which don't exist

https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-pushrules-scope-kind-ruleid-actions
https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-pushrules-scope-kind-ruleid-enabled

`or device/<profile_tag> to specify global rules or device rules for the given profile_tag.`

**Comment by richvdh** [comment]
I think this is https://github.com/matrix-org/matrix-doc/issues/2616?
