### ISSUE TITLE
Server TLS: Why is `<hostname>` or `<delegated_hostname>` required.

### ISSUE THREAD

**Issue by nielsbasjes** [matrix-org/matrix-doc#3321]
**Link to problem area**:
https://matrix.org/docs/spec/server_server/latest#resolving-server-names

**Issue**
The reasoning behind why either the `<hostname>` or `<delegated_hostname>` must be provided in the certificate by the homeserver is unclear.

I'll put up a proposal for clarification.

**Comment by nielsbasjes** [comment]
Note: I asked about this here:
https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$0qhg4YusurrIbsIBhBUsi3-AfyF0d1zTy28buhPCsvo?via=matrix.org&via=libera.chat&via=vector.modular.im

**Comment by psrpinto** [comment]
@nielsbasjes Now that  #3322 is merged, this issue is fixed, right?
