### ISSUE TITLE
Allow hiding Room-changes/Member changes (room specific!)

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/matrix-doc#3346]
# What should be changed
It would be great if you could disable non-security relevant changes for a room.
At a first glance this would for me:
- member relevant stuff (e.g. joining, leaving, changing name/picture)
- room relevant stuff (e.G. change of the room topic)
For me the most important thing would beeing able to hide member relevant stuff.
It would be good, if the member could change this setting for the room on their own

# How should it be configured
- The Administrator should be able to change this settings for a room as standard.
- The user should be able to overwrite this setting, which will only have a effect for this specific user. (optional)

# Why?
In my opinion it would be good for:
- Info-Rooms where the members aren't allowed to send messages.
- big public rooms, where the specific member "didn't matter".

Especially with a high amount of users and/or a high user fluctuation it could be a useful feature.

**Comment by SimonBrandner** [comment]
As far as I know, the spec shouldn't concern itself with UI/UX issues. This should be a client thing

**Comment by JokerGermany** [comment]
But this is propose shouldn't be a client based (only the optional user thing)
The main propose it to make this setting room based, not client based.

**Comment by SimonBrandner** [comment]
Ah, sorry, though it still seems like there is a better and more re-usable way to do this :thinking:

**Comment by richvdh** [comment]
agreed, this should be a client feature in the first instance. If it's useful to share the settings across clients, then the client can store the information in a user's account settings (and that can be standardised).

I'd suggest raising an issue against your favourite client to kick it off.

**Comment by JokerGermany** [comment]
But a room owner should be able to change the standard setting?!
Why should this be a client setting then?
@richvdh

**Comment by richvdh** [comment]
> But a room owner should be able to change the standard setting?!

I think it's unlikely we would include such a feature, but in any case, the first step is per-user controls. If that works successfully and we still consider that there is a need for room admins to change the per-room defaults, then we can consider supporting that. 

Either way, this would need to be driven by a client author which wants to implement the new feature.
