### ISSUE TITLE
Clarify "is a valid event" requirement in PDU checks

### ISSUE THREAD

**Issue by tulir** [matrix-org/matrix-doc#3357]
**Link to problem area**: https://spec.matrix.org/unstable/server-server-api/#checks-performed-on-receipt-of-a-pdu

**Issue**: The first check, "Is a valid event, otherwise it is dropped.", could be interpreted as validating the entire event, including the content. Only validating the top-level keys seems more reasonable (related: #2801), but either way it should be specified explicitly.

**Context**: Conduit interpreted the requirement as validating the content, and is validating the content of `m.room.create` events, which leads to being unable to join rooms where the `predecessor` doesn't contain a valid event ID (there's no explicitly defined validation of `predecessor` in auth rules or other such places)

**Comment by richvdh** [comment]
I think this is a dup of #1646?

**Comment by tulir** [comment]
I guess yeah, but there has been no progress on that issue :crying_cat_face:
