### ISSUE TITLE
`master` branch has been replaced

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3367]
On 2021-08-27, we replaced the default `master` branch in the matrix-doc repo with a new branch, named `main`. 

The old `master` branch is retained as `old_master`.

We have done this to clean up [some history](https://github.com/matrix-org/matrix-doc/commit/00c6a866) in the repository to ensure that `git annotate` works in the [data](https://github.com/matrix-org/matrix-doc/tree/main/data) directory. Previously it only went back as far as 2021-01, due to multiple copies of the data existing at that time.

We have also taken the opportunity to rename the branch, for consistency with many other projects under the matrix-org umbrella.

Actions that need to be taken by users of this repository:
 * If you have local checkouts of the repository, you should tell them that `master` has been renamed, and that there is a new default branch:
   ```sh
   git branch -m master old_master
   git fetch
   git branch -u origin/old_master old_master
   git remote set-head origin -a
   ```
* New branches and pull requests should be based on `main` rather than `master` (this will be the default behaviour).
* If you have existing pull requests (including MSC proposals) targetting `old_master`, you **DO NOT** need to rebase the branch or change the target of the pull request. Once the pull request is ready, the matrix-doc administrators will merge it to `old_master` and then cherry-pick the change into `main`.

**Comment by turt2live** [comment]
For self docs: e895827731bd5cd17fdc23f135602937e4f0d009 is now on main as d9dd37de0c275b41e377eb7fba91fa84d1b56ab7

Uncommitted stuff: https://github.com/matrix-org/matrix-doc/compare/e895827731bd5cd17fdc23f135602937e4f0d009...old_master

**Comment by richvdh** [comment]
> Uncommitted stuff: [e895827...old_master](https://github.com/matrix-org/matrix-doc/compare/e895827731bd5cd17fdc23f135602937e4f0d009...old_master)

I'm afraid I don't understand this, @turt2live. Uncommitted to where? These things should be on both `old_main` and `old_master`.

**Comment by turt2live** [comment]
The comment is already out of date. Things landed on the old Master yesterday and needed bringing over. Was hoping to record where I got to in that, but ultimately didn't help.

No action needed.
