### ISSUE TITLE
Organise non-state event schemas in a separate section or index type to corresponding section

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3369]
MSC https://github.com/matrix-org/matrix-doc/pull/3368 triggered me thinking about this, there's a lot of message event schemas scattered all over the spec in different areas, while i think it'd help if either;
- an index for it existed (`m.room.message` -> link)
- a full section is dedicated to all message schemas alone, and the rest of the spec links to it instead.

This is mainly to make the spec more friendly to traverse, and to easily list all "official" event formats side-by-side.

This is specifically for non-state events at the moment, I think state events are still important in their context, but maybe a simple index would be helpful for that as well.

**Comment by richvdh** [comment]
I think this is a subset of https://github.com/matrix-org/matrix-doc/issues/3404.
