### ISSUE TITLE
Clarify the mandatory TLS versions supported in clients and servers when connecting over HTTPS

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3376]
Context: We have had some confusion in the conduit room as to if a server only supporting TLSv1.3 would "just have to work", https://federationtester.matrix.org/ reported no problems for that server.

Problem: It might be helpful if the spec says something along the lines of "HTTPS endpoints for servers must support TLS versions 1.2 and 1.3, clients must expect to be able to, and be ready to, connect to a HTTPS endpoint presenting either of these TLS versions"

This would avoid the situation such as a client only supporting TLS versions v1.1 and 1.2, and a server only supporting v1.3, and this failing to establish a successful connection.

**Comment by richvdh** [comment]
dup #2789
