### ISSUE TITLE
Requiring an implementation before FCP isn't mentioned in the official spec process

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3392]
It's been said multiple times (and attested by having a `needs-implementation` label on MSCs) that MSCs need a working implementation before FCP.

However, this isn't reported in the [Spec Change Process](https://spec.matrix.org/unstable/proposals/#process) section, and `needs-implementation` isn't mentioned under the [Lifetime States](https://spec.matrix.org/unstable/proposals/#lifetime-states) section.

It'd be helpful if this defacto process step is clarified in the spec as well, as currently it's the assertion that a implementation is only needed after the MSC is merged, and the spec PR is about to be written.

**Comment by uhoreg** [comment]
The 5th bullet point says

> When a member of the Spec Core Team believes that no new discussion points are being made, and the proposal has suitable evidence of working (see [implementing a proposal](https://spec.matrix.org/unstable/proposals/#implementing-a-proposal) below), they will propose a motion for a final comment period (FCP)

And the linked "Implementing a proposal" section starts with:

> As part of the proposal process the Spec Core Team will require evidence of the MSC working in order for it to move into FCP. This can usually be a branch/pull request to whichever implementation of choice that proves the MSC works in practice, though in some cases the MSC itself will be small enough to be considered proven.

Both these sections indicate that an implementation is needed (except in certain cases) before FCP.
