### ISSUE TITLE
Rename matrix to (S)IMP

### ISSUE THREAD

**Issue by Wallby** [matrix-org/matrix-doc#3398]
**Suggestion**
I think that "matrix" is hard to explain (i.e. the name has little to do with the functionality). I was thinking, as im (instant messaging) is "broadly used", why not rename matrix to SIMP/IMP (i.e. simple instant messaging protocol/instant messaging protocol)..?
I think that adoptation of some standard protocol for "instant messaging" would require a solid name, and I think currently this is lacking.

**Comment by KitsuneRal** [comment]
The meaning of the name is explained right on the front page: "Matrix owes its name to its ability to bridge existing platforms into a global open matrix of communication" (see the "Bridging" section). And Matrix is definitely not only about instant messaging, it's just one of use cases.

**Comment by ShadowJonathan** [comment]
Matrix's use-case is much broader than instant messaging.

**Comment by richvdh** [comment]
I don't think renaming the protocol is on the cards in the near future ;)

**Comment by LinAGKar** [comment]
Even if it were renamed, I don't think SIMP would be a very appropriate name. https://en.wikipedia.org/wiki/Simp:

>Simp is an [Internet slang](https://en.wikipedia.org/wiki/Internet_slang) term describing someone who shows excessive sympathy and attention toward another person, typically someone who does not reciprocate the same feelings, in order to win their affection.
