### ISSUE TITLE
Require DNS over TLS (DoT), or DNS over HTTPS (DoH) to better encrypt user metadata

### ISSUE THREAD

**Issue by marek-lach** [matrix-org/matrix-doc#3399]
**Suggestion**
Require either **[DNS over TLS (DoT)](https://datatracker.ietf.org/doc/html/rfc7858)**, or maybe **[DNS over HTTPS (DoH)](https://datatracker.ietf.org/doc/html/rfc8484)** at the protocol (spec) level itself, in order to help better encrypt (or make a best possible effort at encrypting) even user metadata to some degree when server requests are being made.

**Comment by uhoreg** [comment]
This isn't something we can practically enforce, is out of scope for the Matrix protocol, and doing so would mean that if something better comes along in the future, means that users wouldn't be able to use it until we change the Matrix protocol.
