### ISSUE TITLE
If a client can't generate encryption key for user, give option to prohibit joining encrypted rooms (also #884)

### ISSUE THREAD

**Issue by marek-lach** [matrix-org/matrix-doc#3477]
**Suggestion**
If a **room** that has encryption enabled by default, is joined by a **user** who is not able to generate an encryption key when asked to, because **their client doesn't support e2e encryption**, the server admin should have the option to automatically throw any and all _unencrypted_ participants out of an _encrypted_ room.

This could be achieved so that the server waits a specific time for the client to generate an encryption key for the user and the server also could send multiple (maybe 3) requests one after another in intervals to the client, requesting an encryption key for the user to be generated.

When _all attempts fail after a certain time_, such a user is **automatically kicked out of the encrypted room**, in order to protect the other users there from communicating with an unsecured party.
This would always be only an **optional setting** that server admins could enable if they so choose, not on by default.

Related to #884 also.

**Comment by uhoreg** [comment]
Can you explain why you want this?

You mention that this will protect other users from communicating with an unsecured party, but if the user doesn't have keys, they won't be able to read the encrypted messages anyways.

Also, which server would be in charge of enforcing this?

**Comment by marek-lach** [comment]
> but if the user doesn't have keys, they won't be able to read the encrypted messages anyways

The idea'd be, that an unencrypted user won't even be able to join a room whatsoever, if a server that hosts this room would enforce such rule, so that an unencrypted user cannot engage in any conversation, nor eliciting, soliciting, nor probing (even if blindly) of any information, or content from the encrypted users in that room, because encrypted users won't even see a user joining in the first place, unless they also have an encryption key.

**Comment by uhoreg** [comment]
> if a server that hosts this room

Rooms are not hosted by servers.  Each server has their own view of the room, and they exchange messages to ensure that every server's view is (eventually) consistent.  There is no single server that has authority over the room.

But in any event,

> so that an unencrypted user cannot engage in any conversation, nor eliciting, soliciting, nor probing (even if blindly) of any information, or content from the encrypted users in that room, because encrypted users won't even see a user joining in the first place, unless they also have an encryption key.

What is the attack that you are trying to prevent?  It is pretty trivial for a user to create a key, which would allow them to join the room, and so engage in conversation.  So this would not really stop any sort of attack.

**Comment by marek-lach** [comment]
> Each server has their own view of the room, and they exchange messages to ensure that every server's view is (eventually) consistent.

Interesting. Thanks for the clarification.
