### ISSUE TITLE
Open API: getRoomKeys is missing required flag

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#3485]
**Link to problem area**:

https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/key_backup.yaml#L852-L880

**Issue**

This field is missing `required: true` like is done [here](https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/key_backup.yaml#L757).
The description says that if no keys are found, then empty (but not omitted) `rooms` property will be returned.

This whole schema should probably just be de-duplicated into the definitions folder [like so](https://github.com/matrix-org/matrix-doc/blob/main/data/api/client-server/definitions/room_key_backup.yaml).

**Comment by ankur12-1610** [comment]
I'll work on this!
