### ISSUE TITLE
Open API: Should the *RoomKeysBySessionId APIs really be plural?

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#3486]
**Link to problem area**:

[`putRoomKeysBySessionId`](https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/key_backup.yaml#L380)
[`getRoomKeysBySessionId`](https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/key_backup.yaml#L452)
[`deleteRoomKeysBySessionId`](https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/key_backup.yaml#L499)

**Issue**

The `operationId`s say `RoomKeys` instead of `RoomKey`, however the descriptions clearly states that the operation only deals with a single key.
Can these be updated to `putRoomKeyBySessionId`, `getRoomKeyBySessionId` and `deleteRoomKeyBySessionId` respectively?
Maybe the `BySessionId` postfix could even be dropped?

**Comment by ankur12-1610** [comment]
I'll work on it!
