### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-doc#3487]
**Link to problem area**:

chronological -> https://github.com/matrix-org/matrix-doc/blob/1ad5ff4179cfa2b62d6be47ad6ed8bde95ec2e41/data/api/client-server/message_pagination.yaml#L77

**Issue**

Update

**Comment by ankur12-1610** [comment]
Can I work on it?

**Comment by richvdh** [comment]
please don't feel you need to ask for permission to work on an issue - pull requests are always welcome, particularly in cases like this where there is no doubt of the change being accepted.

Better to say "I'll work on this", just to avoid duplicating work.
