### ISSUE TITLE
the fact the new spec tells you to use /v3 endpoints when synapse doesn't implement them yet is very unfortunate

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#3514]

**Comment by ShadowJonathan** [comment]
I believe this is more a Synapse issue, see their tracking issue; https://github.com/matrix-org/synapse/issues/11079

**Comment by turt2live** [comment]
The spec release was prioritized over waiting for synapse to fix this.

This feels like a retrospective item rather than an issue.
