### ISSUE TITLE
Do older public one-time key pairs get deleted after some time, even if they remain yet unused?

### ISSUE THREAD

**Issue by marek-lach** [matrix-org/matrix-doc#3518]
**Link to problem area**:

> As well as the identity key, each device creates a number of Curve25519 key pairs which are also used to establish Olm sessions, but can only be used once. Once again, the private part remains on the device.

Are the public key pairs specified to be regenerated after some period of time, even if some of them were technically still not used?

For example, does each new season also generate completely new pairs and deletes some yet unused older ones, or do all already in the past generated public key pairs get used first, and remain on the server indefinitely _until_ they are used to the very last key pair until a new one's generated?

> At startup, Alice creates a number of one-time key pairs, and publishes them to her homeserver. If Bob wants to establish an Olm session with Alice, he needs to claim one of Alice's one-time keys, and creates a new one of his own. Those two keys, along with Alice's and Bob's identity keys, are used in establishing an Olm session between Alice and Bob.

**Comment by uhoreg** [comment]
> Are the public key pairs specified to be regenerated after some period of time, even if some of them were technically still not used?

Yes, the client maintains a pool of one-time keys on the server, and generates new ones when the number of keys on the server drops below a certain number (as decided by the client).

> For example, does each new season also generate completely new pairs and deletes some yet unused older ones, or do all already in the past generated public key pairs get used first, and remain on the server indefinitely until they are used to the very last key pair until a new one's generated?

What do you mean by "each new session"?  If you mean a new login, each login is independent and doesn't share one-time keys.  If you log out, the server will drop all one-time keys associated with that device.

**Comment by marek-lach** [comment]
> > Are the public key pairs specified to be regenerated after some period of time, even if some of them were technically still not used?
> 
> Yes, the client maintains a pool of one-time keys on the server, and generates new ones when the number of keys on the server drops below a certain number (as decided by the client).
> 
> > For example, does each new season also generate completely new pairs and deletes some yet unused older ones, or do all already in the past generated public key pairs get used first, and remain on the server indefinitely until they are used to the very last key pair until a new one's generated?
> 
> What do you mean by "each new session"? If you mean a new login, each login is independent and doesn't share one-time keys. If you log out, the server will drop all one-time keys associated with that device.

Yes, I wanted to know if the number of keys on the server drops bellow a certain number after some time period, say 30 days, even if we only used 1 pair of keys in that time, and 2 are still left there unused for all that time, or if the keys are only dropped based on allowed number of public keys allowed to be stored on the server, regardless of how much time it elapsed since they were first generated?

**Comment by uhoreg** [comment]
It is up to the client to decide how to to ensure that there are enough one-time keys, but as far as I know, I think that most clients will just upload new keys once the number of remaining one-time keys drops below a certain threshold.

**Comment by ShadowJonathan** [comment]
@uhoreg i think their question is "will OTKs on a server have an expiry date?", which I assume is mostly related to actors being able to crack these keys preemptively before they're given out, if they gain access to the server's database.

**Comment by uhoreg** [comment]
Yeah, one-time keys stay on the server until they're claimed; they don't have a time limit.

**Comment by marek-lach** [comment]
> @uhoreg i think their question is "will OTKs on a server have an expiry date?", which I assume is mostly related to actors being able to crack these keys preemptively before they're given out, if they gain access to the server's database.
> 
> @marek-lach keys that're given out to other clients or servers automatically instantly expire, if that's an answer to your question.
> 
> Some context that's important here, is the possibility of OTKs "running out", this is why fallback keys exist, which are given instead of OTKs once that pool has been exhausted.

Oh, this answers the question. Much thanks.

**Comment by marek-lach** [comment]
> Yeah, one-time keys stay on the server until they're claimed; they don't have a time limit.

Could this be optionally specified in the future? To set that for example unclaimed keys older than 30 days could expire, and so some new ones are generated by the client on next login, if the client & server developers would want to implement such a possibility?

Thanks for your patience,

**Comment by ShadowJonathan** [comment]
It's a trade-off, there's technically a small security risk with running out of OTKs already, where other clients then have to request the fallback key, and the device can't know how many times the fallback key has been used, and/or for how long.

Though I think Hubert can explain that trade-off better than me. I think that an expiration date *could* technically be possible, but I don't think it's a clear-cut better option, considering a context in which the current behaviour was made.

**Comment by marek-lach** [comment]
> It's a trade-off, there's technically a small security risk with running out of OTKs already, where other clients then have to request the fallback key, and the device can't know how many times the fallback key has been used, and/or for how long.

Ah, I see how that would not be a good idea rather at all then to get into.

You explain these things well.

Thank you.
