### ISSUE TITLE
Public config? Publishable server configurations? (Add example Matrix public homeserver config?)

### ISSUE THREAD

**Issue by payingattention** [matrix-org/matrix-doc#3521]
**Link to problem area**:
Server config (https://spec.matrix.org/v1.1/server-server-api/#security-considerations?)

**Issue**
Visibility/sharing of server configuration settings

In ``wp-config.php`` for WordPress, it is a common security vulnerability/concern that users keep that data in their public_html folder, which risks sharing sensitive information.

Is the main/primary concern for Matrix.org servers the same as WordPress, which is to say not sharing credentials/password fields is the "only" attack vector?

Should there be clear instructions/warnings about what config file(s) disclosures are safe?

![Screenshot_20211123-112812](https://user-images.githubusercontent.com/8619/143069154-bd37e114-5f98-49b4-810c-c74aeab2003b.png)

**Comment by richvdh** [comment]
I don't think this is a spec issue.

The synapse homeserver.yaml typically contains secret keys, so it should be self-evident that publishing it is a bad idea.

**Comment by payingattention** [comment]
@richvdh Migrate or make again at https://github.com/matrix-org/synapse?

WordPress users publish these files all the time...
