### ISSUE TITLE
Sync v2 is specced as `/v3/sync` on the new spec website

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3536]
**Link to problem area**: https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3sync

**Issue**
This is clearly sync v2, while v3 is still in MSC land

**Comment by uhoreg** [comment]
The "v3" in the endpoint name and in "Sync v3" mean different things.  `/v3/sync` is correct, as per [MSC2844](https://github.com/matrix-org/matrix-doc/blob/main/proposals/2844-global-versioning.md#endpoint-versioning).  We may want to rename "Sync v3" to something else to reduce confusion, but that's an issue for the "Sync v3" proposal, and not a spec issue.

**Comment by turt2live** [comment]
This was raised several times over the last year - it's unfortunate, but significantly lower priority than getting the feature out.
