### ISSUE TITLE
Clarify how user self-demoting works

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3545]
Currently, the spec says nothing about user self-demotion, where either a user sets their own PL to less than their current PL, or removes it from the new PL event entirely.

The current server consensus seems to be that user self-demotion is okay and will always be allowed, but some explicit wording on this would be nice.

**Comment by uhoreg** [comment]
This is covered in [Authorization rules]:

> 10. If type is m.room.power_levels: 
>   ...
>      4. For each entry being added, changed or removed in both the events and users keys:
>       1. If the current value is higher than the sender’s current power level, reject.
>       2. If the new value is higher than the sender’s current power level, reject.
>   ...
>      6. Otherwise, allow. (Markdown is mangling this, but this is supposed to be "6", at the same level as the "4" above)

It may be a bit hard to understand, but it's there.

**Comment by ShadowJonathan** [comment]
Hmmm, looks to be fairly implicit, but since this is methodological (and essentially pseudocode), i think this is fine.

cc @kegsay

**Comment by ShadowJonathan** [comment]
The only thing I could say is that a comment saying that "the current power level" is whatever "the resolved power level preceding this event" is, would maybe help resolve this ambiguity.

But as it's rather a small ambiguity, I'm not pressing it.
