### ISSUE TITLE
Feature request: anonymous messages by room members

### ISSUE THREAD

**Issue by 0cwa** [matrix-org/matrix-doc#3546]
Hi, I'm sorry if this isn't the right place to put this, I'm not super familiar with the protocol, but it seemed like this might be a protocol-level feature request.

One thing I've found as far as organizing people for political action: it would really be nice to have a room setting that allows members of that group to send messages to the group anonymously to allow the voicing of controversial opinions, for example, opinions or calls to action that could get a renter posting to a group of renters in trouble with their landlord if it got back to the landlord.

Let me know what you think or if this is even the right place to post this.  Thank you for this amazing open source tool :) 👍

**Comment by 0cwa** [comment]
Here's how I could see this working, at least for my use case:
For the creation of ad-hoc rooms within spaces to discuss issues, (with the ability to generate invites within channels), where people could choose which information from their main account/roles from the channel/space they wish to carry over to the ad-hoc room wish would allow a permission for people to create one or multiple ad-hoc anonymous names to comment controversial opinions.
There may also be a place for an optional de-masking feature in the future to prevent spam or harassment.

**Comment by richvdh** [comment]
this somewhat ties into #1228, which talks about ways of decoupling the events in a room from the ID of a user that sends them. Suffice it to say, it's not easy.

A partial solution is simply to use guest accounts.

**Comment by richvdh** [comment]
I think it's the same as https://github.com/matrix-org/matrix-doc/issues/951, so I'm going to close in favour of that.

**Comment by 0cwa** [comment]
I think it's more similar to #566 (SPEC-260), linked in the one you mentioned.
