### ISSUE TITLE
Define a version regex

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3594]
This came up in https://github.com/matrix-org/complement/pull/260, while defining a strict regex for validating `/versions` responses with, it became clear that that is more a spec issue.

The regex in question is;

`^(v[1-9]\d*\.\d+|r0\.\d\.\d)$`

A bit more exploded;

	Matches;
	 - v1^.*
	   where 1^ is 1 through 9 for the first digit, then any digit thereafter,
	   and * is any single or multiple of digits
	 - r0.?.?
	   where ? is any single digit

	(
	  # v1^.*
	  v[1-9]\d*
        \.
        \d+
      # r0.?.?
      |r0
        \.
        \d
        \.
        \d
	)
	

([Regexr link](regexr.com/6c889))
	
Would this regex satisfy all historical and future version notations?

**Comment by turt2live** [comment]
Support questions like this are best asked in rooms.

The versions are specified as follows:
rX: https://github.com/matrix-org/matrix-doc/blob/client_server/r0.6.1/specification/index.rst#specification-versions
vX: https://spec.matrix.org/v1.1/#specification-versions
