### ISSUE TITLE
 MSC3089: File tree structures #3089 Transclusion 

### ISSUE THREAD

**Issue by bijang** [matrix-org/matrix-doc#3596]
A query/suggestion/request regarding the  MSC3089: File tree structures #3089 :
 Would the transclusion of an object in the file structure, such as an editable document, be possible? so that changes eg editing or deleting it, in one part would affect all other instances, no matter where in the tree structure it appears? 
Or multiple tree structures, if it appears across multiple different heirarchies, allowing simultaneous editing of a file whose instances reside, (in relation to each other), in a non-heirarchical distribution?

**Comment by uhoreg** [comment]
This is not the right place for asking questions.  Either ask in a Matrix room, such as #spec:matrix.org, or ask in the MSC itself.  But MSC3089 does not introduce any functionality for editing documents.  It's only about organizing files in a tree-like structure.  Editable documents would be a separate MSC.
