### ISSUE TITLE
Example response for `GET /_matrix/federation/v1/user/devices/{userId}` omits missing field

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-doc#3620]
**Link to problem area**:  https://spec.matrix.org/v1.1/server-server-api/#get_matrixfederationv1userdevicesuserid

**Issue**
The spec says that the response object has a top-level "devices" key, which is

> **Required:** The user’s devices. May be empty.

It then provides an example response object with no "devices" key.

**Expected behaviour**
If the field truly is required, amend the example. Otherwise amend the api description to make "devices" not required.

**Comment by DMRobertson** [comment]
This seems to have been corrected in the unstable spec: https://spec.matrix.org/unstable/server-server-api/#get_matrixfederationv1userdevicesuserid

**Comment by DMRobertson** [comment]
(though I couldn't see how, where or why this has changed. /shrug)

**Comment by turt2live** [comment]
possibly https://github.com/matrix-org/matrix-doc/pull/3584 ?
