### ISSUE TITLE
`Event::depth` does not specify if negative values are (dis)allowed

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3629]
**Link to problem area**: https://spec.matrix.org/v1.1/rooms/v1/#event-format

**Issue**
> Required: The maximum depth of the prev_events, plus one. Must be less than the maximum value for an integer (2^63 - 1). If the room’s depth is already at the limit, the depth must be set to the limit.

This does not specify if negative values are (dis)allowed.

Convention is that depth starts from 0, as it's an increasing/adding counter only going upwards.

This has stateres consequences only in v1, but it is also defined in other room versions.

`ruma` defines this as an unsigned int variant.

**Comment by turt2live** [comment]
https://spec.matrix.org/v1.1/#event-graphs

> An event’s depth is a positive integer that is strictly greater than the depths of any of its parents. The root event should have a depth of 1. Thus if one event is before another, then it must have a strictly smaller depth.

Note that `0` is also valid in some cases where annotated.

**Comment by ShadowJonathan** [comment]
Ah, thanks!

**Comment by jplatte** [comment]
Actually I found a place that mentions this:

> To order and ease chronological comparison between the events within the graph, homeservers maintain a `depth` metadata field on each event. An event’s `depth` is a positive integer that is strictly greater than the depths of any of its parents. The root event should have a depth of 1. Thus if one event is before another, then it must have a strictly smaller depth.
>
> — https://spec.matrix.org/v1.1/#event-graphs

However, "positive integer" to me sounds like it would actually exclude 0, contradicting what you wrote.

**Comment by jplatte** [comment]
> Note that `0` is also valid in some cases where annotated.

What's an example of such an annotation? Would it be okay to change that section to say non-negative?

**Comment by turt2live** [comment]
In various places it'll say "May be zero" (or similar). I don't have a link off-hand, sorry. 

The intro text is meant to be accurate for the general case, and was the original intent of v1 rooms, but not all rooms in v1 start at 1 because of ancient Synapse issues (as Synapse was Matrix way back then). `depth` is supposed to be `>=1` in v1 and v2+ versions, but there's those exceptions in v1 which make it zero *sometimes*.
