### ISSUE TITLE
Push rules - Don't search domains for keywords

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/matrix-doc#3640]
Push rules are defined by the spec and evaluated by all clients and servers, I suggest opening this on the matrix-doc repo
_Originally posted by @t3chguy in https://github.com/vector-im/element-web/issues/20518#issuecomment-1011580153_

### Your use case

I made the big mistake and my matrix server is contains my nickname jokergermany.XXX

#### What would you like to do?
Now i get a notification because "i got mentioned" when some of the ghost user on my matrix Server a mentioned.
It would be great if this could be stopped.

#### Why would you like to do it?
To get no notification when puppets are mentioned.

#### How would you like to achieve it?
When searching for keywords, ignore domain names.

### Have you considered any alternatives?

Yes, Anti-Keywords [#20519 ](https://github.com/vector-im/element-web/issues/20519)

**Comment by richvdh** [comment]
please can you give an example of a message that you are getting a notification for, that you wouldn't expect?

related: #1549

**Comment by JokerGermany** [comment]
This is the same issue:
https://github.com/matrix-org/matrix-doc/issues/2319

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-doc/issues/2319
