### ISSUE TITLE
Should room name be limited to 255 bytes?

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#3641]
**Link to problem area**: https://spec.matrix.org/v1.1/client-server-api/#mroomname

**Issue**

The spec says the `name` field in the `m.room.name` event must not exceed 255 bytes. Synapse, Dendrite, and Conduit do not enforce this over the C-S API. Is the spec wrong or are the servers wrong?

**Comment by Half-Shot** [comment]
Hm, the horse may have bolted by this point. I'd probably vote to remove the requirement (and later add it in a MSC, if we think it's required). Events are obviously limited to 65k, and any sensible client should be trimming excessive names anyway.
