### ISSUE TITLE
Missing knock rule on v7 room

### ISSUE THREAD

**Issue by gnieto** [matrix-org/matrix-doc#3648]
**Link to problem area**:

https://github.com/matrix-org/matrix-doc/blame/16ec511e9c858b9fd49456922132f4fc389e4ddd/content/rooms/v7.md#L134-L138

**Issue**

Rule `iv. Otherwise, reject` seems to be missing on knock membership auth rule (Rule 4.6). It was present on a previous version of the spec ( https://github.com/matrix-org/matrix-doc/pull/3432/files#diff-d6b46653922eec4cccb889228b3bc6a1eca1f2aaec466b486e21b734071f017eL40-L48), but it's missing since this PR was merged: https://github.com/matrix-org/matrix-doc/pull/3432

**Expected behaviour**

The mentioned rule should be restored

**Comment by gnieto** [comment]
This rule seems to be missing also on room v8 and v9 which were recently merged on: https://github.com/matrix-org/matrix-doc/pull/3387

**Comment by turt2live** [comment]
I don't think it's technically required because it'll fall into `unknown, thus reject`, but it's very sensible to put back
