### ISSUE TITLE
the thing tagged `v1.2` is not v1.2

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3704]
https://github.com/matrix-org/matrix-doc/tree/v1.2 predates the generation of the changelog (e488a7fb6), and is therefore not a true representation of the thing that actually forms https://spec.matrix.org/v1.2.

**Comment by richvdh** [comment]
(I think this is because otherwise you get an empty "changes since last version" section, https://github.com/matrix-org/matrix-doc/issues/3580)

**Comment by turt2live** [comment]
What is served on spec.matrix.org is actually what is tagged - those artifacts are on the release itself.

**Comment by richvdh** [comment]
> What is served on spec.matrix.org is actually what is tagged

Hrm, so it is.

**Comment by turt2live** [comment]
(it is confusing though that the changelog isn't generated, per https://github.com/matrix-org/matrix-doc/issues/3580 )
