### ISSUE TITLE
v1.2 Appservice login type identifier inconsistency

### ISSUE THREAD

**Issue by Schuwi** [matrix-org/matrix-doc#3709]
**Link to problem area**:

https://spec.matrix.org/v1.2/client-server-api/#appservice-login

**Issue**
The appservice login type is referred to as `m.login.appservice` here while in the [Application Service API spec](https://spec.matrix.org/v1.2/application-service-api/#server-admin-style-permissions) it's specified as `m.login.application_service`, same as in the [corresponding MSC2778](https://github.com/matrix-org/matrix-doc/pull/2778) and the [`/register` route](https://spec.matrix.org/v1.2/application-service-api/#server-admin-style-permissions).

**Expected behaviour**
The identifier in [Client-Server API](https://spec.matrix.org/v1.2/client-server-api/) and [Application Service API](https://spec.matrix.org/v1.2/application-service-api/) specs should be consistent. I suppose the correct identifier is `m.login.application_service`.

**Comment by Half-Shot** [comment]
Looks like it didn't get copied into the spec properly, it's actually `m.login.application_service` in Synapse anyway (https://github.com/matrix-org/synapse/blob/2f053f3f82ca174cc1c858c75afffae51af8ce0d/synapse/rest/client/login.py#L73-L74) so it looks like even implementations are following the proposal.
