### ISSUE TITLE
Mentions of `m.login.token` linger in the spec

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-doc#3733]
**Link to problem area**: https://spec.matrix.org/v1.2/client-server-api/, search for `m.login.token`

**Issue**
As per https://github.com/matrix-org/matrix-doc/pull/2611, these references should've been removed.

Related: https://github.com/matrix-org/matrix-doc/issues/3732

**Comment by richvdh** [comment]
the references look correct to me?

**Comment by turt2live** [comment]
The UIA type was removed but not the login type.

**Comment by ShadowJonathan** [comment]
Then that clarifies things a little, thanks.

**Comment by richvdh** [comment]
The text of MSC2611 explicitly says:

> For clarity: this proposal does not suggest making any changes to the `m.login.token` login type.

It feels like a little more attention could have saved a bunch of people some time here.
