### ISSUE TITLE
MSC 1929 admin contact: new roles in addition to admin and security: abuse and support

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-doc#3740]
I like the idea of being able to contact an admin. However, I find the `admin` being a catch-all a bit broad and not future proof.

It would be a very good addition to mjolnir if after enacting a ban, it could contact the HS abuse personnel (`abuse`) of the abuser via a direct message or a report room. It could submit a link pointing to the user and the event ID of the abuse. The HS abuse control personnel could then verify the report and then enact a ban based on email address, email domain or IP address of the abuser. Others can not enact such a powerful ban outside the HS.

I think the (customer-) `support` contact point might be useful if a user has a general issue, like messages or encryption keys getting lost, synchronization taking forever, slowness, request for enabling a feature like labs, etc.

The `admin` contact point should probably be reserved for very high level communication, for example between server operators about federation issues or other things that can only be debugged from the server logs with cooperation of multiple admins or developers.

The `support`, `abuse` and `security` roles can all be delegated to trusted third parties, while the `admin` role should be reserved for responsibilities that can not.

https://github.com/matrix-org/matrix-doc/blob/7395dcd7855ad1c19d77873fbadbfd0ca8e2e00a/proposals/1929-admin-contact.md?plain=1#L36

**Comment by turt2live** [comment]
This would be best represented as inline comments on the MSC please.
