### ISSUE TITLE
API viewer is barely usable on mobile web

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#727]

**Comment by richvdh** [comment]
Yup, needs some CSS love. ![screenshot_20161121-111251](https://cloud.githubusercontent.com/assets/1389908/20480697/958e5b80-afdb-11e6-9241-a61ce7b4fb09.png)

**Comment by turt2live** [comment]
Still spectacularly broken today - is this something that's fixable in this repo or should this be moved to matrix-org/matrix.org?

**Comment by richvdh** [comment]
> should this be moved to matrix-org/matrix.org?

yes.

**Comment by turt2live** [comment]
Moved to https://github.com/matrix-org/matrix.org/issues/192
