### ISSUE TITLE
API to enquire what rooms I'm a member of

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-doc#734]
Currently the Slack bridge has a horrible hack abusing `/sync` to let a user enquire what rooms they're a member of. It's messy:
https://github.com/matrix-org/matrix-appservice-slack/blob/master/lib/MatrixSlackBridge.js#L381

I'm about to copypaste it into the gitter bridge, before seeing if I can push it upstream either into the bridge library or matrix-js-sdk itself.

It would be nice though if sometime there was a better server-side API this code could use to ask the question. Right now I believe it will cause unnecessary work in the server to generate information it is only going to throw away (namely; the contents of the `m.room.create` events)

**Comment by richvdh** [comment]
So in a regular client, you already know which rooms you're a member of, because you've already called /sync. Is this an issue which is specific to bridges, because they aren't calling /sync on a per-user basis?

**Comment by leonerd** [comment]
When you say "already called sync" - yes. We're calling sync on startup to know what rooms we're in. Currently that's too much overhead because synapse wants to populate lots of extra results in the "/sync" response - namely room state and presence, which the bridge is going to ignore anyway. So synapse could save itself some work by not bothering.

Even just a simple

    GET /_matrix/client/r0/sync?room_ids_only=1

would be nice.

**Comment by richvdh** [comment]
right... but how do you then get hold of any messages which you need to mirror from the matrix to the foreign protocol?

**Comment by Kegsay** [comment]
I imagine the intention would be to use the resulting room IDs to query room-based APIs like `/state` to pull in associated data. Messages would still be done via the HS -> AS API.

**Comment by richvdh** [comment]
I thought the whole point of /sync was that everything should come via /sync to avoid race conditions. Why does the same argument not apply to bridges?

**Comment by leonerd** [comment]
`/sync`'s design is also to be a oneshot "get everything the client needs" in one call, to display to a human sitting at a monitor. It puts a lot of load on the server to do that, unnecessarily so for bridges that don't need that all-in-oneness.

Additionally, making sync work like this would require the bridge to be storing sync position tokens locally, which is something so far none of the bridges do. They all start up and attempt to resynchronise from whatever state is prevailing when they start.

**Comment by leonerd** [comment]
For tracking: this code now also copied into `App::MatrixTool`, at
https://metacpan.org/source/PEVANS/App-MatrixTool-0.08/lib/App/MatrixTool/Command/client/list_rooms.pm#L33

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/1680

**Comment by richvdh** [comment]
Now just needs speccing

**Comment by turt2live** [comment]
Just so this shows up in search results:

The missing endpoints are `/rooms/{roomID}/joined_members` and `/joined_rooms`.

**Comment by richvdh** [comment]
resolved by #999 thanks to @t3chguy
