### ISSUE TITLE
Register API docs lie about default `kind` param

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#736]
<img width="1165" alt="screen shot 2016-11-20 at 16 20 50" src="https://cloud.githubusercontent.com/assets/1294269/20463508/60257bac-af3d-11e6-9850-833d52f5b497.png">

**Comment by ara4n** [comment]
is it `guest` or `user`?

**Comment by richvdh** [comment]
This will be fixed by #740 in the next spec release.
