### ISSUE TITLE
Add node-red matrix nodes to projects

### ISSUE THREAD

**Issue by mlopezr** [matrix-org/matrix-doc#753]
[Node-RED](http://nodered.org/) is a self-hosted visual tool to wire together APIs. 
I have extended Node-RED with nodes to listen and talk in Matrix chatrooms.

Documentation is available here:
https://github.com/mlopezr/node-red-contrib-matrixbot/tree/master/docs

Feedback is welcome!

**Comment by oddvar** [comment]
Thank you! added @ 46eef3d32e839d2db379cffa5ff970e965e6a430
