### ISSUE TITLE
Start publishing a list of public homeservers

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#765]
* matrix.org (duh)
* we.ho.st
* disroot.org

If you want to advertise public HS hosting, please add a comment here and we'll get you added to an official list somewhere on matrix.org!

**Comment by almereyda** [comment]
matrix.allmende.io

**Comment by 4nd3r** [comment]
important thing to remember with public homeservers: where is HS hosted and what promises "owner" gives. or how do you even measure quality of public HS? if someone just got cheap VPS from somewhere and HS gets lots of accounts and one day owner can't pay for it anymore... well, you get the idea.

**Comment by JasonLocklin** [comment]
A table that indicates information about each server's reliability, updates, security, etc., could be modelled after: https://xmpp.net/directory.php or http://www.jabberes.org/servers/ or https://list.jabber.at/

**Comment by arxcode** [comment]
I have made a first attempt at a public server list for Matrix: https://www.hello-matrix.net/public_servers.php 

I have added the servers above to which I could actually connect. Let me know if you want to use this or get added to it (or want to add details to your server's listing).

**Comment by richvdh** [comment]
this isn't really a spec issue. Closing in favour of https://github.com/matrix-org/matrix.org/issues/95
