### ISSUE TITLE
/r0/register endpoint requires a password according to the spec

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-doc#771]
This doesn't make sense because it is used for both user registrations and logging in as a guest, and Riot doesn't follow the spec either when using it without being logged in.

**Comment by richvdh** [comment]
dup #719

This is actually fixed (or at least improved) in the head version of the spec: http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-unstable-register.
