### ISSUE TITLE
"Make" Error

### ISSUE THREAD

**Issue by samnils** [matrix-org/matrix-doc#791]
cybers@ubuntu:~$ cd sprout/
cybers@ubuntu:~/sprout$ make
/home/cybers/sprout/mk/cassandra.mk:48: /home/cybers/sprout/build/cassandra/interface/thrift/gen-cpp/Cassandra.d: No such file or directory
/home/cybers/sprout/mk/cassandra.mk:48: /home/cybers/sprout/build/cassandra/interface/thrift/gen-cpp/cassandra_types.d: No such file or directory
cd /home/cybers/sprout/modules/thrift && ./bootstrap.sh
./bootstrap.sh: 1: ./bootstrap.sh: automake: not found
make: *** [/home/cybers/sprout/modules/thrift/configure] Error 1

help please

**Comment by richvdh** [comment]
what is this to do with matrix-doc?
