### ISSUE TITLE
Could you explain the differences between similar components of Matrix.org and IPFS/libp2p in the FAQ or other section in the home page?

### ISSUE THREAD

**Issue by jmithmstr** [matrix-org/matrix-doc#796]
Could you explain the differences between similar components of Matrix.org and https://github.com/ipfs/ipfs or https://github.com/libp2p/libp2p in the FAQ or other section in the home page?

**Comment by jmithmstr** [comment]
Matrix.org is just federated while ipfs/libp2p is really distributed.
Where should this information be documented?

**Comment by richvdh** [comment]
the faq seems like a good starting point.

This repo is (nowadays) for the spec, and I don't think the spec is a good home for this sort of explanation, so I've opened https://github.com/matrix-org/matrix.org/issues/71 to replace this one.
