### ISSUE TITLE
Handling the reason field in kick and ban endpoints

### ISSUE THREAD

**Issue by mujx** [matrix-org/matrix-doc#798]
Could you clarify the usage of this field? The spec doesn't seem to use it, unless I have missed something. 

I guess that there should be a `reason` field on the `m.room.member` event.

**Comment by MilkManzJourDaddy** [comment]
If you mean that which more or less directly translates to, in an IRC client, or Matrix client:

```
- /kick <IRC_nickname|Matrix_MXID> [<reason>]

- /ban <IRC_nickname|Matrix_MXID> [<reason>]

(At the time of this writing, I don't recall if issuing the above with 
a "Matrix_Display_Name" works in Matrix, 
but IRC_nickname is for use within IRC clients.)
```

Then it is probably assumed that those seasoned in IRC know the context and usage.  

Conventionally, by the above example notations of the command, the parts enclosed with the square brackets "[" & "]" are optional.   And you don't literally issue the characters "<", ">", "[", or "]".

Traditionally in IRC, and now Matrix, giving the kicked, or banned a reason is probably good practice. Those kicked or banned should understand why an IRC Op' (now Matrix Admin' **PL**100/Mod'/Custom PL), at their discretion, decided to do so.  And, IRC often has had the ability to issue a ban of a fixed duration, through 'bots.  So, users might be readmitted, automatically, after a time.

For such an example, with, more or less, a "services" bot, "X"; See: 
> /msg X ban <#channel> <nick!*@* | *!*userid@host> [duration] [leve] [reason]
https://cservice.undernet.org/docs/xcmds.txt
([sic] "[leve]" probably should be "[level}", which, as used, means the PL required to over-ride, 
chosen by the issuer, up to their own PL.)

Regardless, the API i.e. [kick](https://matrix.org/docs/api/client-server/#!/Room_membership/post_matrix_client_r0_rooms_roomId_kick) & [ban](https://matrix.org/docs/api/client-server/#!/Room_membership/post_matrix_client_r0_rooms_roomId_ban), they do show cURL context for the JSON, albiet POST is advised, over GET.

**Comment by mujx** [comment]
My question was what a homeserver should do with the `reason` field. How the user being kicked or banned should be notified by the server? 

I guess that the `reason` should be present in an event (probably `m.room.member` so the user will be notified when his membership changes) but I couldn't find something relevant in the spec.

**Comment by richvdh** [comment]
@mujx I think you're right.

@dbkr you were looking at this just recently IIRC: can you confirm?
