### ISSUE TITLE
Add matrix recorder to the Try Matrix page

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#813]
https://gitlab.com/argit/matrix-recorder

**Comment by MilkManzJourDaddy** [comment]
Users coming from IRC expect this functionality.  

It probably also deserves a fragment-anchored Wiki entry, hypothetically at: https://github.com/matrix-org/matrix-doc/

**Comment by oddvar** [comment]
added, thanks! f740e3fb083da304ea02d45d2df011c131f0b799
