### ISSUE TITLE
Allow Users to Hide: Joins and Parts, Changes of Avatars and Display Names, via Settings on HomeServers Instead of Each Client.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#815]
This is done on IRC, Client-Side.  Now Matrix has a Kitchen-Sink philosophy, and HSs could hold such settings for MXIDs, instead of, or in addition to rach client.  This is what makes this issue diffrent from others filed.  An option is to separate hiding each type of event, or lump them together.

**Comment by Half-Shot** [comment]
This is a request for clients, and I presume you mean https://github.com/vector-im/riot-web. Matrix already has a spec for specifying user settings.

**Comment by MilkManzJourDaddy** [comment]
Clearly the title specifies settings on MXIDs HSs, specifically for:
## Hiding: Joins and Parts, Changes of Avatars and Display Names, et cetera. 

And that would be the default for MXIDs, across their various clients, unless a client-specific override is afforded.  

Maybe there can be an API to look up the history of joins/parts, avatar history, and Display Name history, for those who really feel the need to stay on top of the latest Matrix happenings.  But for many, where some use changing of their Matrix Display Name, instead of "!nick <new_nickname>" as an IRC "away nickname", it can be annoying to many.  And that has a storied history:

> http://bisqwit.iki.fi/jutut/away.html
>
> https://sackheads.org/~bnaylor/spew/away_msgs.html

**Comment by MilkManzJourDaddy** [comment]
FWIW, there seems to be some sort of practice of working on features that would require being included in the Matrix protocol & specification, from the client aspect.  

Not being part of the core Development team, I can only speculate.  But, perhaps it is due to how end users request things, from the aspect of Matrix **clients**.  

This, in instances where those end users are unaware of the fact that, behind their client, there is a whole, wholly inclusive protocol and specification.  And, unlike in other protocols, such as IRC, generally Matrix features really need to be rolled into that wholly inclusive specification and protocol, and not just piecemeal in various client and server manifestations.

**Comment by richvdh** [comment]
closing this verbose issue in favour of https://github.com/vector-im/riot-web/issues/916. Any implementation would be shared across clients.
