### ISSUE TITLE
Expose DAG to clients

### ISSUE THREAD

**Issue by Lapin0t** [matrix-org/matrix-doc#819]
It would be really nice for a lot of applications of matrix to expose the underlying DAG of events within a room. Some usecases:

- clients can order the events how they wish (topological sort is not unique) or even display the links in the UI
- applications could begin using matrix as a generic distributed database for partially ordered messages (collaborative document edition, key-value stores, ...)

A proposal to expose the links: add a new field to all events containing a list of event ids. It could be named `parents`.

**Comment by dumblob** [comment]
ping

**Comment by maxidor** [comment]
The spec already [defines a way](https://github.com/matrix-org/matrix-doc/blob/master/api/client-server/definitions/sync_filter.yaml#L24) via sync filters to get the full events, including parents, auth events, etc.

**Comment by turt2live** [comment]
Now that the sync filter actually works in (develop) synapse, and the thing is possible for clients to use, I think this can be closed.

**Comment by ara4n** [comment]
i’m not sure the ability to request federation event fields via cs api is entirely deliberate, fwiw. but if it works...
