### ISSUE TITLE
matrix.org appears as mobile site on Chrome, macOS

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-doc#825]
![screen shot 2017-03-04 at 22 01 14](https://cloud.githubusercontent.com/assets/6750344/23582610/1f9a360a-0126-11e7-9bae-3debdf8d5673.png)

**Comment by ara4n** [comment]
it doesn't for me :) what version of chrome, and what screen size?

**Comment by lukebarnard1** [comment]
Version 56.0.2924.87 (64-bit), Screen resolution 2880 x 1800, window size as it is in the screenshot but changing it seems to have no effect.

**Comment by ara4n** [comment]
i can't explain this at all... can you doublecheck the UA settings in inspector? button on the top left which lets you test responsive design?

**Comment by lukebarnard1** [comment]
Sure... OK so I've got a couple of screenshots for a resolution of 618 x 845 (arbitrary). It seems like these should be the other way around...

Device type = Mobile:
![matrix org-](https://cloud.githubusercontent.com/assets/6750344/23589886/d9d3a69e-01cd-11e7-9c46-e458f66f5ace.png)

Device type = Desktop:
![matrix org- 1](https://cloud.githubusercontent.com/assets/6750344/23589888/e639a4e2-01cd-11e7-837d-60468905c5ee.png)

**Comment by lukebarnard1** [comment]
PEBKAC: I had by browser zoomed in and it caches per-site and persists apparently.
