### ISSUE TITLE
'Next' button in 'How does it work?' animation no longer works

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#827]
Since the .legend items are absolutely positioned, they are 'above' the Next button and catch the clicks.  Changing the padding-top to margin-top in the style for .legend should fix this.

**Comment by ara4n** [comment]
the whole theme had been accidentally upgraded from our custom Divi2 to stock Divi3 whilst preparing the next version of the website.  i'm amazed more things didn't explode. sorry for missing this!
