### ISSUE TITLE
Need to spec msisdn login API

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#829]
Documentation: https://docs.google.com/document/d/1-6ZSSW5YvCGhVFDyD2QExAUAdpCWjccvJT5xiyTTG2Y/edit#heading=h.79ot48krpkq7
Author: @dbkr 
PRs: #1390

**Comment by richvdh** [comment]
Also `/account/password/msisdn/requestToken`

**Comment by uhoreg** [comment]
PR was merged, and I forgot to close this.
