### ISSUE TITLE
Notifications appear to be targeting multiple devices

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#834]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1489414975108249jrELW:matrix.org

I've also noticed this. When chatting with someone in the web browser, my phone is also being notified of messages, despite me explicitly having the riot tab open.

This was working up until a week or so ago (as far as I can tell). 

*I'm also unsure of where to report concerns similar to this. I do recall that matrix-doc is the best place for infrastructure-related issues*

**Comment by richvdh** [comment]
matrix-doc is for doc issues...

could you file it at riot-web
