### ISSUE TITLE
Turn letsencrypt blog post into a proper guide

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#844]
From https://matrix.org/jira/browse/ORG-48.

Turn https://matrix.org/blog/2016/02/10/advanced-synapse-setup-with-lets-encrypt/ into a proper guide.

**Comment by turt2live** [comment]
Should this be moved to the matrix.org repo?

**Comment by richvdh** [comment]
yes. closing in favour of https://github.com/matrix-org/matrix.org/issues/101
