### ISSUE TITLE
spec the bulk_lookup API

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#853]
apparently we have an API called bulk_lookup? with no docs at all?

**Comment by dbkr** [comment]
This is the new sydent API for 3pid lookup, although it might be superseded by one where you don't have to do all the canonicalisation yourself

**Comment by richvdh** [comment]
` /_matrix/identity/api/v1/bulk_lookup` apparently

**Comment by maxidor** [comment]
Waiting this eagerly so it can be implemented into mxisd also!

**Comment by maxidor** [comment]
Done at https://github.com/eventually-matrix/matrix-doc/commit/9e71fd668972605ed98b4b275f10b4185bd9417a

**Comment by maxidor** [comment]
@richvdh This can be closed, done in #1069

**Comment by turt2live** [comment]
Closing: This does indeed appear to be in the spec.

https://matrix.org/docs/spec/identity_service/unstable.html#post-matrix-identity-api-v1-bulk-lookup
