### ISSUE TITLE
spec m.login.msisdn UI auth type

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-doc#855]
Documentation: https://docs.google.com/document/d/1B7q_3ruJzeQTg-uJHe1UScxbVLzgm451c25OjpYcojI/edit#
Author: @dbkr 

added as part of msisdn registration / signin

**Comment by richvdh** [comment]
gdocs link would be super-helpful here, @dbkr

**Comment by dbkr** [comment]
https://docs.google.com/document/d/1-6ZSSW5YvCGhVFDyD2QExAUAdpCWjccvJT5xiyTTG2Y/edit#heading=h.79ot48krpkq7

**Comment by richvdh** [comment]
it turns out that when we are talking about UI auth we don't mean UI auth, we mean /login, which makes this a dup of #829

**Comment by dbkr** [comment]
Sorry, there is a separate msisdn flow for UI auth that needs spec (it's what we use to register with a msisdn).

The doc for this is here: https://docs.google.com/document/d/1oBJ86MfFGZ4TE4YaM8I9ngY7R3FED74122jRM9C54-Y/edit
