### ISSUE TITLE
Mechanism for Forking Rooms, and Merging Rooms.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#859]
Although it might be possible to implement a very simple solution for the issue: [Mechanism for migrating portal rooms to plumbed rooms \#387](https://github.com/matrix-org/matrix-appservice-irc/issues/387), it does raise questions for this seperate issue, which is expected to currently be low priority.  
       
We must consider that in the history of IRC, it was more or less all one network.  That, until people had differences of opinion, including how IRC should work.  Hopefully, Matrix with it's all-inclusive standards, won't have that happen.

But, communities of federated rooms might find out they have irreconcilable differences, or opinions, or different goals.  So, instead of fighting over who keeps control of the room, fork it into other rooms, history, files, and perhaps membership.  Those who stay in each respective room would have to work out aliases.  

And, even if they are on different HomeServers, it is good for communities to be unified, in federated rooms that have consistent aliases.  So, the issue is weightier than just creating a new room with a variation on aliases.  

Also, people might find they are working towards the exact same end, and might want to merge rooms, but not close the old ones.  Moving aliases might be simple.  Merging rooms, history, and "fowarding" members, not so much.  

But, the issue should be sussed out.

**Comment by richvdh** [comment]
Merging rooms is more concisely expressed at https://github.com/vector-im/riot-web/issues/2299.

I'm not really sure what you expect for forking rooms. I think this is too blue-sky to bother having an open bug for.
