### ISSUE TITLE
Synapse implements different sendToDevice/

### ISSUE THREAD

**Issue by qznc** [matrix-org/matrix-doc#860]
What the spec tells me is to send content [like](https://github.com/matrix-org/matrix-doc/blob/bc6c5858ea51316e92f02f401c77cb00763e05a9/api/client-server/to_device.yaml#L74):

    {            
      "@alice:example.com": {
        "TLLBEANAAG": {
          "example_content_key": "value"
        }             
      }             
    }

However, Synapse [wants this wrapped in "messages"](https://github.com/matrix-org/synapse/blob/f5a4001bb116c468cc5e8e0ae04a1c570e2cb171/synapse/rest/client/v2_alpha/sendtodevice.py#L60):

    { "messages": see_above }

I'm confused, because the SDK seem [not](https://github.com/matrix-org/matrix-js-sdk/blob/d76e8be4ffa5e4b9726660976be7be929bfe35a2/src/crypto/index.js#L823) to implement that. With [my own implementation](https://github.com/qznc/d-matrix-client) I see "M_UNKNOWN Internal server error" without the wrap.

**Comment by richvdh** [comment]
I think you're misreading the spec. It does say the messages should be wrapped in `messages`: http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#put-matrix-client-unstable-sendtodevice-eventtype-txnid. The js-sdk implements that in `baseApis.sendToDevice` IIRC.
