### ISSUE TITLE
spec phone numbers 3PID lookup

### ISSUE THREAD

**Issue by maxidor** [matrix-org/matrix-doc#863]
[sydent](https://github.com/matrix-org/sydent) and riot clients now have support for phone numbers 3PID lookup but no spec to back it up.
As the author of [mxisd](https://github.com/kamax-io/mxisd), a formal spec is necessary at this point so this can be implemented.

Non-exhaustive list of important points to clarify in the spec:
- General
  - Medium ID to use (most likely `msisdn` ?)
  - To ensure compatibility between identity servers data, how should a msisdn be stored? As-is, or international?
- Input
  - In which format should the msisdn be provided: local (RFC?),  international (RFC?) or "as-is"
  - Any other attribute (local country of the user?)
- Output
  - Since we echo back the requested 3PID, should it be provided as-is, or should we transform it (international?)
- Resolution
  - If we are able to accept several format for the same msisdn, guidelines to handle resolution local <-> international

**Comment by dbkr** [comment]
There is actually nothing to spec here since, for now, it re-uses the same `/lookup` and `/bulk_lookup` APIs (the latter is waiting to be specced but that's an aside). It probably wouldn't hurt to make it clearer in the spec how this works though.

**Comment by maxidor** [comment]
For clarification, msisdn is the actual number format to use for phone numbers.
I've also updated the issue name to better reflect that we are talking about phone numbers here, using msisdn format.

**Comment by maxidor** [comment]
If I may: msisdn is confusing to people without a phone tech background.  
Spec documents should actually talk about phone numbers and only mention msisdn when talking about the format or lookup details.

**Comment by maxidor** [comment]
Part of this would be solved by #1039 and #1040.
What `msisdn` is should still be clarified in the spec.

**Comment by maxidor** [comment]
Unofficial documentation for this, aligned to current implementations: https://github.com/eventually-matrix/matrix-doc/commit/f1b192c5e109d6f9b92f5c5b54ef0cc5b161ab95

**Comment by uhoreg** [comment]
As the msisdn 3pid type is now documented, as well as the bulk lookup, is this issue fixed?

**Comment by maxidor** [comment]
There is another format used, so not fully done yet.

**Comment by turt2live** [comment]
I believe this is completed. The appendix says they use the E.164 numbering plan and do not include a `+`. With the lookup otherwise looking specified, I'm closing this.
