### ISSUE TITLE
Add Something like IRC /wallchops to Message Room Mod's, in Addition to "Report Content".

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#864]
If certain things are decided to be included, they should be added to the spec', so they are not overlooked.  I discovered that "Report Content" was missing from Riot-Web, and [asked a Dev' to address the issue](https://github.com/vector-im/riot-web/issues/3359).  

I looked in the Spec' for "report content", and searched for something like /wallchops.  And nothing came up.

For those unfamiliar with IRC, /wallchops sends messages to those who are (h)Op's (channel Operators/half-Operators), et cetera.  In Matrix, it probably should be decided by room Admin's, what Power Level is the threshhold for **receiving** something like /wallchops.  

Perhaps GUI/UX, it could be "Whisper-Message Room Moderators, **ONLY**"  In that, it seems related to ["whispering" in group rooms \#3345](https://github.com/vector-im/riot-web/issues/3345), but probably deserves it's own m.\* room message type.  

For Moderation, it could be a step below "Report Content", and useful to give a "Heads-UP" to Moderators, for issues specific to the room.  One such use-case is where it might be imperitive to change room settings/topics, for how the grand scheme of Matrix traffic would be effected, such as for [\(un\)"Piping" of Plumbed rooms \#387](https://github.com/matrix-org/matrix-appservice-irc/issues/387).

And, also, related to that, it could be a mechanism that (ro)bots/scripts might use, at the behest of HomeServer maintainers, for example.  The (ab)use-case should be considered, too.

**Comment by richvdh** [comment]
contacting admins would probably be better covered with something like #639

**Comment by heyakyra** [comment]
Should this be re-opened? It looks like it was superseded by #1033 but doesn't cover the use case of being able tag/@mention/whisper to moderators, does it? 

>"If you had tags, you could also mention @​moderators, @​everyone, @​first_time_users..."

https://github.com/matrix-org/matrix-doc/issues/639#issuecomment-256942091
