### ISSUE TITLE
Add a Label like "Needs-Spec' " to All Matrix Related Repo's and Make that Compulsory in the Specification.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#865]
It seems that most ordinary end-users drive issues from the client repo's here, as that is how they view the UX, from a client perspective...

But, IMHO, if things which might be considered compulsory or important are not spelled out in the spec', they might not get percolated into a dev's punch-list of to-do check-boxes to include, and such things subsequently get overlooked. [It happens](https://github.com/vector-im/riot-web/issues/3359).

In some repository, I thought I saw a bright yellow label, "needs-spec' ".  But, I don't see anything similar in the repo' for that oversight.  Looking quickly, I see: https://github.com/matrix-org/matrix-doc/labels/spec-omission

So, prompted by that omission I uncovered, what I advocate is a label in all Matrix related repo's, ala "needs-spec' ", similar to: https://github.com/matrix-org/matrix-doc/labels/spec-omission  And, furthermore, put in a reference in the spec' to include certain labels in each and every repository loosely related to Matrix.  That way, when an issue is raised, in context of a client, one that reflects across various client-servers then a label "needs-spec' " should be applied, so a developer might add to the specification.

**Comment by richvdh** [comment]
I'm not in favour of adding more labels to other repositories; it's unclear how that would help anything.
