### ISSUE TITLE
We need a nice table showing how to interpret m.room.member events

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#876]
One axis would show possible prev_content values; the other would show possible content values; and explain that join->join is a profile change, join->leave is either a leave or a kick, join->ban is a kickban, leave->ban is a ban, etc.

**Comment by t3chguy** [comment]
Initial: https://docs.google.com/spreadsheets/d/1jNZyt53RrvwnyPulJA0wUTTXFynS1pB6twPoUu0SUUI/edit?usp=sharing
