### ISSUE TITLE
device_lists missing from Spec 

### ISSUE THREAD

**Issue by pik** [matrix-org/matrix-doc#882]
matrix-js-sdk is using device_lists.changed (https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/sync.js#L676) to know when to refresh user devices, but how the notification process works or it's inclusion in `/sync` does not appear to be documented in the spec? 

```
    // data looks like:
    // {
    //    next_batch: $token,
    //    presence: { events: [] },
    //    account_data: { events: [] },
    //    device_lists: { changed: ["@user:server", ... ]},
```

**Comment by richvdh** [comment]
dup #797
