### ISSUE TITLE
Specification for determining which Olm Session to use if multiple are present

### ISSUE THREAD

**Issue by pik** [matrix-org/matrix-doc#892]
Currently the existing implementation (matrix-js-sdk) will use the session with the lowestID if multiple are present  (https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/OlmDevice.js#L377): 

    // Use the session with the lowest ID.
    sessionIds.sort();
    return sessionIds[0];

Since sessionIds are the same on both ends this seems like it is consistent as long as both clients have both sessions, but in the case of an orphaned session this may lead to errors? At the least this should be specified in the spec so that all clients may implement the same session selection method. 

For reference Open Whisper Systems uses the session with the last message received: 
https://whispersystems.org/docs/specifications/sesame/#overview

**Comment by richvdh** [comment]
Yes, this needs fixing, as per https://github.com/vector-im/riot-web/issues/2330. The sesame approach seems sensible.

**Comment by uhoreg** [comment]
It looks like what we need to spec is that if a client has multiple sessions:

- devices should use the session in which they last received a message when sending messages
- devices should expire old sessions (it looks like sesame maintains a list of inactive sessions, ordered by when they were last active, and drops sessions off the end of the list)

Is there anything else that needs spec-ing for this?
