### ISSUE TITLE
Unspec'd server_name request param for /join/{roomIdOrAlias} 

### ISSUE THREAD

**Issue by pik** [matrix-org/matrix-doc#904]
ref: https://github.com/matrix-org/synapse/issues/2171

Currently in order to join a room on a different (non-HS) server by roomId a `server_name` requestParam should be provided, this behavior is not documented. Also there are some clarifying points that I'm not sure about, for example the current synapse endpoint accepts `remote_host_names` non-singular (what is the significance of joining the same room on multiple servers, is this even possible ? ). If the answer to the later that joining a room by room_id is always  / only a singular action than possibly Synapse should be extracting `server_name` from the `<opaque_id>:<server_name>` combo and deprecate the arg in requestParams.

**Comment by richvdh** [comment]
@Kegsay apparently you added this in https://github.com/matrix-org/synapse/pull/794; was the intention that it become part of the spec? do you know if there is already a bug to track it?

**Comment by Kegsay** [comment]
There isn't a bug to track it. It seems like a useful thing to have, and it was originally added to aid Go-NEB development which originally was going to be hosted on a different HS.

It's **a** solution to the problem of "I have a room ID, I know that I can join it via server X because I was told out-of-band, so please just try."

**Comment by t3chguy** [comment]
ooi why doesn't it go on the room-id specific endpoint (http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-unstable-rooms-roomid-join) also, should probably be generalised to `serverName` to match casing of other query params.

**Comment by Matrixcoffee** [comment]
@turt2live Does d279fdafa6e649f4dd8ea2dd4a89e559c633a3f3 mean that the extra homeserver parameter is now part of the spec-to-be?

**Comment by turt2live** [comment]
Yup! It's currently sitting in unstable, scheduled for r0.4.0 by the end of the month.
