### ISSUE TITLE
Add new Read Marker API to docs

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-doc#910]
Documentation: https://docs.google.com/document/d/1UWqdS-e1sdwkLDUY0wA4gZyIkRp-ekjsLZ8k6g_Zvso/edit

SPEC: Synapse changes here, https://github.com/matrix-org/synapse/pull/2120
JS-SDK changes: https://github.com/matrix-org/matrix-js-sdk/pull/419/files

**Comment by turt2live** [comment]
More information: https://docs.google.com/document/d/1UWqdS-e1sdwkLDUY0wA4gZyIkRp-ekjsLZ8k6g_Zvso/edit
