### ISSUE TITLE
Clarify registration / UI auth documentation 

### ISSUE THREAD

**Issue by pik** [matrix-org/matrix-doc#912]
Just glancing at the [Spec](https://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-register), it seems that switching from `api/v1/register` to `client/r0/register` should be as simple as moving authentication details into the `auth: <AuthenticationData>` JSON and calling it a day. 

Unfortunately it seems `type: m.login.password` registration flow has been irrevocably deprecated (https://github.com/matrix-org/synapse/issues/2205) - the current flow as inferred from what Riot does involves making a request with `{username: 'my_user', password: 'my_password'}` registration request and than following the `m.login.dummy` flow. Contrary to what is suggested by 
> type	string	Required. The login type that the client is attempting to complete.

Type is not required nor useful in the first request - in other words even if the server accepts non-interactive login flows (`m.login.dummy`) it is impossible to achieve that within the context of a single request (sending a `type: m.login.dummy` request without an existing `session_id` registers a guest user).

**Comment by dbkr** [comment]
You can complete (or attempt to complete) user-interactive auth in the same way as before by just sending the request with `m.login.dummy` auth and no session ID - we should make this clear in the doc.

**Comment by dbkr** [comment]
This should include speccing how HSes remember the parameters from the first call to the request.

**Comment by pik** [comment]
Oh, I see - the key got changed from `user` -> `username` and the other `username` / `password` params remain outside of the `auth` body.

**Comment by dbkr** [comment]
Correct

**Comment by richvdh** [comment]
I'm unclear what actually needs changing here. I do remember there being some business with some parameters being remembered between calls, but can't remember what - @dbkr can you clarify?

It's worth noting that the head version of the spec (http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#changelog) does contain some clarifications to the user-interactive auth section, so I recommend using that as a starting point.

**Comment by richvdh** [comment]
> I'm unclear what actually needs changing here.

Clarity has not been forthcoming in the last 3 months, so closing this in the hope that anybody still confused can submit a more concise issue
