### ISSUE TITLE
matrix.org home page has broken link to Try Matrix page

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#916]
under the 'Show me  the code' section, it has a link that says 'https://matrix.org/blog/try-matrix-now' and links to 'https://matrix.org/try-matrix-now'.  Even though 'https://matrix.org/blog/try-matrix-now' redirects to the correct page, the href=https://matrix.org/try-matrix-now is broken.

**Comment by ara4n** [comment]
fixed, thanks.
