### ISSUE TITLE
"knocking" (requesting access) to invite-only rooms (SPEC-60)

### ISSUE THREAD

**Issue by heyakyra** [matrix-org/matrix-doc#932]
via: https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1496963122369440lUphj:matrix.org

**Comment by richvdh** [comment]
The linked conversation says:

> [might] there ever be an option to allow requests to join invite-only rooms? so that mods can vet join 

Matthew (`@matthew:matrix.org`)
> yes, there was once the concept of 'knocking' on a room
> but was removed from the spec as nothing had implemented it
> could file a bug against matrix-doc to add it back

(related to https://matrix.org/jira/browse/SPEC-60 which *appears* to have been closed by mistake)

**Comment by ara4n** [comment]
here's someone asking for it again:

<img width="841" alt="screen shot 2018-05-04 at 02 13 02" src="https://user-images.githubusercontent.com/1294269/39609418-b4287c0a-4f40-11e8-97b6-a225fc1a2c2c.png">

**Comment by madduck** [comment]
I'm definitely raising my hand on this one, @ara4n and @richvdh. I'm trying to move a community of roughly 300 people to Matrix, and neither of the two available options are good enough:

1. Relying on security-by-obscurity, i.e. that the room link never leaks, is not an option, really.
2. Please don't expect me to collect the usernames or email addresses used by 300 people, and then invite them to the room. Sure, I could script that, but there is no way I'll ever get all 300 people to give me these details in due time.

However, I can get them to install the client and then request to join a room, or at least I am a lot more confident about that, then I am about the invitation path.

**Comment by richvdh** [comment]
I think this has been fixed by #3154.
