### ISSUE TITLE
Deleting a room with associated contents (messages and uploaded files)

### ISSUE THREAD

**Issue by saintger** [matrix-org/matrix-doc#948]
It is currently not possible to delete a room with all associated contents (messages and uploaded files).
Especially in the case of abandoned rooms (rooms which everyone has left), the content is useless and could be safely deleted.
However in the current (and seemingly future) of Matrix, there isn't any relation between the stored uploaded file and the room where it has been uploaded.

Some kind of workaround can be done by deleting local media which are older than a specified timestamp but that approach may delete old files which are however still relevant for some other rooms.

Relevant issues:

- https://github.com/matrix-org/synapse/issues/2340
- https://github.com/matrix-org/synapse/issues/2339
- https://github.com/matrix-org/synapse/issues/2338
- https://github.com/matrix-org/synapse/issues/1730
- https://github.com/vector-im/riot-web/issues/3994
- https://github.com/vector-im/riot-web/issues/722

**Comment by t3chguy** [comment]
Files do not get uploaded to a room, and multiple rooms may refer to the same file, this is how the forward feature works in Riot
so the following is not quite true:
> the content is useless and could be safely deleted.

**Comment by xuhdev** [comment]
What about text though? Text may be useless.

**Comment by richvdh** [comment]
dip #1882
