### ISSUE TITLE
File upload / resume behavior sub-par on flaky connections

### ISSUE THREAD

**Issue by Nebukadneza** [matrix-org/matrix-doc#949]
Hi All,

recently I’ve noticed that file upload is not quite optimal with flaky connections. One practical example: A friend’s hiking in the mountains and wants to send me ~5 photos he took the day. The internet up there is not only slow, but also flaky — i.e., it drops every now and then, more often than one’d like. What Riot / Synapse *seem* to do today is something like: let’s try to upload the chunk (one complete file) and if that fails, retry after 5/10/15 seconds again. However, since no single transfer of a ~800KByte file will succeed, all uploads will fail, presenting the user (in case of riot) with a „failed — cancel or resend“-warning.

While I also know that comparing Matrix/Riot/Synapse to other proprietary solutions, I’d like to point out that both the dreaded WhatsApp as well as XMPP/Conversations (with HTTPUpload) have succeeded to send full files in this situation, regardless of intermittent connection drops.

I’m filing this issue in -doc, because from what I’ve read in quick source-reads as well as reading existing issues from riot-android and matrix-synapse, I think this needs to be addressed on both server and client end.

Thanks for all your hard and great work so far ^_^.
Best,
-Dario

**Comment by richvdh** [comment]
Please can you file this at riot-android (or whichever client your friend is using). It may need server-side changes too but we can decide on that later.
