### ISSUE TITLE
Typo in event schema example

### ISSUE THREAD

**Issue by DigitalChiller** [matrix-org/matrix-doc#961]
In this [https://github.com/matrix-org/matrix-doc/blob/master/event-schemas/examples/m.room.member%23invite_room_state#L20](url)  "join_rules" has a trailing 's'. Is that a typo? Everywhere else in the specs "join_rules" doesn't have that 's'.

**Comment by t3chguy** [comment]
has been fixed by recent PR.

**Comment by richvdh** [comment]
Indeed, fixed by @krombel in #963. Thanks krombel!
