### ISSUE TITLE
Add groups stuff to spec

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#971]
Documentation: [Proposal](https://docs.google.com/document/d/1cTK2pKolWNXspL69knpDJkcQWZsHpsMDTc2X_dEB5XQ), [API summary](https://docs.google.com/document/d/1F2i1q7Kk4DKMtSaUzwj8CoNkDDwNFu0Uc2xPzJ2Mx00/edit), [semi-accurate API details](https://docs.google.com/document/d/17RHQ4Fw_cltmF1ABvDp7P4q65Kk65vi6HAaNbXgjjJE)
Author: @erikjohnston

**Comment by richvdh** [comment]
Also m.room.related_groups, which doesn't seem to be in the google doc

**Comment by non-Jedi** [comment]
Would be really helpful on this one to have some indication (even if in a comment afterward) on how those three docs relate to each other.

**Comment by richvdh** [comment]
This has been in production for over a year, so it's a bit late to be arguing about the proposal now. Which sucks, but here we are.

**Comment by ara4n** [comment]
i'm not so sure. the current system in production has a *lot* of issues, and i at least am worried about speccing them into concrete in the current API shape, at least until we've decided what the medium/long-term plan is here.

**Comment by ptman** [comment]
#1772

**Comment by turt2live** [comment]
I'm declaring this as obsolete now that [MSC1772](https://github.com/matrix-org/matrix-doc/issues/1772) (Spaces, or Communities v2, or Groups v2) is in FCP. We anticipate that Spaces will take over the spec, and that Groups will never make it into an official spec document.
