### ISSUE TITLE
update FAQ on 'Who is funding Matrix.org?'

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#979]
as amdocs is no longer providing funding.  Also "What kind of company is Matrix.org" needs to be updated with the fact that it is now incorporated.

**Comment by uhoreg** [comment]
Proposed text for some sections (I tried to keep most of the original wording where possible):

> *Who is funding Matrix.org?*
>
> For the first three years of Matrix's development, most of the core contributors worked an [Amdocs](http://amdocs.com/).  In the summer of 2017, as a result of cuts to funding, New Vector was spun off from Amdocs, and the core team is funded by a combination of community support (via [Patreon](https://www.patreon.com/matrixdotorg), [Liberapay](https://liberapay.com/matrixdotorg/), Bitcoin, and Ethereum), and corporate sponsorship.  Current corporate sponsors can be found on our [sponsors page](https://matrix.org/blog/supporters/).  If you would like to support the core Matrix team as a member of the community, please visit our Patreon or Liberapay pages, or you can send us Bitcoin at 1LxowEgsquZ3UPZ68wHf8v2MDZw82dVmAE or Ethereum at ETH 0xA5f9a4f9E024F6D727f7afdA9257e22329A97485.  If you would like to sponsor the team as a corporation, or are interested in custom development, please [get in touch](mailto:matthew@matrix.org).
>
> *Who is building Matrix*
>
> The core team is ~12 people with extensive experience in building custom VoIP and Messaging apps for mobile network operators.  Most of us work for New Vector, but there are an increasing number of contributors from other companies and folks all over the internet.

I have not attempted to write anything for "What kind of company is Matrix.org" because I don't know what the structure is.

**Comment by ara4n** [comment]
i've merged this in - thanks :)
