### ISSUE TITLE
Make Matrix user online / unavailable (idle) / offline status per device instead of per account on Server

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-doc#980]
At now online / unavailable / offline states of user are global for account. But user can be offline on one device, online on other and unavailable on third device. 

So when user on one device goes unavailable/offline, Matrix client sends corresponding presence event to Matrix server, and other users will see that he jump offline, even it stay online on other device. After short time this state must be overwritten by any online client on `/sync` event, but users will see short jump online-offline-online, that is not so good.

For solve this "jumps", will be good to store presence state info on server side per device, and show aggregated presence status in user info.

**Comment by richvdh** [comment]
I'm struggling to understand your description of the problem, but I'm not convinced it's a spec issue.
