### ISSUE TITLE
Regexp in dump-swagger.py looks wrong

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix-doc#982]
`dump-swagger.py` uses the following regexp to (as far as I can tell) take the major version number together with the leading "r": `"^(r\d)+(\.\d+)*$"` (taking the first group out of the match, if there's a match). `(r\d)+` would match a string like "r1r2" but not a string like "r12". Is that intended or a typo?

**Comment by richvdh** [comment]
typo, I'd have thougt
