### ISSUE TITLE
Document the /account/3pid/delete route

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#985]
A `POST` on this route with an object like:

```json
{
    "medium": "email",
    "address": "hello@example.tld"
}
```

removes the given 3PID from the homeserver's local database (with no interaction with an identity server).

I'm not sure it belongs here since it's an `unstable` route (`/_matrix/client/unstable/account/3pid/delete`) but since Synapse and Riot have been implementing and using for months now (https://github.com/matrix-org/synapse/pull/1714) I thought it could be considered as an omission from the spec.

**Comment by turt2live** [comment]
Note: there's a proposal that moves to have this route unbind

https://github.com/matrix-org/matrix-doc/issues/1194
