### ISSUE TITLE
Specify the /rooms/{roomID}/joined_members client endpoint

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#993]
This endpoint behave exactly like the `/rooms/{roomID}/members` endpoint but only responds with the joined members whereas the latter responds with all membership events including `leave` and `invite` events.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-doc/issues/734

**Comment by babolivier** [comment]
Indeed. The endpoint was mentioned in a PR linked to #734 (and the issue isn't related to this specific endpoint) so my search didn't return it.
